//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface MNBannerItem : SBUIBannerItem
{
}

- (void)updateFromGuidanceChange:(id)arg1;
- (_Bool)matchingGuidanceInfo:(id)arg1;

@end