//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundEditor : IDESourceCodeEditor
{
    NSMutableArray *_sectionViewControllers;
    IDEPlaygroundEditorStackView_ML *_editorStackView;
    IDEPlaygroundSourceTextScrollView *_topLevelPlaygroundScrollView;
    id <DVTCancellable> _clipViewFillToken;
    NSCountedSet *_countedToysSelectedInRegisteredToyboxes;
    NSMutableSet *_toysSelectedInRegisteredToyboxes;
    struct _NSRange _lastEditedCharRangeForExecution;
    BOOL _lastEditedCharRangeWasInComment;
    struct _NSRange _lastSelectedRange;
    struct _NSRange _lastSelectedLineRange;
    DVTObservingToken *_sessionInProgressObserverToken;
    DVTObservingToken *_autoterminationDelayObservingToken;
    DVTObservingToken *_timelineScrubberEnabledObservingToken;
    id <NSObject> _sourceTextSettingsChangedObserver;
    double _minSidebarWidth;
    BOOL _playgroundExecutionEnabled;
    BOOL _playgroundExecutionWasEverScheduled;
    BOOL _disableReplayingSerializedResults;
    NSMapTable *_toyboxEditorToSelectedToyObserverTokensMap;
    BOOL _alreadySetUp;
    DVTPerformanceMetric *_loadPerformanceMetric;
    DVTPerformanceMetric *_closePerformanceMetric;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (double)defaultPlaygroundSidebarWidth;
+ (void)setDefaultPlaygroundSidebarWidth:(double)arg1;
+ (void)initialize;
- (void).cxx_destruct;
- (id)_playgroundActivityReporter;
- (void)_registerPlaygroundDocumentWithActivityReporter;
- (void)selectRepresentationType:(unsigned long long)arg1;
- (void)selectGraphResultInlineRepresentation:(id)arg1;
- (void)selectMultipleResultInlineRepresentation:(id)arg1;
- (void)selectSingleResultInlineRepresentation:(id)arg1;
- (void)toggleQuickLookInline:(id)arg1;
- (void)presentError:(id)arg1 delegate:(id)arg2 didPresentSelector:(SEL)arg3 contextInfo:(void *)arg4;
- (void)executePlaygroundFromSerializedData;
- (void)execute:(id)arg1;
- (void)cancelExecution;
- (void)executePlayground;
- (void)scheduleDelayedPlaygroundExecution;
- (void)scheduleImmediatePlaygroundExecution;
- (void)schedulePlaygroundExecutionWithDelay:(double)arg1;
- (BOOL)executeOnSourceChanges;
@property(getter=isPlaygroundExecutionEnabled) BOOL playgroundExecutionEnabled;
- (void)auxiliarySourceModuleChangedNotification:(id)arg1;
- (double)textView:(id)arg1 constrainAccessoryAnnotationWidth:(double)arg2;
- (double)textView:(id)arg1 constrainMaxAccessoryAnnotationWidth:(double)arg2;
- (double)textView:(id)arg1 constrainMinAccessoryAnnotationWidth:(double)arg2;
- (double)_minimumSidebarWidth;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)textDidChange:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (struct _NSRange)textView:(id)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
- (id)annotationContextForTextView:(id)arg1;
- (unsigned long long)textView:(id)arg1 lineEndingForWritingSelectionToPasteboard:(id)arg2 type:(id)arg3;
- (unsigned long long)textView:(id)arg1 lineEndingForReadingSelectionFromPasteboard:(id)arg2 type:(id)arg3;
- (id)sdk;
- (id)languageService;
- (id)playgroundContext;
- (void)navigateToAnnotationWithRepresentedObject:(id)arg1 wantsIndicatorAnimation:(BOOL)arg2 exploreAnnotationRepresentedObject:(id)arg3;
- (id)currentSelectedDocumentLocations;
@property(readonly, copy) NSArray *playgroundSectionViewControllers;
- (void)unregisterToyboxEditor:(id)arg1;
- (void)registerToyboxEditor:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)commitStateToDictionary:(id)arg1;
- (BOOL)validateInlineResultRepresentation:(unsigned long long)arg1 forMenuItem:(id)arg2 context:(id)arg3;
- (BOOL)validateSelectGraphResultInlineRepresentationMenuItem:(id)arg1 context:(id)arg2;
- (BOOL)validateSelectMultipleResultInlineRepresentationMenuItem:(id)arg1 context:(id)arg2;
- (BOOL)validateSelectSingleResultInlineRepresentationMenuItem:(id)arg1 context:(id)arg2;
- (BOOL)validateToggleQuickLookInlineMenuItem:(id)arg1 context:(id)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)primitiveInvalidate;
- (void)didSetupEditor;
- (void)takeFocus;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;

// Remaining properties
@property(readonly) IDEPlaygroundDocument *document; // @dynamic document;
@property(retain) NSMutableSet *mutableToysSelectedInRegisteredToyboxes; // @dynamic mutableToysSelectedInRegisteredToyboxes;
@property(readonly) IDEPlaygroundTextView *textView; // @dynamic textView;
@property(readonly, copy) NSSet *toysSelectedInRegisteredToyboxes; // @dynamic toysSelectedInRegisteredToyboxes;

@end