//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBICDataSetRep (DisplayAdditions)
+ (id)keyPathsForValuesAffectingIbInspectedUniversalTypeIdentifier;
+ (id)assetRepWithRepIdentifier:(id)arg1 forPasteboardReferencedFilePath:(id)arg2;
- (id)image;
- (id)icon;
@property(copy) NSString *ibInspectedUniversalTypeIdentifier;
@end