//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBPlatformToolFailureContext : NSObject <IBDiagnosticsHandlerConfigurator>
{
    IBAbstractPlatformToolProxy *_tool;
    IBPlatformToolDescription *_toolDescription;
    IBPlatformToolLaunchContext *_launchContext;
    IBAbstractPlatformToolExecutionContext *_executionContext;
    IBAbstractInterfaceBuilderPlatformToolManager *_manager;
}

+ (id)contextWithTool:(id)arg1;
@property(retain, nonatomic) IBAbstractInterfaceBuilderPlatformToolManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) IBAbstractPlatformToolExecutionContext *executionContext; // @synthesize executionContext=_executionContext;
@property(retain, nonatomic) IBPlatformToolLaunchContext *launchContext; // @synthesize launchContext=_launchContext;
@property(retain, nonatomic) IBPlatformToolDescription *toolDescription; // @synthesize toolDescription=_toolDescription;
@property(retain, nonatomic) IBAbstractPlatformToolProxy *tool; // @synthesize tool=_tool;
- (void).cxx_destruct;
- (void)configureDiagnosticsHandler:(id)arg1;
- (id)effectiveToolName;
- (id)initWithTool:(id)arg1 toolDescription:(id)arg2 launchContext:(id)arg3 executionContext:(id)arg4 toolProxyManager:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end