//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBPlatformToolRequester : NSObject
{
    IBTargetRuntime *_targetRuntime;
    double _scaleFactor;
    id <IBPlatformToolRequestProcessor> _requestProcessor;
    IBMutableOrderedDictionary *_pendingRequestsByID;
    IBSemaphore *_waitingRequestSemaphore;
    IBMutableOrderedDictionary *_finishedRequestsByID;
    NSMutableSet *_cancelledRequestIDs;
    NSObject<OS_dispatch_queue> *_processingQueue;
    NSString *_waitingRequestID;
    long long _batchSize;
    IBLiveViewsManager *_liveViewsManager;
}

@property(readonly, nonatomic) IBLiveViewsManager *liveViewsManager; // @synthesize liveViewsManager=_liveViewsManager;
- (void).cxx_destruct;
- (void)processRequests;
- (id)_connectToToolProxyReturningFailedLoadResult:(id *)arg1;
- (void)processResults;
- (BOOL)waitForRequestWithID:(id)arg1 timeout:(id)arg2;
- (void)cancelRequestWithID:(id)arg1;
- (id)issueRequestWithData:(id)arg1 diagnosticsBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)initWithTargetRuntime:(id)arg1 scaleFactor:(id)arg2 liveViewsManager:(id)arg3 batchSize:(long long)arg4 requestProcessor:(id)arg5;
- (id)init;

@end