//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBStackViewEmbeddingPolicy : IBSubviewEmbeddingPolicy
{
}

- (BOOL)canEmbedObjects:(id)arg1 shouldRestrictedToSibilingViews:(BOOL)arg2 fromDocument:(id)arg3;
- (struct CGRect)layoutFrameForContainer:(id)arg1 byAligningToLayoutFrame:(struct CGRect)arg2 orientation:(long long)arg3 alignment:(long long)arg4;
- (id)canvasPositionOrderedItemsForObjects:(id)arg1 forOrientation:(long long)arg2;
- (id)createContainerForObjects:(id)arg1 toParent:(id)arg2 fromDocument:(id)arg3 context:(id)arg4;
- (long long)inferredStackViewOrientationFromObjects:(id)arg1 forDocument:(id)arg2 outInferredAlignment:(long long *)arg3;
- (BOOL)supportsFillAlignment;
- (long long)inferOrientationFromLayoutOfObjects:(id)arg1 inDocument:(id)arg2;
- (id)embedObjects:(id)arg1 fromDocument:(id)arg2 context:(id)arg3;
- (void)performEmbedWithObjects:(id)arg1 withStrategy:(long long)arg2 inDocumentEditor:(id)arg3;
- (void)performEmbedWithObjects:(id)arg1 inDocumentEditor:(id)arg2;

@end