//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBStoryboardCanvasFrameTitleView : DVTLayoutView_ML
{
    NSAttributedString *_cachedTitle;
    NSValue *_cachedTitleSize;
    NSFont *_font;
    NSString *_title;
    NSColor *_titleColor;
    NSImage *_image;
    NSView *_closeButton;
    long long _alignment;
}

@property(nonatomic) long long alignment; // @synthesize alignment=_alignment;
@property(copy, nonatomic) NSView *closeButton; // @synthesize closeButton=_closeButton;
@property(copy, nonatomic) NSImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSColor *titleColor; // @synthesize titleColor=_titleColor;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSFont *font; // @synthesize font=_font;
- (void).cxx_destruct;
- (BOOL)isOpaque;
- (void)drawRect:(struct CGRect)arg1;
- (void)sizeToFit;
- (void)layoutBottomUp;
- (double)effectiveImageWidth;
- (double)effectiveCloseButtonWidth;
- (struct CGSize)effectiveTitleSize;
- (void)invalidateCachedTitle;
- (id)effectiveAttributedTitle;
- (id)firstLineOfTitle;
- (id)initWithFrame:(struct CGRect)arg1;

@end