//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBUIMakeClassAccessibleImplementations : NSObject
{
}

+ (id)keyPathsForValuesAffectingIbInspectedIsAccessibilityElement;
+ (id)keyPathsForValuesAffectingIbInspectedAccessibilityTraits;
+ (void)registerMarshallingRecordHandlers;
+ (void)ibPopulateAdditionalInspectors:(id)arg1 forCategory:(id)arg2;
- (void)setIbInspectedIsAccessibilityElement:(BOOL)arg1;
- (BOOL)ibInspectedIsAccessibilityElement;
- (id)ibInspectedAccessibilityTraits;
- (void)setIbInspectedAccessibilityTraits:(id)arg1;
- (void)setIsAccessibilityElement:(id)arg1;
- (id)isAccessibilityElement;
- (void)setAccessibilityTraits:(id)arg1;
- (id)accessibilityTraits;
- (void)setAccessibilityIdentifier:(id)arg1;
- (id)accessibilityIdentifier;
- (void)setAccessibilityHint:(id)arg1;
- (id)accessibilityHint;
- (void)setAccessibilityLabel:(id)arg1;
- (id)ibCocoaTouchAccessibilityConfiguration;
- (id)ibLocalAttributeKeyPaths;
- (id)ibLocalLocalizableStringsAttributeKeyPaths;
- (void)setAccessibilityConfiguration:(id)arg1;
- (id)accessibilityLabel;
- (id)accessibilityConfiguration;

@end