//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PreferencesRemoteUIDelegate : NSObject <RUIObjectModelDelegate, RUILoaderDelegate>
{
    UINavigationController *_navigationController;
    PSCloudStorageOffersManager *_storageOffersManager;
    NSMutableArray *_objectModels;
    RUILoader *_loader;
    NSMutableArray *_deleteLoaders;
    NSOperationQueue *_deleteQueue;
    PreferencesRemoteUIDelegateTableCellButton *_button;
    int _forceActionSignal;
    _Bool _cancelled;
    int _deleteAllDocumentsAttemptCount;
    id <DelayedPushDelegate> _delegate;
    RUILoader *_lastDocumentDeleteLoader;
}

@property(retain) RUILoader *lastDocumentDeleteLoader; // @synthesize lastDocumentDeleteLoader=_lastDocumentDeleteLoader;
@property(nonatomic) __weak id <DelayedPushDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reloadQuotaInfo;
- (void)loadQuotaInfo;
- (unsigned long long)supportedInterfaceOrientations;
- (void)loader:(id)arg1 didFailWithError:(id)arg2;
- (void)loader:(id)arg1 receivedObjectModel:(id)arg2 actionSignal:(int)arg3;
- (void)objectModelPressedBack:(id)arg1;
- (void)_popObjectModelAnimated:(_Bool)arg1;
- (_Bool)objectModel:(id)arg1 page:(id)arg2 deletedTableRow:(id)arg3 atIndexPath:(id)arg4 withURL:(id)arg5 httpMethod:(id)arg6;
- (void)objectModel:(id)arg1 page:(id)arg2 toggledEditing:(_Bool)arg3;
- (void)confirmDeleteWithTitle:(id)arg1 prompt:(id)arg2 explanation:(id)arg3 confirmationAction:(CDUnknownBlockType)arg4;
- (void)confirmDeleteAll;
- (void)deleteAllDocuments;
- (void)objectModel:(id)arg1 pressedLink:(id)arg2 httpMethod:(id)arg3;
- (void)objectModel:(id)arg1 pressedButton:(id)arg2 attributes:(id)arg3;
- (void)popAndReloadFromRemoteUI:(_Bool)arg1 additionalHeaders:(id)arg2;
- (void)reloadTopControllerWithAdditionalHeaders:(id)arg1;
- (void)loadURL:(id)arg1 postBody:(id)arg2;
- (void)loadURL:(id)arg1 postBody:(id)arg2 additionalHeaders:(id)arg3;
- (void)cleanupLoader;
- (void)cancelRemoteUI;
- (id)parentViewControllerForObjectModel:(id)arg1;
- (void)willShowController:(id)arg1;
- (void)dealloc;
- (id)initWithNavigationController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end