//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface QuotaRequestManager : NSObject
{
    NSOperationQueue *_requestQueue;
    NSObject<OS_dispatch_queue> *_quota_info_queue;
    QuotaInfoResponse *_quotaInfo;
    _Bool _quotaInfoIsDetailed;
    NSMutableDictionary *_appDetailsCache;
}

+ (id)noAccountError;
+ (id)sharedManager;
- (void).cxx_destruct;
- (void)getAppDetailsForBundleIDs:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)appDetailsForBundleIDs:(id)arg1 error:(id *)arg2;
- (void)clearCachedAppDetails;
- (void)getQuotaInfoDetailed:(_Bool)arg1 handler:(CDUnknownBlockType)arg2;
- (id)quotaInfoDetailed:(_Bool)arg1 error:(id *)arg2;
- (id)_sendSynchronousAARequest:(id)arg1;
- (void)noteQuotaInfoChanged;
- (void)clearCachedQuotaInfo;
- (id)init;

@end