//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoDroppedPinMapItem : MKMapItem
{
}

- (id)name;
- (id)_mk_nano_placecardIcon;
- (_Bool)_nano_isDroppedPin;

@end