//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoGlanceLocationModeController : NSObject <MKMapViewDelegate, NanoReverseGeocodeObserver, GEOGizmoXPCInterface, RadiosPreferencesDelegate, NanoGlanceChromeModeController>
{
    NanoGlanceLocationHeaderView *_headerView;
    NanoReverseGeocodeProvider *_geocodeProvider;
    UIImageView *_mapSnapshotView;
    _Bool _mapIsFullyRendered;
    _Bool _visible;
    NanoGlanceLocationModeLoadingIndicatorController *_loadingIndicatorController;
    id <LoadingToken> _locatingUserToken;
    id <LoadingToken> _mapSnapshotToken;
    id <LoadingToken> _mapLoadingToken;
    NSXPCConnection *_deviceConnectivityConnection;
    _Bool _connected;
    _Bool _inAirplaneMode;
    RadiosPreferences *_radiosPreferences;
    NanoGlanceChromeViewController *_chromeViewController;
}

+ (id)noLocationTitle;
+ (id)defaultMapTitle;
@property(nonatomic) ChromeViewController *chromeViewController;
- (void).cxx_destruct;
- (void)didChangePairedDeviceReachability:(_Bool)arg1;
- (void)updateNavigationRouteStatus:(id)arg1;
- (void)updateNavigationRouteDetails:(id)arg1 routeStatus:(id)arg2 routeContext:(id)arg3;
- (void)didChangeActiveTileGroup:(id)arg1;
- (void)airplaneModeChanged;
- (void)modeWillDisappear:(_Bool)arg1;
- (void)modeDidAppear:(_Bool)arg1;
- (void)modeWillAppear:(_Bool)arg1;
- (void)_updateHeaderIndicator;
- (void)_updateTitle;
- (id)_defaultTitle;
- (void)reverseGeocodeProvider:(id)arg1 geocodedTitle:(id)arg2;
- (void)reverseGeocodeProvider:(id)arg1 startedGeocodeType:(unsigned int)arg2;
- (void)mapViewDidFinishRenderingMap:(id)arg1 fullyRendered:(_Bool)arg2;
- (void)mapViewWillStartRenderingMap:(id)arg1;
- (void)mapViewDidFinishLoadingMap:(id)arg1;
- (void)mapViewDidFailLoadingMap:(id)arg1 withError:(id)arg2;
- (void)mapViewWillStartLoadingMap:(id)arg1;
- (void)_setNeedsConsiderRemovingSnapshot;
- (void)_considerRemovingSnapshot;
- (_Bool)_isShowingSnapshot;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (void)mapViewWillStartLocatingUser:(id)arg1;
- (id)launchURL;
- (id)headerView;
- (void)resignCurrentModeAnimated:(_Bool)arg1 toMode:(id)arg2;
- (void)becomeCurrentModeWithViews:(id)arg1 animated:(_Bool)arg2 state:(id)arg3 fromMode:(id)arg4;
- (void)_locationAuthorizationChanged:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end