//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _DKAudioInputMonitor : _DKMonitor
{
    AVAudioSession *_inputMonitor;
}

+ (id)_eventWithState:(id)arg1 type:(id)arg2 name:(id)arg3 identifier:(id)arg4 routeChangeReason:(id)arg5;
+ (id)entitlement;
+ (id)eventStream;
- (void).cxx_destruct;
- (void)onAudioRouteChangeNotification:(id)arg1;
- (void)stop;
- (void)start;

@end