//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _DKInteractionUtility : NSObject
{
}

+ (id)recentCallBundleId;
+ (id)interactionFromCalendarEvent:(id)arg1;
+ (id)_participantToContact:(id)arg1;
+ (id)interactionFromRecentCall:(id)arg1;
+ (id)interactionFromTelephonyCall:(struct __CTCall *)arg1;

@end