//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _DKSleepPredictor : NSObject
{
}

+ (id)findAllSleepPeriodsInDayStarting:(id)arg1 FromActivityProbabilities:(id)arg2;
+ (id)findSleepPeriodInDayStarting:(id)arg1 FromActivityProbabilities:(id)arg2;
+ (id)gatherBitmapHistoryFromStore:(id)arg1 forPeriod:(id)arg2;
+ (id)generateActivityBitmapFor:(id)arg1 From:(id)arg2;

@end