//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSArray (Range)
+ (id)rangeFrom:(id)arg1 to:(id)arg2 stride:(id)arg3;
+ (id)rangeFrom:(id)arg1 toInclusive:(id)arg2;
+ (id)rangeFrom:(id)arg1 to:(id)arg2;
@end