//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface BKHIDServiceInfo : NSObject
{
    struct __IOHIDService *_hidService;
    NSString *_displayUUID;
    int _eventSource;
    unsigned long long _senderID;
    unsigned int _primaryUsagePage;
    unsigned int _primaryUsage;
    float _maxForce;
    _Bool _swallowEvents;
    _Bool _capsLockOn;
    unsigned char _countryCode;
    _Bool _touchPad;
    unsigned int _keyDownCount;
    unsigned int _keyboardType;
    NSString *_keyboardLayout;
    struct __GSKeyboard *__gsKeyboard;
    unsigned int _touchCount;
    BKEventDestination *_currentDestination;
}

@property(nonatomic, getter=isTouchPad) _Bool touchPad; // @synthesize touchPad=_touchPad;
@property(retain, nonatomic) BKEventDestination *currentDestination; // @synthesize currentDestination=_currentDestination;
@property(nonatomic) unsigned int touchCount; // @synthesize touchCount=_touchCount;
@property(readonly, nonatomic) struct __GSKeyboard *_gsKeyboard; // @synthesize _gsKeyboard=__gsKeyboard;
@property(copy, nonatomic) NSString *keyboardLayout; // @synthesize keyboardLayout=_keyboardLayout;
@property(nonatomic) unsigned int keyboardType; // @synthesize keyboardType=_keyboardType;
@property(nonatomic) unsigned char countryCode; // @synthesize countryCode=_countryCode;
@property(nonatomic, getter=isCapsLockOn) _Bool capsLockOn; // @synthesize capsLockOn=_capsLockOn;
@property(nonatomic, getter=shouldSwallowEvents) _Bool swallowEvents; // @synthesize swallowEvents=_swallowEvents;
@property(nonatomic) unsigned int keyDownCount; // @synthesize keyDownCount=_keyDownCount;
- (void)_completeDigitizerInit;
- (void)_setDisplayUUID:(id)arg1;
- (void)_setSenderID:(unsigned long long)arg1;
- (void)watchForRemoval:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) float maxForce;
- (void)setExternalKeyboardEventSource;
- (unsigned int)primaryUsage;
- (unsigned int)primaryUsagePage;
- (unsigned long long)senderID;
- (int)eventSource;
- (id)displayUUID;
- (struct __IOHIDService *)copyHIDService;
- (id)description;
- (void)dealloc;
- (id)initWithHIDService:(struct __IOHIDService *)arg1;

@end