//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FitnessUIPageControlAccessibility : __FitnessUIPageControlAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)accessibilityIncrement;
- (void)accessibilityDecrement;
- (void)_axUpdateStateForDetailView;
- (id)_axDetailView;

@end