//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CLAvailabilityTile : PBCodable <NSCopying>
{
    double _availabilityZScoreConfidenceInterval;
    unsigned int _locationOfInterestMergeRadiusKM;
    unsigned int _preferPredictionWithinNActivityCycles;
    unsigned int _prefetchMaxFloorCount;
    unsigned int _prefetchRadiusKM;
    NSMutableArray *_venues;
    struct {
        unsigned int availabilityZScoreConfidenceInterval:1;
        unsigned int locationOfInterestMergeRadiusKM:1;
        unsigned int preferPredictionWithinNActivityCycles:1;
        unsigned int prefetchMaxFloorCount:1;
        unsigned int prefetchRadiusKM:1;
    } _has;
}

@property(retain, nonatomic) NSMutableArray *venues; // @synthesize venues=_venues;
- (void)mergeFrom:(id)arg1;
- (unsigned int)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasPreferPredictionWithinNActivityCycles;
@property(nonatomic) unsigned int preferPredictionWithinNActivityCycles; // @synthesize preferPredictionWithinNActivityCycles=_preferPredictionWithinNActivityCycles;
@property(nonatomic) _Bool hasLocationOfInterestMergeRadiusKM;
@property(nonatomic) unsigned int locationOfInterestMergeRadiusKM; // @synthesize locationOfInterestMergeRadiusKM=_locationOfInterestMergeRadiusKM;
@property(nonatomic) _Bool hasPrefetchMaxFloorCount;
@property(nonatomic) unsigned int prefetchMaxFloorCount; // @synthesize prefetchMaxFloorCount=_prefetchMaxFloorCount;
@property(nonatomic) _Bool hasPrefetchRadiusKM;
@property(nonatomic) unsigned int prefetchRadiusKM; // @synthesize prefetchRadiusKM=_prefetchRadiusKM;
@property(nonatomic) _Bool hasAvailabilityZScoreConfidenceInterval;
@property(nonatomic) double availabilityZScoreConfidenceInterval; // @synthesize availabilityZScoreConfidenceInterval=_availabilityZScoreConfidenceInterval;
- (id)venuesAtIndex:(unsigned int)arg1;
- (unsigned int)venuesCount;
- (void)addVenues:(id)arg1;
- (void)clearVenues;
- (void)dealloc;

@end