//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CLClientManagerUsageSyncManager : NSObject <IDSServiceDelegate>
{
    struct CLClientManager *_manager;
    _Bool _dirtyUsageSyncState;
    _Bool _needFullResync;
    _Bool _retryTimerSet;
    CLSilo *_silo;
    IDSService *_service;
    NSUUID *_pairedDeviceID;
    id _pairedDeviceRegistry;
    CLTimer *_retryTimer;
    NSMutableArray *_errorQueue;
    NSMutableDictionary *_messagesWaitingForAck;
}

@property(retain, nonatomic) NSMutableDictionary *messagesWaitingForAck; // @synthesize messagesWaitingForAck=_messagesWaitingForAck;
@property(retain, nonatomic) NSMutableArray *errorQueue; // @synthesize errorQueue=_errorQueue;
@property(retain, nonatomic) CLTimer *retryTimer; // @synthesize retryTimer=_retryTimer;
@property(nonatomic) _Bool retryTimerSet; // @synthesize retryTimerSet=_retryTimerSet;
@property(retain, nonatomic) id pairedDeviceRegistry; // @synthesize pairedDeviceRegistry=_pairedDeviceRegistry;
@property(retain, nonatomic) NSUUID *pairedDeviceID; // @synthesize pairedDeviceID=_pairedDeviceID;
@property(nonatomic) _Bool needFullResync; // @synthesize needFullResync=_needFullResync;
@property(nonatomic) _Bool dirtyUsageSyncState; // @synthesize dirtyUsageSyncState=_dirtyUsageSyncState;
@property(retain, nonatomic) IDSService *service; // @synthesize service=_service;
@property(retain, nonatomic) CLSilo *silo; // @synthesize silo=_silo;
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;
- (void)service:(id)arg1 account:(id)arg2 incomingMessage:(id)arg3 fromID:(id)arg4 context:(id)arg5;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;
- (void)handleMessageResyncResponseWithMessageData:(id)arg1;
- (void)handleMessageResyncRequestWithMessageData:(id)arg1;
- (void)handleMessagePromptWithMessageData:(id)arg1;
- (void)handleMessageUsageUpdateWithMessageData:(id)arg1;
- (void)handleMessageSendSuccessForIdentifier:(id)arg1;
- (void)handleMessageSendError:(id)arg1 identifier:(id)arg2;
- (void)sendAllUsageSyncData;
- (void)promptForClient:(id)arg1 authorizationStatus:(int)arg2 forcePrompt:(_Bool)arg3;
- (void)client:(id)arg1 didChangeUsageData:(id)arg2;
@property(nonatomic) long long highestReceivedSequenceNumber;
- (void)requestFullResync;
- (void)sendMessageWithMessageType:(id)arg1 dataPayload:(id)arg2 priority:(int)arg3 idsOptions:(id)arg4;
- (void)sendMessage:(id)arg1;
- (void)handleMessageError:(id)arg1;
- (void)messageFailedToSend:(id)arg1 withError:(id)arg2 recoverable:(_Bool)arg3;
- (void)drainErrorQueue;
- (void)addMessageToErrorQueue:(id)arg1;
- (_Bool)_sendMessage:(id)arg1 identifier:(id *)arg2 error:(id *)arg3;
- (void)handlePair;
- (void)handleUnpair;
- (void)handlePairNotification_bounce:(id)arg1;
- (void)handleUnpairNotification_bounce:(id)arg1;
- (void)dealloc;
- (id)initWithClientManager:(struct CLClientManager *)arg1 inSilo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end