//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CLLocationStreamer : CLIntersiloService <CLLocationStreamerServiceProtocol, CLLocationStreamingConnectionManagerClientProtocol>
{
    struct unique_ptr<CLLocationController_Type::Client, std::__1::default_delete<CLLocationController_Type::Client>> _locationClient;
    struct unique_ptr<CLPowerAssertion, std::__1::default_delete<CLPowerAssertion>> _powerAssertion;
    int _currentGranularity;
    CLTimer *_stopTimer;
    id <CLLocationStreamingConnectionManagerServiceProtocol> _streamingConnection;
    CLTimer *_aliveAgainThrottleTimer;
}

+ (_Bool)isSupported;
+ (id)getSilo;
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;
+ (void)becameFatallyBlocked:(id)arg1;
@property(retain, nonatomic) CLTimer *aliveAgainThrottleTimer; // @synthesize aliveAgainThrottleTimer=_aliveAgainThrottleTimer;
@property(retain, nonatomic) id <CLLocationStreamingConnectionManagerServiceProtocol> streamingConnection; // @synthesize streamingConnection=_streamingConnection;
@property(retain, nonatomic) CLTimer *stopTimer; // @synthesize stopTimer=_stopTimer;
@property(nonatomic) int currentGranularity; // @synthesize currentGranularity=_currentGranularity;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)pairedDeviceIsNearby:(_Bool)arg1;
- (void)successfullySentMessage:(id)arg1;
- (void)failedToSendMessage:(id)arg1 withError:(id)arg2 isFatal:(_Bool)arg3;
- (void)receivedMessageOfType:(id)arg1 withPayload:(id)arg2;
- (void)onLocationNotification:(const int *)arg1 withData:(const struct NotificationData *)arg2;
- (void)resetStopTimer;
- (void)startUpdatingLocationWithGranularity:(int)arg1;
- (void)stopLocation;
- (void)unregisterAllLocationNotifications;
- (void)sendAliveAgainMessage;
- (void)endService;
- (void)beginService;
- (id)initInSilo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end