//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CLSimulationControllerAdapter : CLIntersiloService <CLSimulationControllerProtocol>
{
    struct CLSimulationController *_controller;
}

+ (id)getSilo;
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;
+ (void)becameFatallyBlocked:(id)arg1;
@property(nonatomic) struct CLSimulationController *controller; // @synthesize controller=_controller;
- (void)setTravellingSpeed:(double)arg1;
- (void)setLocationInterval:(double)arg1;
- (void)setIntermediateLocationDistance:(double)arg1;
- (void)setRepeatBehavior:(int)arg1;
- (void)setSimulationType:(int)arg1;
- (void)clearPendingLocations;
- (void)addPendingLocationsArray:(id)arg1;
- (void)startSimulation;
- (void)stopSimulation;
- (void)setSimulationScenarioURL:(id)arg1;
- (void)shutdown;
- (void)endService;
- (void)beginService;
- (id)initInSilo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end