//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NRRecoveryStepRemoteUnpair : NSObject <NSCoding, IDSServiceDelegate, NRRecoveryStep>
{
    NRRecoveryManager *_recoveryManager;
    IDSService *_idsService;
    NSString *_sentMessageID;
    NSObject<OS_dispatch_queue> *_queue;
    NSUUID *_deviceID;
    NSString *_advertisedName;
}

+ (void)setAbortReason:(id)arg1;
+ (void)setPairingErrorCode:(unsigned long long)arg1;
+ (void)setRemoteUnpairRequestID:(id)arg1;
+ (void)clearGlobals;
+ (void)clearObliterationEnabled;
+ (_Bool)isObliterationEnabled;
+ (void)setObliterationEnabled;
+ (void)setObliterationEnabled:(_Bool)arg1;
+ (void)_globalUnlock;
+ (void)_globalLock;
+ (void)_makeGlobalLock;
@property(retain, nonatomic) NSString *advertisedName; // @synthesize advertisedName=_advertisedName;
@property(retain, nonatomic) NSUUID *deviceID; // @synthesize deviceID=_deviceID;
- (void).cxx_destruct;
- (void)_handleWillUnpairResponse:(id)arg1;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;
- (void)_sendMessageResponseWithDevice:(id)arg1;
- (void)_sendMessageWithDevice:(id)arg1;
- (void)_setUpIDSAndSendMessageWithAccounts:(id)arg1 andDevices:(id)arg2;
- (void)service:(id)arg1 devicesChanged:(id)arg2;
- (void)service:(id)arg1 activeAccountsChanged:(id)arg2;
@property(readonly, copy) NSString *description;
- (void)invalidate;
- (double)start:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAdvertisedName:(id)arg1 andPairedBluetoothDeviceID:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end