//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NRRegistryProxy : NRXPCProxy <NRPairedDeviceRegistryXPCDaemonDelegate>
{
    _Bool _pairing;
    NSUUID *_clientUUID;
}

@property(retain, nonatomic) NSUUID *clientUUID; // @synthesize clientUUID=_clientUUID;
@property(nonatomic) _Bool pairing; // @synthesize pairing=_pairing;
- (void).cxx_destruct;
- (void)xpcAddRemoveRecoveryStepIDSFinalize:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)xpcAddRemoveRecoveryStepObliterate:(_Bool)arg1 withStatePath:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)xpcAddRemoveRecoveryStepResetNVRAM:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)xpcAddRemoveRecoveryStepICloudDeletePaymentCards:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)xpcAddRemoveRecoveryStepStockholmReset:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)xpcAddRemoveRecoveryStepIDSUnpair:(_Bool)arg1 withPairingDeviceID:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)xpcAddRemoveRecoveryStepUnpairBluetooth:(_Bool)arg1 withPairingDeviceID:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)xpcAddRemoveRecoveryStepDeletePairingStore:(_Bool)arg1 withPairingDeviceID:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)xpcAddRemoveRecoveryStepRemoteUnpair:(_Bool)arg1 withAdvertisedName:(id)arg2 andPairedDeviceID:(id)arg3 block:(CDUnknownBlockType)arg4;
- (void)xpcAddRemoveRecoveryStepIDSUnpairStart:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)xpcAddRemoveRecoveryStepDeleteAccounts:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)xpcAddRemoveRecoveryStepBackup:(_Bool)arg1 withPairingDeviceID:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)xpcAddRemoveRecoveryStepDisableDaemons:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)xpcSetObliterationEnabled:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)xpcTriggerRecovery:(CDUnknownBlockType)arg1;
- (void)xpcRecoveryDescription:(CDUnknownBlockType)arg1;
- (_Bool)_hasInternalEntitlement;
- (void)xpcRetriggerUnpairInfoDialogWithBlock:(CDUnknownBlockType)arg1;
- (void)xpcResumePairingClientCrashMonitoring:(CDUnknownBlockType)arg1;
- (void)xpcSuspendPairingClientCrashMonitoring:(CDUnknownBlockType)arg1;
- (void)xpcSubmitAlbertPairingReport:(CDUnknownBlockType)arg1;
- (void)xpcTriggerVersion4Workaround;
- (void)xpcQueryStatus:(id)arg1 statusData:(CDUnknownBlockType)arg2;
- (void)xpcSetValue:(id)arg1 forProperty:(id)arg2 deviceID:(id)arg3;
- (void)xpcEnterCompatibilityState:(unsigned short)arg1 withDeviceID:(id)arg2;
- (void)xpcPairingShouldContinue;
- (void)xpcNotifyPasscode:(id)arg1 withDeviceID:(id)arg2;
- (void)xpcNotifyActivationCompleted:(id)arg1 withSuccess:(_Bool)arg2;
- (void)xpcUnpairWithDeviceID:(id)arg1 shouldObliterate:(_Bool)arg2 operationHasBegun:(CDUnknownBlockType)arg3;
- (void)xpcAbortPairingReason:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)xpcGizmoPasscodeAdvertiseAndPairWithName:(id)arg1 operationHasBegun:(CDUnknownBlockType)arg2;
- (void)xpcGizmoOOBAdvertiseAndPairWithName:(id)arg1 operationHasBegun:(CDUnknownBlockType)arg2;
- (void)xpcCompanionPasscodePairWithDeviceID:(id)arg1 operationHasBegun:(CDUnknownBlockType)arg2;
- (void)xpcCompanionOOBDiscoverAndPairWithName:(id)arg1 withOutOfBandPairingKey:(id)arg2 operationHasBegun:(CDUnknownBlockType)arg3;
- (void)_setPairingAndUpdatePairingClients:(_Bool)arg1 withClientUDID:(id)arg2;
- (void)invalidationHandler;
- (void)interruptionHandler;
- (id)initWithConnection:(id)arg1 andEntitlements:(id)arg2 andDelegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end