//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol NRRegistryProxyDelegate <NSObject>
@property(readonly, nonatomic) unsigned long long devicesUpdateCounter;
@property(readonly, nonatomic) NRRecoveryManager *recoveryManager;
@property(readonly, nonatomic) long long minPairingCompatibilityVersion;
@property(readonly, nonatomic) long long maxPairingCompatibilityVersion;
@property(readonly, nonatomic) long long version4CompatibilityWorkaroundVersion;
@property(readonly, nonatomic) unsigned long long lastUnpairReason;
@property(readonly, nonatomic) NRStateMachine *machine;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *deviceQueue;
@property(readonly, nonatomic) NSMutableDictionary *pairedDevices;
@property(readonly, nonatomic) NSMutableDictionary *pairingClients;
@property(readonly, nonatomic) _Bool pairing;
- (void)xpcExpireTransactionAfterDelay;
- (void)xpcTransactionDidEnd;
- (void)xpcTransactionDidBegin;
- (NRDaemonDevice *)_deviceForDeviceID:(NSUUID *)arg1;
- (void)_appTerminatedAbortPairing;
- (void)shouldAddPairingClientWithBool:(_Bool)arg1 andClientUUID:(NSUUID *)arg2;
- (void)handleDeadPairingClient;
- (void)abortPairing;
@end