//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PWRGRingView : UIImageView
{
    NSMutableArray *_baseImages;
    UIImageView *_rotatedImage;
    float _ringWidth;
    int _onPercentage;
    UIColor *_onColor;
    UIColor *_offColor;
}

@property(retain, nonatomic) UIColor *offColor; // @synthesize offColor=_offColor;
@property(retain, nonatomic) UIColor *onColor; // @synthesize onColor=_onColor;
@property(nonatomic) int onPercentage; // @synthesize onPercentage=_onPercentage;
@property(nonatomic) float ringWidth; // @synthesize ringWidth=_ringWidth;
- (void).cxx_destruct;
- (id)_generateImageForPercentage:(float)arg1;
- (void)_generateImages;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end