//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface BookmarkFavoritesViewController : UIViewController <BookmarkFavoritesGridViewDelegate>
{
    WebBookmarkCollection *_collection;
    WebBookmarkList *_favoritesList;
    _Bool _showWhitelistFavorites;
    id <UIViewControllerPreviewing> _gridViewPreviewingContext;
    id <BookmarkFavoritesViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <BookmarkFavoritesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)bookmarkFavoritesGridViewLayoutType:(id)arg1;
- (void)bookmarkFavoritesGridView:(id)arg1 updatedContentSize:(struct CGSize)arg2;
- (void)bookmarkFavoritesGridView:(id)arg1 banFrequentlyVisitedSite:(id)arg2;
- (void)bookmarkFavoritesGridView:(id)arg1 promoteFrequentlyVisitedSite:(id)arg2 toFavoriteAtIndex:(unsigned long long)arg3;
- (void)bookmarkFavoritesGridViewDidReorderBookmarks:(id)arg1;
- (void)bookmarkFavoritesGridView:(id)arg1 deleteBookmark:(id)arg2;
- (void)bookmarkFavoritesGridView:(id)arg1 editBookmark:(id)arg2;
- (void)bookmarkFavoritesGridView:(id)arg1 didReorderBookmarkFromIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (_Bool)bookmarkFavoritesGridViewShouldReorderBookmarks:(id)arg1;
- (void)didTapOutsideBookmarkFavoritesGridView:(id)arg1;
- (void)bookmarkFavoritesGridView:(id)arg1 didSelectBookmark:(id)arg2;
- (void)bookmarkFavoritesGridView:(id)arg1 activityWasSelected:(id)arg2;
- (void)setScrollViewScrollsToTop:(_Bool)arg1;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (void)loadFavoritesList;
- (void)_updateFavoritesListDueToBookmarksReload:(_Bool)arg1;
- (void)_recomputeFrequentlyVisitedSitesIfNecessary;
- (void)_updateVisibleFrequentlyVisitedSites;
- (void)_receivedFrequentlyVisitedSitesDidChangeNotification:(id)arg1;
- (void)_receivedBookmarksFolderContentChangedNotification:(id)arg1;
- (void)_receivedBookmarksReloadOrSpecialFolderChangeNotification:(id)arg1;
- (id)_bookmarkFavoritesGridView;
- (id)bookmarksNavigationController;
- (void)setAdjustedForSidebar:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)initWithBookmarksCollection:(id)arg1 showWhiteListFavorites:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end