//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol SearchUIRichTextItem <NSObject>

@optional
@property(readonly, copy, nonatomic) NSString *contentAdvisory;
@property(readonly, nonatomic) NSArray *icons;
@property(readonly, nonatomic) double starRating;
@property(readonly, nonatomic) unsigned long long textMaxLines;
@property(readonly, copy, nonatomic) NSString *formattedTextDelimiter;
@property(readonly, copy, nonatomic) NSArray *formattedTextItems;
@property(readonly, copy, nonatomic) NSString *text;
@end