//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WBSParsecTableAlignmentSchema (SearchUIConformance) <SearchUITableAlignmentSchema>
@property(readonly, nonatomic) NSArray *externalAlignments;
@property(readonly, nonatomic) id <SearchUITableMetaResult> meta;

// Remaining properties
@property(readonly, nonatomic) NSArray *columnsWithEqualWidths;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSArray *internalAlignments;
@property(readonly) Class superclass;
@end