//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRArticlePageViewController : FRPageViewController <UIPageViewControllerDelegate, UIPageViewControllerDataSource, ADInterstitialAdDelegate, FRCompressingToolbarViewControllerChild, FRReportActivityDelegate, FRReportSubmissionDelegate, FCReadingHistoryObserving, FRPageViewControllerDelegate, FRPageViewControllerDataSource, UIViewControllerRestoration>
{
    _Bool _allowPaging;
    _Bool _articleIsLiked;
    _Bool _articleIsSaved;
    FRFeldsparContext *_feldsparContext;
    id <FRArticlePageViewDataSource> _pageViewDataSource;
    id <FRArticlePageViewDelegate> _pageViewDelegate;
    id <FCHeadlineProviding> _lastShownHeadline;
    id <FCHeadlineProviding> _currentShowingHeadline;
    ADInterstitialAd *_interstitialAd;
    FRInterstitialAdViewController *_interstitialViewController;
    unsigned long long _interstitialAdStatus;
    NSString *_headlineIDForAd;
    UIViewController *_previousArticleViewController;
    UIViewController *_nextArticleViewController;
    UIViewController *_currentArticleViewController;
    NSArray *_pendingPresentedViewControllers;
    CDUnknownBlockType _progressBlock;
    id <FCFeedTheming> _feedTheme;
    FCFeedDescriptor *_feed;
    UIToolbar *_bottomToolbar;
    UIBarButtonItem *_shareBarButtonItem;
    UIBarButtonItem *_likeBarButtonItem;
    UIBarButtonItem *_saveBarButtonItem;
    UIImage *_likeImage;
    UIImage *_notLikedImage;
    UIImage *_savedImage;
    UIImage *_notSavedImage;
    long long _articleLikingActionWhenArticleShown;
    long long _articleLikingActionAfterArticleShown;
    long long _readingListAddRemoveUserActionWhenArticleShown;
    long long _readingListAddRemoveUserActionAfterArticleShown;
    unsigned long long _articleLikingStatus;
    long long _articleViewingState;
}

+ (id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2;
+ (id)storyboardIdentifier;
+ (id)viewControllerForArticleViewController:(id)arg1 feldsparContext:(id)arg2 storyboard:(id)arg3;
+ (id)viewControllerFromStoryboard:(id)arg1;
@property(nonatomic) long long articleViewingState; // @synthesize articleViewingState=_articleViewingState;
@property(nonatomic) unsigned long long articleLikingStatus; // @synthesize articleLikingStatus=_articleLikingStatus;
@property(nonatomic) long long readingListAddRemoveUserActionAfterArticleShown; // @synthesize readingListAddRemoveUserActionAfterArticleShown=_readingListAddRemoveUserActionAfterArticleShown;
@property(nonatomic) long long readingListAddRemoveUserActionWhenArticleShown; // @synthesize readingListAddRemoveUserActionWhenArticleShown=_readingListAddRemoveUserActionWhenArticleShown;
@property(nonatomic) long long articleLikingActionAfterArticleShown; // @synthesize articleLikingActionAfterArticleShown=_articleLikingActionAfterArticleShown;
@property(nonatomic) long long articleLikingActionWhenArticleShown; // @synthesize articleLikingActionWhenArticleShown=_articleLikingActionWhenArticleShown;
@property(retain, nonatomic) UIImage *notSavedImage; // @synthesize notSavedImage=_notSavedImage;
@property(retain, nonatomic) UIImage *savedImage; // @synthesize savedImage=_savedImage;
@property(nonatomic) _Bool articleIsSaved; // @synthesize articleIsSaved=_articleIsSaved;
@property(retain, nonatomic) UIImage *notLikedImage; // @synthesize notLikedImage=_notLikedImage;
@property(retain, nonatomic) UIImage *likeImage; // @synthesize likeImage=_likeImage;
@property(nonatomic) _Bool articleIsLiked; // @synthesize articleIsLiked=_articleIsLiked;
@property(retain, nonatomic) UIBarButtonItem *saveBarButtonItem; // @synthesize saveBarButtonItem=_saveBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *likeBarButtonItem; // @synthesize likeBarButtonItem=_likeBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *shareBarButtonItem; // @synthesize shareBarButtonItem=_shareBarButtonItem;
@property(retain, nonatomic) UIToolbar *bottomToolbar; // @synthesize bottomToolbar=_bottomToolbar;
@property(retain, nonatomic) FCFeedDescriptor *feed; // @synthesize feed=_feed;
@property(retain, nonatomic) id <FCFeedTheming> feedTheme; // @synthesize feedTheme=_feedTheme;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(copy, nonatomic) NSArray *pendingPresentedViewControllers; // @synthesize pendingPresentedViewControllers=_pendingPresentedViewControllers;
@property(retain, nonatomic) UIViewController *currentArticleViewController; // @synthesize currentArticleViewController=_currentArticleViewController;
@property(retain, nonatomic) UIViewController *nextArticleViewController; // @synthesize nextArticleViewController=_nextArticleViewController;
@property(retain, nonatomic) UIViewController *previousArticleViewController; // @synthesize previousArticleViewController=_previousArticleViewController;
@property(copy, nonatomic) NSString *headlineIDForAd; // @synthesize headlineIDForAd=_headlineIDForAd;
@property(nonatomic) unsigned long long interstitialAdStatus; // @synthesize interstitialAdStatus=_interstitialAdStatus;
@property(retain, nonatomic) FRInterstitialAdViewController *interstitialViewController; // @synthesize interstitialViewController=_interstitialViewController;
@property(retain, nonatomic) ADInterstitialAd *interstitialAd; // @synthesize interstitialAd=_interstitialAd;
@property(retain, nonatomic) id <FCHeadlineProviding> currentShowingHeadline; // @synthesize currentShowingHeadline=_currentShowingHeadline;
@property(retain, nonatomic) id <FCHeadlineProviding> lastShownHeadline; // @synthesize lastShownHeadline=_lastShownHeadline;
@property(nonatomic) _Bool allowPaging; // @synthesize allowPaging=_allowPaging;
@property(nonatomic) __weak id <FRArticlePageViewDelegate> pageViewDelegate; // @synthesize pageViewDelegate=_pageViewDelegate;
@property(nonatomic) __weak id <FRArticlePageViewDataSource> pageViewDataSource; // @synthesize pageViewDataSource=_pageViewDataSource;
@property(retain, nonatomic) FRFeldsparContext *feldsparContext; // @synthesize feldsparContext=_feldsparContext;
- (void).cxx_destruct;
- (void)readingHistoryDidChange:(id)arg1 forArticleIDs:(id)arg2;
- (void)reportSubmitted;
- (id)fillReportConcernObject;
- (void)reportActivityWantsToPerformAction:(id)arg1;
- (void)_updateSaveButtonAccessibilityLabel:(id)arg1;
- (void)_savedArticleToReadingList:(id)arg1;
- (void)_markArticleLikingStatus;
- (void)_updateLikeButtonAccessibilityLabel:(id)arg1 forStatus:(unsigned long long)arg2;
- (void)_likeArticle:(id)arg1;
- (void)_displayShareSheet:(id)arg1;
- (void)_updateStatusOfBarButtonItems;
- (void)_setBarButtonItemsOnTopBarHidden:(_Bool)arg1;
- (void)_setupBarButtonItemsOnTopBar;
- (void)_setupArticleLikingActionWithHeadline:(id)arg1;
- (void)_setupBottomToolbar;
- (void)_updateToolbarsForSizeClass:(long long)arg1;
- (void)_setupBarButtonItems;
- (void)interstitialAdDidUnload:(id)arg1;
- (void)interstitialAdDidLoad:(id)arg1;
- (void)interstitialAd:(id)arg1 didFailWithError:(id)arg2;
- (id)viewControllerInForwardDirection:(_Bool)arg1 currentViewController:(id)arg2;
- (void)updateTitleView;
- (void)cancelAdLoad;
- (void)clearInterstitial;
- (void)loadNewAd;
- (void)pageViewController:(id)arg1 didChangeVisibleViewControllerFromViewController:(id)arg2 direction:(int)arg3;
- (void)pageViewController:(id)arg1 willChangeToVisibleViewController:(id)arg2;
- (void)pageViewController:(id)arg1 willShowViewController:(id)arg2;
- (void)pageViewController:(id)arg1 viewController:(id)arg2 changedVisibilityFactor:(double)arg3;
- (id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2;
- (void)compressingToolbarViewControllerDidChangeScrollViewInsets:(id)arg1;
- (void)compressingToolbarViewControllerDidChangeCompression:(id)arg1;
- (_Bool)compressingToolbarViewControllerShouldCompress:(id)arg1;
- (id)bottomAccessoryBarForCompressingToolbarViewController:(id)arg1;
- (id)topAccessoryBarForCompressingToolbarViewController:(id)arg1;
- (id)_viewControllerRespondingToSelector:(SEL)arg1;
- (void)_sendAnalyticsEvent;
- (void)dealloc;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)_updateNavigationItemWithViewController:(id)arg1;
- (void)showWithHeadline:(id)arg1;
- (id)previewActionItems;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)didFinishPresenting;
- (void)willBeginPresenting;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setupWithFeldsparContext:(id)arg1;
- (void)_setupArticleViewController:(id)arg1;
- (void)loadWithHeadline:(id)arg1 indexPath:(id)arg2 feed:(id)arg3 theme:(id)arg4 feldsparContext:(id)arg5 articleContext:(id)arg6 feedContext:(id)arg7 storyboard:(id)arg8 playVideoOnAppearance:(_Bool)arg9;
- (void)loadWithHeadline:(id)arg1 indexPath:(id)arg2 feed:(id)arg3 theme:(id)arg4 feldsparContext:(id)arg5 feedContext:(id)arg6 storyboard:(id)arg7 playVideoOnAppearance:(_Bool)arg8;
- (id)_currentArticleViewController;
- (void)loadWithArticleViewController:(id)arg1 feldsparContext:(id)arg2 feed:(id)arg3 feedTheme:(id)arg4;
- (void)loadWithURL:(id)arg1 feldsparContext:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)fr_effectiveViewControllerInContainer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end