//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRFeedViewContext : NSObject
{
    long long _presentationReason;
    long long _feedPickerSection;
    NSURL *_sourceURL;
    NSString *_sourceApplication;
    NSString *_sourceSearchText;
    long long _displayRank;
}

+ (id)feedContextForQuickActions;
+ (id)feedContextForLocalNotification;
+ (id)feedContextForHandoff;
+ (id)feedContextForStateRestoration;
+ (id)feedContextForRelatedArticles;
+ (id)feedContextForSavedTabBarSelection;
+ (id)feedContextForLinkWithURL:(id)arg1 sourceApplication:(id)arg2;
+ (id)feedContextForSearchWithText:(id)arg1 displayRank:(long long)arg2;
+ (id)feedContextForSuggestionsWithDisplayRank:(long long)arg1 feedPickerSection:(long long)arg2;
+ (id)feedContextForSubscriptionsWithDisplayRank:(long long)arg1;
+ (id)feedContextForDefaultFeedOnLaunch;
+ (id)unknownFeedContext;
@property(nonatomic) long long displayRank; // @synthesize displayRank=_displayRank;
@property(copy, nonatomic) NSString *sourceSearchText; // @synthesize sourceSearchText=_sourceSearchText;
@property(copy, nonatomic) NSString *sourceApplication; // @synthesize sourceApplication=_sourceApplication;
@property(copy, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(nonatomic) long long feedPickerSection; // @synthesize feedPickerSection=_feedPickerSection;
@property(nonatomic) long long presentationReason; // @synthesize presentationReason=_presentationReason;
- (void).cxx_destruct;

@end