//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRFeedVideoCollectionViewCell : FRFeedCollectionViewCell <FRPlayerViewControllerDataSource, FRPlayerViewControllerObserver>
{
    FRPlayerViewController *_internalPlayerViewController;
    NSURL *_videoURL;
}

@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(readonly, nonatomic) FRPlayerViewController *internalPlayerViewController; // @synthesize internalPlayerViewController=_internalPlayerViewController;
- (void).cxx_destruct;
- (id)videoArticleViewContextForPlayerViewController:(id)arg1;
- (_Bool)isVideoInArticleForPlayerViewController:(id)arg1;
- (id)videoHeadlineForPlayerViewController:(id)arg1;
- (_Bool)videoAdSupportedForPlayerViewController:(id)arg1;
- (id)videoURLForPlayerViewController:(id)arg1;
- (void)playButtonPressedWithPlayerViewController:(id)arg1;
- (void)setMinimumAdDuration:(double)arg1;
- (void)populateWithHeadline:(id)arg1 theme:(id)arg2;
- (void)_createHeadlineViews;
- (void)_loadPlayerViewController;
- (void)layoutPlayerViewController;
- (void)prepareForReuse;
- (void)applyLayoutAttributes:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end