//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRFeedPickerCollectionViewController : UICollectionViewController <FRFeedBasedDataSourceDelegate, FRFeedPickerDelegate, UINavigationControllerDelegate, FRStackViewControllerAnimatorContext, UIGestureRecognizerDelegate, FRVisibleViewProviding, FRSubscriptionLimitExceededDelegate, FRReusableCellVisibilityMonitorObserving, FCOperationThrottlerDelegate, FRAppActivityBackgroundForegroundObserving, UIViewControllerPreviewingDelegate, UIViewControllerRestoration, FRStoryboardRestorableViewController>
{
    _Bool _isSuppressingColorSettings;
    _Bool _isObservingFeed;
    _Bool _viewControllerIsVisible;
    id <FRFeldsparContext> _feldsparContext;
    id <FRFeedPickerDelegate> _feedPickerDelegate;
    FRFeedPickerDataSource *_feedDataSource;
    FRCollectionViewFlowLayout *_pickerLayout;
    FRCollectionViewCellVisibilityMonitor *_cellVisibilityMonitor;
    FROfflineAwareViewControllerTransitionConductor *_transitionConductor;
    NSDate *_viewAppearDate;
    NSUUID *_viewAppearUUID;
    UISearchController *_searchController;
    FRTagSearchViewController *_tagSearchViewController;
    NSMutableArray *_updateBlocks;
    FRNoContentView *_noContentView;
    NSString *_lastSeenPreferredContentSizeCategory;
    unsigned long long _subscriptionsUpdateCount;
    FCOperationThrottler *_subscriptionsUpdateThrottler;
    id <UIViewControllerPreviewing> _previewingContext;
    struct CGRect _viewAppearFrameInScreen;
}

+ (id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2;
+ (id)storyboardIdentifier;
+ (id)viewControllerWithFeldsparContext:(id)arg1 storyboard:(id)arg2 isInitialViewController:(_Bool)arg3;
@property(retain, nonatomic) id <UIViewControllerPreviewing> previewingContext; // @synthesize previewingContext=_previewingContext;
@property(nonatomic) _Bool viewControllerIsVisible; // @synthesize viewControllerIsVisible=_viewControllerIsVisible;
@property(retain, nonatomic) FCOperationThrottler *subscriptionsUpdateThrottler; // @synthesize subscriptionsUpdateThrottler=_subscriptionsUpdateThrottler;
@property(nonatomic) unsigned long long subscriptionsUpdateCount; // @synthesize subscriptionsUpdateCount=_subscriptionsUpdateCount;
@property(copy, nonatomic) NSString *lastSeenPreferredContentSizeCategory; // @synthesize lastSeenPreferredContentSizeCategory=_lastSeenPreferredContentSizeCategory;
@property(retain, nonatomic) FRNoContentView *noContentView; // @synthesize noContentView=_noContentView;
@property(retain, nonatomic) NSMutableArray *updateBlocks; // @synthesize updateBlocks=_updateBlocks;
@property(retain, nonatomic) FRTagSearchViewController *tagSearchViewController; // @synthesize tagSearchViewController=_tagSearchViewController;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) struct CGRect viewAppearFrameInScreen; // @synthesize viewAppearFrameInScreen=_viewAppearFrameInScreen;
@property(copy, nonatomic) NSUUID *viewAppearUUID; // @synthesize viewAppearUUID=_viewAppearUUID;
@property(retain, nonatomic) NSDate *viewAppearDate; // @synthesize viewAppearDate=_viewAppearDate;
@property(retain, nonatomic) FROfflineAwareViewControllerTransitionConductor *transitionConductor; // @synthesize transitionConductor=_transitionConductor;
@property(retain, nonatomic) FRCollectionViewCellVisibilityMonitor *cellVisibilityMonitor; // @synthesize cellVisibilityMonitor=_cellVisibilityMonitor;
@property(nonatomic) _Bool isObservingFeed; // @synthesize isObservingFeed=_isObservingFeed;
@property(nonatomic) _Bool isSuppressingColorSettings; // @synthesize isSuppressingColorSettings=_isSuppressingColorSettings;
@property(retain, nonatomic) FRCollectionViewFlowLayout *pickerLayout; // @synthesize pickerLayout=_pickerLayout;
@property(retain, nonatomic) FRFeedPickerDataSource *feedDataSource; // @synthesize feedDataSource=_feedDataSource;
@property(nonatomic) __weak id <FRFeedPickerDelegate> feedPickerDelegate; // @synthesize feedPickerDelegate=_feedPickerDelegate;
@property(readonly, nonatomic) id <FRFeldsparContext> feldsparContext; // @synthesize feldsparContext=_feldsparContext;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *viewContentID;
@property(readonly, nonatomic) long long visibleViewType;
- (void)_updateLayout;
- (void)_updateLayoutIfDynamicTypePreferencesHaveChanged;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)_applicationWillEnterBackground:(id)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewViewControllerForItemAtIndexPath:(id)arg1;
- (void)feedDataSourceDidReloadData:(id)arg1;
- (void)feedDataSource:(id)arg1 wantsToPerformUpdate:(CDUnknownBlockType)arg2;
- (void)_handleUpdates;
- (id)contentIdentifier;
- (long long)viewType;
- (void)feedPicker:(id)arg1 didPickFeed:(id)arg2 feedContext:(id)arg3;
- (id)animatorForDismissingViewController:(id)arg1;
- (id)animatorForPresentingViewController:(id)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)_minimumLineSpacingForCollectionView:(id)arg1;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)exceededMaximumAllowedSubscription;
- (void)operationThrottler:(id)arg1 performAsyncOperationWithCompletion:(CDUnknownBlockType)arg2;
- (void)reusableCellVisibilityMonitor:(id)arg1 cellDidBecomeInvisible:(id)arg2 visibilityStartDate:(id)arg3 indexPath:(id)arg4;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)_endSuppressingColorSettingsUpdate;
- (void)_beginSuppressingColorSettingsUpdate;
- (void)didBecomeNotVisible;
- (void)didBecomeVisible;
- (_Bool)isViewVisible;
- (void)activityBackgroundForegroundObservingApplicationDidEnterBackground:(CDUnknownBlockType)arg1;
- (void)activityBackgroundForegroundObservingApplicationDidBecomeActive;
- (void)didReceiveMemoryWarning;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)_searchButtonItemTapped:(id)arg1;
- (void)showOrHideNoContentViewAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)viewDidLoad;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupWithFeldsparContext:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) long long fr_stackViewControllerPresentationStyle;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end