//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRFeedPickerTableViewCell : UITableViewCell <FRFeedPickerTableViewCellAddButtonDelegate, FRTagImageCacheObserving>
{
    unsigned long long _buttonType;
    FRFeedPickerTableViewCellLogoView *_logoImageView;
    UILabel *_titleLabel;
    FRFeedPickerTableViewCellAddButton *_button;
    id <FCTagProviding> _populatedTag;
}

@property(retain, nonatomic) id <FCTagProviding> populatedTag; // @synthesize populatedTag=_populatedTag;
@property(retain, nonatomic) FRFeedPickerTableViewCellAddButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) FRFeedPickerTableViewCellLogoView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(nonatomic) unsigned long long buttonType; // @synthesize buttonType=_buttonType;
- (void).cxx_destruct;
- (id)accessibilityContextForAddButton:(id)arg1;
- (void)tagImageCache:(id)arg1 didFetchImages:(id)arg2 forTag:(id)arg3;
- (void)populateWithTitle:(id)arg1 image:(id)arg2 section:(_Bool)arg3;
- (void)populateWithTag:(id)arg1 context:(id)arg2;
- (void)populateWithFeed:(id)arg1 context:(id)arg2;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)cellAddButtonPressed:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end