//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRGradientView : UIView
{
    _Bool _passThroughTouches;
}

+ (Class)layerClass;
@property(nonatomic) _Bool passThroughTouches; // @synthesize passThroughTouches=_passThroughTouches;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(nonatomic) struct CGPoint endPoint;
@property(nonatomic) struct CGPoint startPoint;
@property(copy, nonatomic) NSArray *locations;
@property(copy, nonatomic) NSArray *colors;

@end