//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRHeadlineZoomAnimator : NSObject <FRHeadlineAnimator>
{
    _Bool _premiumCell;
    id <FRHeadlineZoomAnimatorOrigin> _zoomOrigin;
    id <FRHeadlineZoomAnimatorDestination> _zoomDestination;
    UIView *_targetCell;
    CDUnknownBlockType _completion;
    NSString *_originImagePath;
}

@property(retain, nonatomic) NSString *originImagePath; // @synthesize originImagePath=_originImagePath;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool premiumCell; // @synthesize premiumCell=_premiumCell;
@property(retain, nonatomic) UIView *targetCell; // @synthesize targetCell=_targetCell;
@property(nonatomic) __weak id <FRHeadlineZoomAnimatorDestination> zoomDestination; // @synthesize zoomDestination=_zoomDestination;
@property(nonatomic) __weak id <FRHeadlineZoomAnimatorOrigin> zoomOrigin; // @synthesize zoomOrigin=_zoomOrigin;
- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
- (id)cellImageCoverView;
- (double)transitionDuration:(id)arg1;
- (id)initWithHeadlineZoomOrigin:(id)arg1 destination:(id)arg2 targetCell:(id)arg3 premiumCell:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end