//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol FRHeadlineZoomAnimatorOrigin <NSObject>
- (UIImage *)headlineZoomOriginContentsImage:(id <FRHeadlineAnimator>)arg1;
- (struct CGRect)headlineZoomOriginContentViewFrame:(id <FRHeadlineAnimator>)arg1;
- (UIColor *)headlineZoomOriginBackgroundColor:(id <FRHeadlineAnimator>)arg1;
- (struct CGRect)headlineZoomOriginImageFrame:(id <FRHeadlineAnimator>)arg1;
- (unsigned long long)headlineContentType:(id <FRHeadlineAnimator>)arg1;
- (struct CGRect)headlineZoomOriginContentsRect:(id <FRHeadlineAnimator>)arg1;
- (double)headlineZoomOriginTitleLabelTopInset:(id <FRHeadlineAnimator>)arg1;
- (struct CGRect)headlineZoomOriginFrame:(id <FRHeadlineAnimator>)arg1;
- (NSString *)headlineZoomOriginImagePath:(id <FRHeadlineAnimator>)arg1;
@end