//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRImageOnTopPremiumCellLayoutParameters : NSObject <NSCopying>
{
    unsigned long long _columnSpan;
    unsigned long long _rowSpan;
}

@property(nonatomic) unsigned long long rowSpan; // @synthesize rowSpan=_rowSpan;
@property(nonatomic) unsigned long long columnSpan; // @synthesize columnSpan=_columnSpan;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end