//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRLocalNotificationManager : NSObject
{
    id <FRLocalNotificationManagerDelegate> _delegate;
    id <FRFeldsparContext> _feldsparContext;
    FCKeyValueStore *_notificationStatistics;
}

+ (void)initialize;
@property(retain, nonatomic) FCKeyValueStore *notificationStatistics; // @synthesize notificationStatistics=_notificationStatistics;
@property(retain, nonatomic) id <FRFeldsparContext> feldsparContext; // @synthesize feldsparContext=_feldsparContext;
@property(nonatomic) __weak id <FRLocalNotificationManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_resetLocalNotificationTimer:(id)arg1;
- (void)_attemptToShowHeadlinesFromUserInfo:(id)arg1;
- (void)cancelAllLocalNotifications;
- (void)scheduleLocalNotifications;
- (void)updateLocalNotificationAnalytics;
- (_Bool)handleLocalNotification:(id)arg1;
- (void)dealloc;
- (id)initWithFeldsparContext:(id)arg1;
- (void)setupLocalNotificationActions;

@end