//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRPrerollAdInventory : FRAdInventory <ADBannerViewDelegate, ADBannerViewInternalDelegate>
{
    CDUnknownBlockType _completionBlock;
    ADBannerView *_bannerView;
}

+ (void)initialize;
@property(retain, nonatomic) ADBannerView *bannerView; // @synthesize bannerView=_bannerView;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;
- (void)bannerView:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (id)viewControllerForStoryboardPresentationFromBannerView:(id)arg1;
- (void)bannerViewDidLoadAd:(id)arg1;
- (void)requestPrerollWithContext:(id)arg1 adOpportunityIdentifier:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)purgeAllAdObjects;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end