//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRPrivacyGuardian : NSObject
{
    NSMapTable *_mapTable;
}

@property(retain, nonatomic) NSMapTable *mapTable; // @synthesize mapTable=_mapTable;
- (void).cxx_destruct;
- (id)anonymousUUIDWithFeedID:(id)arg1;
- (id)registerFeedID:(id)arg1;
- (id)init;

@end