//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRPublisherArticlesViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, FCReadingHistoryObserving, FRFeedCollectionViewCellDelegate, UIViewControllerPreviewingDelegate>
{
    id <FCFeedTheming> _theme;
    id <FRPublisherArticlesViewControllerDelegate> _delegate;
    NSArray *_publisherArticles;
    FCReadingHistory *_readingHistory;
    UICollectionView *_headlineCollectionView;
    UILabel *_headerLabel;
    UIButton *_nameImageButton;
    UIActivityIndicatorView *_activityIndicator;
    FREndOfArticleDataProvider *_dataProvider;
    UIView *_hairline;
    id <UIViewControllerPreviewing> _gesturePreviewingContext;
    id <UIViewControllerPreviewing> _headlinePreviewingContext;
}

@property(retain, nonatomic) id <UIViewControllerPreviewing> headlinePreviewingContext; // @synthesize headlinePreviewingContext=_headlinePreviewingContext;
@property(retain, nonatomic) id <UIViewControllerPreviewing> gesturePreviewingContext; // @synthesize gesturePreviewingContext=_gesturePreviewingContext;
@property(retain, nonatomic) UIView *hairline; // @synthesize hairline=_hairline;
@property(retain, nonatomic) FREndOfArticleDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIButton *nameImageButton; // @synthesize nameImageButton=_nameImageButton;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(retain, nonatomic) UICollectionView *headlineCollectionView; // @synthesize headlineCollectionView=_headlineCollectionView;
@property(retain, nonatomic) FCReadingHistory *readingHistory; // @synthesize readingHistory=_readingHistory;
@property(retain, nonatomic) NSArray *publisherArticles; // @synthesize publisherArticles=_publisherArticles;
@property(nonatomic) __weak id <FRPublisherArticlesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) id <FCFeedTheming> theme; // @synthesize theme=_theme;
- (void).cxx_destruct;
- (id)nameImageButtonWithFilePath:(id)arg1 headline:(id)arg2;
- (double)footerWhiteSpace;
@property(readonly, nonatomic) double contentHeight;
- (void)didTapNameImageButton:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)reloadDataWithHeadline:(id)arg1;
- (void)layoutForSize:(struct CGSize)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)readingHistoryDidChange:(id)arg1 forArticleIDs:(id)arg2;
- (void)feedCollectionViewCellShouldHideCensorLabel:(id)arg1;
- (void)setupRelatedHeadlinesCollectionView;
- (void)setupHeaderWithFilePath:(id)arg1 headline:(id)arg2;
- (void)setupActivityIndicator;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCloudContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end