//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRReportConcernManager : NSObject
{
    NSString *_cacheDirectory;
    FCCloudContext *_context;
}

@property(nonatomic) __weak FCCloudContext *context; // @synthesize context=_context;
@property(readonly, copy, nonatomic) NSString *cacheDirectory; // @synthesize cacheDirectory=_cacheDirectory;
- (void).cxx_destruct;
- (void)reportConcernToEndPoint:(id)arg1;
- (int)mapReportConcernType:(unsigned long long)arg1;
- (id)initWithContext:(id)arg1;

@end