//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRReportConcernCommand : FCCommand
{
    NSDictionary *_reportConcernData;
}

+ (void)initialize;
@property(copy, nonatomic) NSDictionary *reportConcernData; // @synthesize reportConcernData=_reportConcernData;
- (void).cxx_destruct;
- (id)_reportProtobufForReportDataDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)executeWithContext:(id)arg1 delegate:(id)arg2;
- (id)initWithReportConcernDict:(id)arg1;

@end