//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRShadowView : UIView
{
    UIColor *_shadowColor;
    double _shadowRadius;
    double _shadowOpacity;
    UIBezierPath *_shadowPath;
    struct CGSize _shadowOffset;
}

@property(retain, nonatomic) UIBezierPath *shadowPath; // @synthesize shadowPath=_shadowPath;
@property(nonatomic) double shadowOpacity; // @synthesize shadowOpacity=_shadowOpacity;
@property(nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset=_shadowOffset;
@property(nonatomic) double shadowRadius; // @synthesize shadowRadius=_shadowRadius;
@property(retain, nonatomic) UIColor *shadowColor; // @synthesize shadowColor=_shadowColor;
- (void).cxx_destruct;

@end