//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol FRTFeedComponentLayout <NSObject>
@property(readonly, nonatomic) unsigned long long rowSpan;
@property(readonly, nonatomic) NSArray *headlinesUsed;
@property(readonly, nonatomic) double rank;
- (NSArray *)preparedHeadlineCellContextsAtRowOrigin:(long long)arg1 columnOrigin:(long long)arg2 subBatchRowOffset:(long long)arg3 feedSettings:(FRTFeedSettings *)arg4;
@end