//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FRTopicToFeedZoomAnimator : NSObject <UIViewControllerAnimatedTransitioning>
{
    id <FRTopicToFeedZoomAnimatorTopicStartFrameProvider> _topicStartFrameProvider;
    id <UIViewControllerContextTransitioning> _transitionContext;
    UIView *_incomingViewSnapshot;
    UIView *_incomingNavigationBar;
    UIView *_incomingNavigationBarSuperview;
    FRShapeView *_buttonBorder;
    UIView *_buttonLabelSnapshot;
    UIView *_fromContentSnapshot;
    UIView *_fromNavigationBar;
    UIView *_fromNavigationBarSuperview;
    UIView *_containerView;
    UIView *_feedContentBackgroundView;
    UIViewController *_curtainViewController;
    NSValue *_startFrameValue;
    UIView *_contentView;
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSValue *startFrameValue; // @synthesize startFrameValue=_startFrameValue;
@property(retain, nonatomic) UIViewController *curtainViewController; // @synthesize curtainViewController=_curtainViewController;
@property(retain, nonatomic) UIView *feedContentBackgroundView; // @synthesize feedContentBackgroundView=_feedContentBackgroundView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *fromNavigationBarSuperview; // @synthesize fromNavigationBarSuperview=_fromNavigationBarSuperview;
@property(retain, nonatomic) UIView *fromNavigationBar; // @synthesize fromNavigationBar=_fromNavigationBar;
@property(retain, nonatomic) UIView *fromContentSnapshot; // @synthesize fromContentSnapshot=_fromContentSnapshot;
@property(retain, nonatomic) UIView *buttonLabelSnapshot; // @synthesize buttonLabelSnapshot=_buttonLabelSnapshot;
@property(retain, nonatomic) FRShapeView *buttonBorder; // @synthesize buttonBorder=_buttonBorder;
@property(retain, nonatomic) UIView *incomingNavigationBarSuperview; // @synthesize incomingNavigationBarSuperview=_incomingNavigationBarSuperview;
@property(retain, nonatomic) UIView *incomingNavigationBar; // @synthesize incomingNavigationBar=_incomingNavigationBar;
@property(retain, nonatomic) UIView *incomingViewSnapshot; // @synthesize incomingViewSnapshot=_incomingViewSnapshot;
@property(retain, nonatomic) id <UIViewControllerContextTransitioning> transitionContext; // @synthesize transitionContext=_transitionContext;
@property(nonatomic) id <FRTopicToFeedZoomAnimatorTopicStartFrameProvider> topicStartFrameProvider; // @synthesize topicStartFrameProvider=_topicStartFrameProvider;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGRect startFrame;
- (void)_addViewsToContainer;
- (void)_findFromViewExcerptResources;
- (_Bool)haveRequiredResources;
- (void)_findIncomingFeedAssets;
- (void)_completeTransition;
- (void)_performButtonLabelDismissTransition;
- (void)_performButtonBorderDismissTransition;
- (void)_performFromExcerptDismissTransition;
- (void)_performNavbarIncomingTransition;
- (void)_performFromNavbarDismissTransition;
- (void)_performIncomingFeedViewAlphaTransition:(CDUnknownBlockType)arg1;
- (void)_performButtonScaleTransition:(struct CGAffineTransform)arg1 feedTransform:(struct CGAffineTransform)arg2;
- (void)_performFeedScaleTransition:(struct CGAffineTransform)arg1 frame:(struct CGRect)arg2;
- (void)_performTransition;
- (void)_prepareForTransition;
- (void)animateTransition:(id)arg1;
- (void)_curtainUp;
- (void)_curtainDown;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end