//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface UIScrollView (FRAdditions)
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (struct CGPoint)fr_convertPointFromInsettedContentView:(struct CGPoint)arg1;
- (struct CGPoint)fr_convertPointFromContentView:(struct CGPoint)arg1;
- (struct UIEdgeInsets)fr_bounceInset;
@property(readonly, nonatomic) _Bool reachedBottom;
@end