//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SDActivityDeviceRecord : NSObject
{
    NSDate *_lastReceivedAdvertisementDate;
    _Bool _deviceTracked;
    _Bool _disableDuplicateFilterOnce;
    IDSDevice *_idsDevice;
    NSData *_lastRawAdvertisementData;
    NSUUID *_lastUsedKeyIdentifier;
    NSData *_lastAdvertisementData;
}

@property(readonly, copy, nonatomic) NSData *lastAdvertisementData; // @synthesize lastAdvertisementData=_lastAdvertisementData;
@property(retain, nonatomic) NSUUID *lastUsedKeyIdentifier; // @synthesize lastUsedKeyIdentifier=_lastUsedKeyIdentifier;
@property(readonly, copy, nonatomic) NSData *lastRawAdvertisementData; // @synthesize lastRawAdvertisementData=_lastRawAdvertisementData;
@property(nonatomic) _Bool disableDuplicateFilterOnce; // @synthesize disableDuplicateFilterOnce=_disableDuplicateFilterOnce;
@property(nonatomic) _Bool deviceTracked; // @synthesize deviceTracked=_deviceTracked;
@property(retain, nonatomic) IDSDevice *idsDevice; // @synthesize idsDevice=_idsDevice;
- (void).cxx_destruct;
@property(readonly, nonatomic) SFActivityAdvertisement *clientAdvertisement;
@property(readonly, copy, nonatomic) NSDictionary *lastAdvertisementOptions;
@property(readonly, copy, nonatomic) NSData *lastAdvertisementPayload;
@property(readonly, nonatomic) unsigned short lastCounter;
@property(readonly, nonatomic) CDStruct_a3f8c740 lastActivityAdvertisement;
@property(readonly, nonatomic) SDActivityDecryptionKey *decryptionKey;
- (void)updateWithRawAdvertisementData:(id)arg1 receivedViaScanning:(_Bool)arg2 isReplay:(_Bool)arg3 newAdvertisementHandler:(CDUnknownBlockType)arg4;
- (void)updateWithRawAdvertisementData:(id)arg1 receivedViaScanning:(_Bool)arg2 newAdvertisementHandler:(CDUnknownBlockType)arg3;
- (id)description;
- (id)initWithDevice:(id)arg1;

@end