//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SDAirDropAlertBBManager : NSObject <BBRemoteDataProvider, LSOpenResourceOperationDelegate, SDAirDropAlertManager, SFAirDropTransferDataProviderProtocol>
{
    BBSectionIcon *_sectionIcon;
    SDStatusMonitor *_monitor;
    BBSectionInfo *_sectionInfo;
    BBDataProviderProxy *_dataProviderProxy;
    NSMutableDictionary *_recordIDToTransfers;
    BBDataProviderConnection *_dataProviderConnection;
    NSObject<SDAirDropAlertManagerDelegate> *_delegate;
}

+ (id)sharedAlertManager;
@property(nonatomic) __weak NSObject<SDAirDropAlertManagerDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)lockscreenedRecordID:(id)arg1;
- (id)delockscreenedRecordID:(id)arg1;
- (id)getDataRepresentationOfPNG:(struct CGImage *)arg1 properties:(struct __CFDictionary *)arg2;
- (struct CGImage *)newImageByScalingAndCroppingImage:(struct CGImage *)arg1 withConstraints:(id)arg2;
- (id)bulletinRequestForRecordID:(id)arg1 withType:(int)arg2;
- (void)logReceiverBundleID:(id)arg1 withProxy:(id)arg2 withURL:(id)arg3;
- (void)springboardInitializing;
- (void)openResourceOperation:(id)arg1 didFinishCopyingResource:(id)arg2;
- (void)processVoiceMemos:(id)arg1;
- (void)processPlainTextsInNotes:(id)arg1;
- (void)processManagedConfigurationItems:(id)arg1;
- (void)processPasses:(id)arg1;
- (void)processNonSpecialFiles:(id)arg1;
- (void)processNonSpecialFilesToiCloudDrive:(id)arg1;
- (void)processNonFileURLs:(id)arg1;
- (void)processPhotosItems:(id)arg1;
- (void)processContacts:(id)arg1;
- (void)processCalendarEvents:(id)arg1;
- (void)performAcceptActionForTransferData:(id)arg1;
- (void)performAcceptForRecordID:(id)arg1;
- (void)performAppStoreSearchForRecordID:(id)arg1;
- (void)discardTransferWithRecordID:(id)arg1;
- (void)performCancelForRecordID:(id)arg1;
- (void)performCancelForBulletins:(id)arg1;
- (_Bool)syncsBulletinDismissal;
- (id)sortDescriptors;
- (float)attachmentAspectRatioForRecordID:(id)arg1;
- (id)attachmentPNGDataForRecordID:(id)arg1 sizeConstraints:(id)arg2;
- (id)bulletinsWithRequestParameters:(id)arg1 lastCleared:(id)arg2;
- (id)sectionParameters;
- (id)defaultSectionInfo;
- (id)sectionIdentifier;
- (id)sectionIcon;
- (id)sectionDisplayName;
- (void)handleBulletinActionResponse:(id)arg1;
- (id)clearedInfoForBulletins:(id)arg1 lastClearedInfo:(id)arg2;
- (void)lockStatusChanged:(id)arg1;
- (void)restoreTransferStates;
- (void)addRejectedNotificationForRecordID:(id)arg1;
- (void)addErrorNotificationForRecordID:(id)arg1;
- (void)addCanceledNotificationForRecordID:(id)arg1;
- (void)addAppSelectionNotificationForRecordID:(id)arg1;
- (void)addProgressNotificationForRecordID:(id)arg1;
- (void)addNotificationForBulletinRequest:(id)arg1;
- (void)addNotificationForRecordID:(id)arg1;
- (void)finishedEventForRecordID:(id)arg1 withResults:(id)arg2;
- (void)errorEventForRecordID:(id)arg1 withResults:(id)arg2;
- (void)cancelEventForRecordID:(id)arg1 withResults:(id)arg2;
- (void)progressEventForRecordID:(id)arg1 withResults:(id)arg2;
- (void)askEventForRecordID:(id)arg1 withResults:(id)arg2;
- (void)dataProviderDidLoad;
- (void)transferDataWithRecordID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end