//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SDCompanionStream : NSObject <NSStreamDelegate, NSNetServiceBrowserDelegate, SDStreamHandlerDelegate>
{
    _Bool _initiator;
    _Bool _shouldStop;
    _Bool _clientSent;
    _Bool _clientReceived;
    _Bool _networkBufferSpaceAvailable;
    NSFileHandle *_fileHandle;
    id <SDCompanionStreamDelegate> _delegate;
    NSString *_identifier;
    SDStreamHandler *_streamHandler;
    NSData *_authorData;
    NSNetServiceBrowser *_netServiceBrowser;
    NSInputStream *_clientInputStream;
    NSOutputStream *_clientOutputStream;
    NSObject<OS_dispatch_queue> *_writeQueue;
    NSMutableData *_networkStreamData;
    NSObject<OS_dispatch_queue> *_readQueue;
    NSMutableData *_clientStreamData;
    int _readFromClient;
    int _wroteToClient;
    CDUnknownBlockType _streamsRequestHandler;
}

@property(copy) CDUnknownBlockType streamsRequestHandler; // @synthesize streamsRequestHandler=_streamsRequestHandler;
@property int wroteToClient; // @synthesize wroteToClient=_wroteToClient;
@property int readFromClient; // @synthesize readFromClient=_readFromClient;
@property(retain) NSMutableData *clientStreamData; // @synthesize clientStreamData=_clientStreamData;
@property(retain) NSObject<OS_dispatch_queue> *readQueue; // @synthesize readQueue=_readQueue;
@property(retain) NSMutableData *networkStreamData; // @synthesize networkStreamData=_networkStreamData;
@property(retain) NSObject<OS_dispatch_queue> *writeQueue; // @synthesize writeQueue=_writeQueue;
@property(retain) NSOutputStream *clientOutputStream; // @synthesize clientOutputStream=_clientOutputStream;
@property(retain) NSInputStream *clientInputStream; // @synthesize clientInputStream=_clientInputStream;
@property(retain) NSNetServiceBrowser *netServiceBrowser; // @synthesize netServiceBrowser=_netServiceBrowser;
@property _Bool networkBufferSpaceAvailable; // @synthesize networkBufferSpaceAvailable=_networkBufferSpaceAvailable;
@property _Bool clientReceived; // @synthesize clientReceived=_clientReceived;
@property _Bool clientSent; // @synthesize clientSent=_clientSent;
@property _Bool shouldStop; // @synthesize shouldStop=_shouldStop;
@property _Bool initiator; // @synthesize initiator=_initiator;
@property(retain) NSData *authorData; // @synthesize authorData=_authorData;
@property(retain) SDStreamHandler *streamHandler; // @synthesize streamHandler=_streamHandler;
@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
@property __weak id <SDCompanionStreamDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)logClientReceived;
- (void)logClientSent;
- (void)writeNetworkStream;
- (void)readClientStream;
- (void)writeClientStream;
- (void)handleOpenedStream;
- (void)stream:(id)arg1 handleEvent:(unsigned int)arg2;
- (void)streamHandlerDidClose:(id)arg1 withError:(id)arg2;
- (void)streamHandler:(id)arg1 didReceiveStreamData:(id)arg2;
- (void)streamHandler:(id)arg1 bufferSpaceChanged:(_Bool)arg2;
- (void)handleStreamResponse:(id)arg1;
- (void)handleStreamRequest:(id)arg1;
- (void)streamHandler:(id)arg1 didReceiveMessage:(id)arg2;
- (void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(_Bool)arg3;
- (int)setBufferSize:(int)arg1 socket:(int)arg2;
@property(readonly) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
- (void)notifyStreamRequestWithError:(id)arg1;
- (void)switchToStreaming;
- (void)sendInitialResponse:(_Bool)arg1;
- (void)sendInitialRequest;
- (void)startBrowser;
- (void)getStreamsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)setBundleID:(id)arg1;
- (void)stopIfReady;
- (void)stop;
- (void)start;
- (void)dealloc;
- (id)initWithAuthorData:(id)arg1 streamHandler:(id)arg2;
- (id)initWithStreamHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end