//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SDURLSessionProxyClientService : SDURLSessionProxyService <NSXPCListenerDelegate>
{
    NSMutableDictionary *_sessionManagers;
    unsigned int _directWiFiRetainCount;
}

+ (id)sharedService;
- (void).cxx_destruct;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)_onqueue_handleFailedMessageSend:(id)arg1 ofType:(unsigned short)arg2;
- (void)_onqueue_handleReceivedMessage:(id)arg1 ofType:(unsigned short)arg2 withReply:(CDUnknownBlockType)arg3;
- (void)_onqueue_remoteDeviceStartedUp;
- (void)_onqueue_devicesDisconnected;
- (void)_onqueue_devicesConnected;
- (void)releaseDirectWiFi;
- (void)retainDirectWiFi;
- (void)start;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end