//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SDURLSessionProxyInvalidateSession : PBCodable <NSCopying>
{
    SDURLSessionProxySessionMessage *_session;
    _Bool _shouldCancel;
    struct {
        unsigned int shouldCancel:1;
    } _has;
}

@property(nonatomic) _Bool shouldCancel; // @synthesize shouldCancel=_shouldCancel;
@property(retain, nonatomic) SDURLSessionProxySessionMessage *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned int)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasShouldCancel;
@property(readonly, nonatomic) _Bool hasSession;

@end