//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SDURLSessionProxyDidReceiveChallengeReply : PBCodable <NSCopying>
{
    SDURLSessionProxyCredential *_credential;
    int _disposition;
    SDURLSessionProxyTaskMessage *_task;
    CDStruct_cc6d6311 _has;
}

@property(retain, nonatomic) SDURLSessionProxyCredential *credential; // @synthesize credential=_credential;
@property(retain, nonatomic) SDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned int)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasCredential;
@property(nonatomic) _Bool hasDisposition;
@property(nonatomic) int disposition; // @synthesize disposition=_disposition;
@property(readonly, nonatomic) _Bool hasTask;

@end