//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PUICPageViewAccessibility : __PUICPageViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (_Bool)_accessibilityShouldAttemptScrollToFrameOnParentView;
- (_Bool)accessibilityActivate;
- (id)accessibilityCustomActions;
- (_Bool)_axHandleDelete;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (id)_axPageScrollViewController;

@end