//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface HSSetupCodeView : UIView
{
    unsigned long long _mode;
    unsigned long long _state;
    NSString *_accessoryName;
    CDUnknownBlockType _actionButtonHandler;
    HSSetupCodeGlyphView *_glyphView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
}

@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) HSSetupCodeGlyphView *glyphView; // @synthesize glyphView=_glyphView;
@property(copy, nonatomic) CDUnknownBlockType actionButtonHandler; // @synthesize actionButtonHandler=_actionButtonHandler;
@property(retain, nonatomic) NSString *accessoryName; // @synthesize accessoryName=_accessoryName;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (void)_updateText;
- (void)_updateGlyph;
- (void)_showViews;
- (void)_hideViews;
- (void)_prepareConstraints;
- (id)initWithMode:(unsigned long long)arg1;

@end