//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol HSSetupStepDelegate <NSObject>
- (void)setupStep:(id <HSSetupStep>)arg1 didProvideSetupCode:(NSString *)arg2;
- (void)setupStep:(id <HSSetupStep>)arg1 didFailWithError:(NSError *)arg2;
- (void)setupStepDidFinish:(id <HSSetupStep>)arg1;
- (void)setupStepDidCancel:(id <HSSetupStep>)arg1;
- (void)setupStepDidChange:(id <HSSetupStep>)arg1;
- (HMSetupAccessoryDescription *)accessoryDescriptionForSetupStep:(id <HSSetupStep>)arg1;
@end