//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface HSSetupCodeField : UIView <UITextFieldDelegate>
{
    id <HSSetupCodeFieldDelegate> _delegate;
    NSArray *_items;
    HSSetupCodeFieldItem *_activeItem;
    double _itemSpacing;
    double _sectionSpacing;
    NSArray *_itemSequence;
    UITextField *_hiddenInputField;
}

@property(retain, nonatomic) UITextField *hiddenInputField; // @synthesize hiddenInputField=_hiddenInputField;
@property(retain, nonatomic) NSArray *itemSequence; // @synthesize itemSequence=_itemSequence;
@property(nonatomic) double sectionSpacing; // @synthesize sectionSpacing=_sectionSpacing;
@property(nonatomic) double itemSpacing; // @synthesize itemSpacing=_itemSpacing;
@property(nonatomic) __weak HSSetupCodeFieldItem *activeItem; // @synthesize activeItem=_activeItem;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak id <HSSetupCodeFieldDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_activateLast;
- (void)_activateNext;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)_prepareConstraints;
- (void)fieldTapped:(id)arg1;
- (void)hideKeypad;
- (void)showKeypad;
- (void)clear;
@property(readonly, nonatomic, getter=isComplete) _Bool complete;
@property(readonly, nonatomic) NSString *setupCode;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end