//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WatchConnectivityDaemon : NSObject <NSXPCListenerDelegate, WCDSystemObserver, IDSServiceDelegate, WCDClientDelegate>
{
    NSXPCListener *_xpcPrivateListener;
    WCDPrivateClient *_privateClient;
    WCDFirstUnlockManager *_firstUnlockManager;
    NSXPCListener *_xpcListener;
    IDSService *_idsService;
    IDSService *_insecureIDSService;
    NSMutableDictionary *_communicationIdentifierToClient;
    NSMutableDictionary *_sendIdentifierToHandler;
    NSMutableDictionary *_pendingMessageRequests;
    NSMutableDictionary *_coreLocationAssertions;
    NSMutableDictionary *_companionAppAssertions;
    NSSet *_counterpartClientCommunicationIdentifiers;
    NSString *_idsServiceIdentifier;
    NSString *_idsInsecureServiceIdentifier;
}

+ (id)sharedDaemon;
@property(readonly) NSString *idsInsecureServiceIdentifier; // @synthesize idsInsecureServiceIdentifier=_idsInsecureServiceIdentifier;
@property(readonly) NSString *idsServiceIdentifier; // @synthesize idsServiceIdentifier=_idsServiceIdentifier;
- (void).cxx_destruct;
- (id)createCLInUseTimerForIdentifier:(id)arg1;
- (void)releaseCLInUseAssertionForIdentifier:(id)arg1;
- (void)acquireCLInUseAssertionForIdentifier:(id)arg1;
- (void)persistAppContext:(id)arg1 bundleID:(id)arg2;
- (void)storeComplicationUserInfoTransfer:(id)arg1 bundleID:(id)arg2;
- (id)moveUserInfoToClientInbox:(id)arg1 bundleID:(id)arg2 userInfoIdentifier:(id)arg3;
- (id)moveFileToClientInbox:(id)arg1 bundleID:(id)arg2 fileIdentifier:(id)arg3 userInfoData:(id)arg4 error:(id *)arg5;
- (void)duetIdentifiersForCompanionAppID:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (id)bundleIDForCommunicationID:(id)arg1;
- (id)WCErrorForIDSError:(id)arg1;
- (id)dataFromUUIDString:(id)arg1;
- (void)updateClientWithValues:(id)arg1;
- (void)updateAllClientsWithValues;
- (id)createBackgroundAssertionTimerForIdentifier:(id)arg1;
- (void)acquireBackgroundAssertionForIdentifier:(id)arg1;
- (void)launchCompanionAppID:(id)arg1;
- (void)service:(id)arg1 devicesChanged:(id)arg2;
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;
- (void)service:(id)arg1 account:(id)arg2 incomingResourceAtURL:(id)arg3 metadata:(id)arg4 fromID:(id)arg5 context:(id)arg6;
- (void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5 context:(id)arg6;
- (void)persistUserInfoTransferResult:(id)arg1 bundleID:(id)arg2 identifier:(id)arg3;
- (_Bool)userInfoExistsForIdentifier:(id)arg1 bundleID:(id)arg2;
- (_Bool)notifyIfUserInfoTransferWithCommunicationID:(id)arg1 sendID:(id)arg2 success:(_Bool)arg3 error:(id)arg4;
- (id)complicationUserInfoPathInDataContainer:(id)arg1 pairingID:(id)arg2;
- (void)handleIncomingUserInfoURL:(id)arg1 communicationID:(id)arg2 sendID:(id)arg3;
- (void)transferUserInfo:(id)arg1 withMetadata:(id)arg2 identifier:(id)arg3 clientID:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)handleIncomingUserInfoTransferProto:(id)arg1 sendID:(id)arg2 communicationID:(id)arg3;
- (void)sendComplicationUserInfo:(id)arg1 clientID:(id)arg2 identifier:(id)arg3 errorHandler:(CDUnknownBlockType)arg4;
- (_Bool)notifyIfFileTransferWithCommunicationID:(id)arg1 sendID:(id)arg2 success:(_Bool)arg3 error:(id)arg4;
- (void)persistFileTransferResult:(id)arg1 bundleID:(id)arg2 identifier:(id)arg3;
- (_Bool)fileTransferExistsForIdentifier:(id)arg1 bundleID:(id)arg2;
- (void)handleIncomingFileURL:(id)arg1 communicationID:(id)arg2 sendID:(id)arg3 metadata:(id)arg4;
- (void)cancelSendWithIdentifier:(id)arg1;
- (void)transferFile:(id)arg1 withMetadata:(id)arg2 identifier:(id)arg3 clientID:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)dequeueApplicationContextForClient:(id)arg1 bundleID:(id)arg2;
- (void)updateApplicationContext:(id)arg1 clientID:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)dequeuePendingMessagesForCommunicationID:(id)arg1;
- (void)handleIncomingRequest:(id)arg1 withCommunicationID:(id)arg2;
- (void)sendMessage:(id)arg1 withIdentifier:(id)arg2 isResponse:(_Bool)arg3 clientID:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)sendFirstUnlockAck:(id)arg1;
- (void)sendFirstUnlockRequest:(id)arg1;
- (void)sendFirstUnlockState:(id)arg1;
- (void)dequeuePendingComplicationPings;
- (void)handleComplicationPingForCommunicationIdentifier:(id)arg1;
- (void)addCounterpartClientCommunicationIdentifier:(id)arg1;
- (void)handleDaemonClientsInformation:(id)arg1;
- (void)sendDaemonClientsInformation;
- (void)handleCounterpartDaemonDidStart;
- (void)sendDaemonDidStart;
- (void)systemObserverWatchAppsInstalledChanged;
- (void)systemObserverInstalledApplicationsChanged;
- (void)clientReachabilityDidChange:(id)arg1;
- (void)clientXPCConnectionDidDisconnect:(id)arg1;
- (void)dequeueContentForClient:(id)arg1;
- (_Bool)checkAndHandleiOSExtensionConnection:(id)arg1;
- (_Bool)privateListenerShouldAcceptNewConnection:(id)arg1;
- (_Bool)listenerShouldAcceptNewConnection:(id)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)debugInfoRequested:(id)arg1;
- (void)subscribeToAllNotifications;
- (id)stateDump;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end