//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WCDIndexManager : NSObject
{
    NSMutableDictionary *_indexCache;
    long long _totalCount;
}

+ (id)sharedManager;
@property long long totalCount; // @synthesize totalCount=_totalCount;
@property(retain) NSMutableDictionary *indexCache; // @synthesize indexCache=_indexCache;
- (void).cxx_destruct;
- (void)clearCacheForBundleID:(id)arg1;
- (id)contentIndexWithKey:(id)arg1 containingFolder:(id)arg2;
- (id)userInfoResultsIndexForBundleID:(id)arg1 containingFolder:(id)arg2;
- (id)userInfoIndexForBundleID:(id)arg1 containingFolder:(id)arg2;
- (id)fileResultsIndexForBundleID:(id)arg1 containingFolder:(id)arg2;
- (id)fileIndexForBundleID:(id)arg1 containingFolder:(id)arg2;
- (id)init;

@end