//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface TTRGameCenterExtension : RCTapToRadarExtensionProvider
{
}

- (id)attachmentsWithParams:(id)arg1;
- (id)newRadar;
- (void)disableLogging;
- (void)enableLogging;
- (_Bool)canEnableLogging;
- (_Bool)isLoggingEnabled;
- (id)init;

@end