//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBSimulatorAgentCocoaTouchTool : IBCocoaTouchTool
{
    UIWindow *_windowToRender;
}

- (void).cxx_destruct;
- (void)initializeWithArguments:(id)arg1;
- (void)configureStatusBar;
- (_Bool)shouldExitWhenStandardInputCloses;
- (_Bool)shouldStartEventProcessingRunloop;
- (id)imageBitmapDataByRenderingView:(id)arg1 scaleFactor:(double)arg2 simulatedMetricsContext:(id)arg3;

@end