//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _NanoNavLocationProvider : NSObject <MKLocationProvider>
{
    id <MKLocationProviderDelegate> _delegate;
    _Bool _updating;
    GEOCompanionRouteStatus *_lastRouteStatus;
    NSBundle *_effectiveBundle;
    NSString *_effectiveBundleIdentifier;
    double _desiredAccuracy;
    _Bool _locationServicesPreferencesDialogEnabled;
    double _distanceFilter;
    _Bool _matchInfoEnabled;
    CDUnknownBlockType _authorizationRequestBlock;
}

@property(copy, nonatomic) CDUnknownBlockType authorizationRequestBlock; // @synthesize authorizationRequestBlock=_authorizationRequestBlock;
@property(nonatomic) _Bool matchInfoEnabled; // @synthesize matchInfoEnabled=_matchInfoEnabled;
@property(nonatomic) double distanceFilter; // @synthesize distanceFilter=_distanceFilter;
@property(nonatomic, getter=isLocationServicesPreferencesDialogEnabled) _Bool locationServicesPreferencesDialogEnabled; // @synthesize locationServicesPreferencesDialogEnabled=_locationServicesPreferencesDialogEnabled;
@property(nonatomic) double desiredAccuracy; // @synthesize desiredAccuracy=_desiredAccuracy;
@property(copy, nonatomic) NSString *effectiveBundleIdentifier; // @synthesize effectiveBundleIdentifier=_effectiveBundleIdentifier;
@property(retain, nonatomic) NSBundle *effectiveBundle; // @synthesize effectiveBundle=_effectiveBundle;
@property(nonatomic) __weak id <MKLocationProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dismissHeadingCalibrationDisplay;
@property(readonly, nonatomic) _Bool isTracePlayer;
@property(readonly, nonatomic) _Bool isSimulation;
@property(readonly, nonatomic) _Bool usesCLMapCorrection;
@property(nonatomic) int activityType;
@property(readonly, nonatomic) int authorizationStatus;
@property(readonly, nonatomic) double expectedGpsUpdateInterval;
@property(nonatomic) int headingOrientation;
- (void)stopUpdatingVehicleHeading;
- (void)startUpdatingVehicleHeading;
- (void)stopUpdatingVehicleSpeed;
- (void)startUpdatingVehicleSpeed;
- (void)stopUpdatingHeading;
- (void)startUpdatingHeading;
- (void)requestWhenInUseAuthorizationWithPrompt;
- (void)requestWhenInUseAuthorization;
@property(readonly, nonatomic) double timeScale;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocation;
- (void)_updateLocation;
- (void)updateWithRouteStatus:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end