//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _TempToken : NSObject <GEOServerFormatToken>
{
    int _type;
    NSString *_token;
    unsigned int _value1;
    unsigned int _value2;
}

@property(nonatomic) unsigned int value2; // @synthesize value2=_value2;
@property(nonatomic) unsigned int value1; // @synthesize value1=_value1;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end