//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol NanoNavViewControllerDelegate <NSObject>
- (void)nanoNavViewController:(NanoNavViewController *)arg1 showMapForStepIndex:(unsigned int)arg2 animated:(_Bool)arg3;
- (void)nanoNavViewController:(NanoNavViewController *)arg1 displayingStepIndex:(unsigned int)arg2 animated:(_Bool)arg3;
- (void)nanoNavViewController:(NanoNavViewController *)arg1 peekingWithPercentage:(float)arg2 upcomingPage:(int)arg3 direction:(int)arg4;
@end