//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoNavInstructionContentView : UIView
{
    UILabel *_instruction;
    UILabel *_secondaryInstruction;
    UILabel *_tertiaryInstruction;
    UILabel *_departureInstruction;
    UIView *_lastView;
    MapsAutoLayoutContext *_layoutContext;
    MapsAutoLayoutContext *_transitLayoutContext;
}

- (void).cxx_destruct;
- (void)configureWithInstructionText:(id)arg1 stepIsCurrent:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)viewForLastBaselineLayout;
- (id)viewForFirstBaselineLayout;

@end