//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoNavTransitionController : PUICNavigationDefaultTransition
{
    _Bool _isPush;
    _Bool _isMapToMap;
    _Bool _hidesChromeMapCorners;
    NanoAppChromeViewController *_chrome;
}

+ (double)transitionDuration;
@property(nonatomic) _Bool hidesChromeMapCorners; // @synthesize hidesChromeMapCorners=_hidesChromeMapCorners;
@property(retain, nonatomic) NanoAppChromeViewController *chrome; // @synthesize chrome=_chrome;
@property(nonatomic) _Bool isMapToMap; // @synthesize isMapToMap=_isMapToMap;
@property(nonatomic) _Bool isPush; // @synthesize isPush=_isPush;
- (void).cxx_destruct;
- (void)_doPopTransition:(id)arg1;
- (void)_doPushTransition:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

@end