//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoNavMapViewController : PassThroughViewController <UIScrollViewDelegate, NanoNavTransitioningViewController>
{
    NanoNavMapRepresentationView *_mapRepresentation;
    NanoNavBarView *_footerView;
    NanoNavInstructionFooterView *_footerInstruction;
    _Bool _appIsActive;
    struct CGPoint _previousScrollPosition;
    GEOCompanionRouteDetails *_routeDetails;
    GEOCompanionRouteStatus *_routeStatus;
    NSDate *_stoppedLookingWhen;
    unsigned int _footerStepIndex;
    _Bool _mapRenderingPaused;
    struct CGAffineTransform _previousMapTransform;
    _Bool _hasFlashedIndicators;
    _Bool _ephemeralDataHidden;
    MKMapView *_mapView;
    UIScrollView *_scrollView;
}

@property(nonatomic) _Bool ephemeralDataHidden; // @synthesize ephemeralDataHidden=_ephemeralDataHidden;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
- (void).cxx_destruct;
- (void)_resumeMapRendering;
- (void)_pauseMapRendering;
- (void)_showSnapshot;
- (void)__showSnapshot;
- (void)_handleNavTrackingButtonPressed:(id)arg1;
- (void)setEphemeralDataHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)handleNavigationRouteStatusChanged;
- (void)handleNavigationRouteDetailsAndStatusChanged;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)refreshRouteStatus:(id)arg1;
- (void)_showStepInFooter:(unsigned int)arg1 animated:(_Bool)arg2;
- (void)showStepInFooter:(unsigned int)arg1 animated:(_Bool)arg2;
- (void)showCurrentNavStepAnimated:(_Bool)arg1;
- (_Bool)mapModeIsVisible;
- (_Bool)mapIsVisible;
- (void)performOrderOutAnimationWithDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)performOrderInAnimationWithDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <NanoNavMapViewControllerDelegate><PassThroughViewControllerDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end