//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoPillTableViewDetailCell : PUICTableViewCell
{
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    MapsAutoLayoutContext *_context;
    UIFont *_titleFont;
    UIFont *_detailFont;
}

+ (_Bool)requiresConstraintBasedLayout;
+ (_Bool)usesConstraintBasedLayout;
- (void).cxx_destruct;
@property(copy, nonatomic) NSAttributedString *attributedDetailText;
@property(copy, nonatomic) NSString *detailText;
@property(copy, nonatomic) NSAttributedString *attributedTitleText;
@property(copy, nonatomic) NSString *titleText;
- (void)textSizeChanged;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end