//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoNavModeController : NSObject <NanoNavViewControllerDelegate, PassThroughViewControllerDelegate, MKMapViewDelegatePrivate, NMGizmoXPC, NanoNavChromeModeController>
{
    NanoNavViewController *_viewController;
    NanoNavCameraController *_cameraController;
    _Bool _startedCameraController;
    int _peekDirection;
    unsigned int _peekingAtStep;
    int _previousDisplayRate;
    int _nonInteractiveMainLoopRate;
    int _previousMarkerMode;
    _NanoNavLocationProvider *_locationProvider;
    NanoStatusBarPercentDrivenAnimation *_currentStatusbarAnimation;
    NanoAppChromeViewController *_chromeViewController;
}

@property(nonatomic) ChromeViewController *chromeViewController;
- (void).cxx_destruct;
- (void)_debug_fetchStateSnapshot:(CDUnknownBlockType)arg1;
- (void)historyUpdated;
- (void)pinsUpdated;
- (void)bookmarksUpdated;
- (void)mapViewDidStopUserInteraction:(id)arg1;
- (void)mapViewDidStartUserInteraction:(id)arg1;
- (id)mapViewCurrentRouteMatch:(id)arg1;
- (void)nanoNavViewController:(id)arg1 showMapForStepIndex:(unsigned int)arg2 animated:(_Bool)arg3;
- (void)nanoNavViewController:(id)arg1 peekingWithPercentage:(float)arg2 upcomingPage:(int)arg3 direction:(int)arg4;
- (void)nanoNavViewController:(id)arg1 displayingStepIndex:(unsigned int)arg2 animated:(_Bool)arg3;
- (id)passThroughView;
- (void)_stopTracking;
- (void)_startTrackingAnimated:(_Bool)arg1;
- (void)statusBarWasTapped;
- (void)showEphemeralData;
- (void)hideEphemeralData;
- (void)refreshTitle;
- (void)_refreshRouteStatus;
- (_Bool)respectBackButtonPopping;
- (void)handleNavigationStepChanged;
- (void)handleNavigationRouteStatusChanged;
- (void)handleNavigationRouteDetailsAndStatusChanged;
- (id)actionGroup;
- (id)transitionControllerForPopToMode:(id)arg1;
- (id)transitionControllerForPushFromMode:(id)arg1;
- (id)viewController;
- (_Bool)shouldAllowActivityContinuation;
- (void)modeWillAppear:(_Bool)arg1;
- (_Bool)allowsEdgeSwipePop;
- (_Bool)showsMapView;
- (void)resignCurrentModeAnimated:(_Bool)arg1 toMode:(id)arg2;
- (void)becomeCurrentModeWithViews:(id)arg1 animated:(_Bool)arg2 state:(id)arg3 fromMode:(id)arg4;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end