//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoNavPreviewFooterView : UIView
{
    PUICSideBySideButtonsView *_buttons;
    int _style;
}

@property(nonatomic) int style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)_updateForStyle;
@property(copy, nonatomic) CDUnknownBlockType rightAction;
@property(copy, nonatomic) CDUnknownBlockType leftAction;
@property(nonatomic, getter=isPrimaryButtonEnabled) _Bool primaryButtonEnabled;
- (_Bool)primaryButtonEnabled;
- (id)initWithFrame:(struct CGRect)arg1;

@end