//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoPinsController : NSObject <NMGizmoXPC>
{
    NSXPCConnection *_connection;
    NSArray *_pins;
    MSPDroppedPin *_droppedPin;
    NSLock *_droppedPinLock;
    NSHashTable *_pinObservers;
    NSLock *_observersLock;
}

+ (id)sharedController;
@property(retain, nonatomic) MSPDroppedPin *droppedPin; // @synthesize droppedPin=_droppedPin;
- (void).cxx_destruct;
- (void)_debug_fetchStateSnapshot:(CDUnknownBlockType)arg1;
- (void)historyUpdated;
- (void)pinsUpdated;
- (void)bookmarksUpdated;
- (void)removePinsObserver:(id)arg1;
- (void)addPinsObserver:(id)arg1;
- (void)_updateDroppedPin;
- (void)_updatePins;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end