//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XRSamplerInspectionCursor : XRStrategyInspectionCursor
{
    struct vector<unsigned int, std::__1::allocator<unsigned int>> _arrangedIdentifiers;
    struct __wrap_iter<unsigned int *> {
        unsigned int *__i;
    } _position;
    XRSamplerRun *_run;
}

+ (id)cursorSatisfyingNavigator:(id)arg1 run:(id)arg2;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_moveBackward;
- (void)_moveForward;
- (BOOL)_canMoveBackward;
- (BOOL)_canMoveForward;
- (BOOL)_populateInspectionDataElements:(id)arg1;

@end