//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SPInterfaceItem_UIViewAccessibility : __SPInterfaceItem_UIViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_accessibilityGetCommonGroupViewAncestorWithView:(id)arg1;
- (long long)_accessibilityWatchKitInterfaceItemCompareGeometryWithView:(id)arg1 sharedGroupItemAncestor:(id)arg2;
- (long long)accessibilityCompareGeometry:(id)arg1;
- (void)setAccessibilityElements:(id)arg1;

@end