//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface HKHeartbeatGlanceViewController : UIViewController <HKHeartbeatGlanceViewDelegate, HKHeartbeatGlanceHeartRateMeasurerDelegate, CUISGlanceServiceViewController>
{
    HKHeartbeatGlanceHeartRateMeasurer *_heartRateMeasurer;
    CSLSBacklightAssertion *_backlightAssertion;
    double _currentReading;
    NSDate *_currentReadingDate;
    double _previousReading;
    NSDate *_previousReadingDate;
    unsigned int _errorCount;
    _Bool _deviceIsCharging;
    _Bool _viewIsVisible;
    NSString *_launchBundleID;
    NSURL *_launchURL;
    NSDictionary *_glanceContext;
    unsigned int _state;
}

@property(nonatomic) unsigned int state; // @synthesize state=_state;
@property(retain, nonatomic) NSDictionary *glanceContext; // @synthesize glanceContext=_glanceContext;
@property(retain, nonatomic) NSURL *launchURL; // @synthesize launchURL=_launchURL;
@property(retain, nonatomic) NSString *launchBundleID; // @synthesize launchBundleID=_launchBundleID;
- (void).cxx_destruct;
- (void)heartRateMeasurerDidFailToMeasure:(id)arg1;
- (void)heartRateMeasurer:(id)arg1 didReceiveHistoricalMeasurement:(double)arg2 withDate:(id)arg3;
- (void)heartRateMeasurer:(id)arg1 didReceiveCurrentMeasurement:(double)arg2 onDate:(id)arg3;
- (id)glanceView:(id)arg1 explanatoryTextForState:(unsigned int)arg2;
- (void)glanceViewDidGetTapped:(id)arg1;
- (void)_releaseBacklightAssertion;
- (void)_takeBacklightAssertion;
- (void)_transitionToStaleReading;
- (void)_updateCurrentReadingViewAnimated:(_Bool)arg1;
- (void)_updatePreviousReadingViewAnimated:(_Bool)arg1;
- (void)_pushNewReading:(double)arg1 withDate:(id)arg2;
- (id)_heartRateMeasurer;
- (void)_transitionToMeasuring;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)glanceDidSettle;
- (void)_deactivateHeartRateMeasuring;
- (void)_transitionToCorrectInitialState;
- (void)_batteryStateChanged:(id)arg1;
- (void)_handlePrivacyPreferencesChanged;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <CUISGlanceServiceViewControllerDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *duetIdentifier;
@property(readonly, copy, nonatomic) NSString *glanceTitle;
@property(readonly, nonatomic) NSUserActivity *glanceUserActivity;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) NSString *prelaunchBundleID;
@property(readonly) Class superclass;

@end