//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NETPolicyManager : NSObject
{
    NSMutableArray *_changeHandlers;
}

+ (id)sharedPolicyManager;
@property(retain) NSMutableArray *changeHandlers; // @synthesize changeHandlers=_changeHandlers;
- (void).cxx_destruct;
- (void)unregisterChangeHandler:(id)arg1;
- (void)registerChangeHandler:(id)arg1;
- (id)init;

@end