//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XRCoreProfileTapPlugInToken : NSObject
{
    NSArray *_triggerConfigs;
    BOOL _configError;
    unsigned long long _kdebugTriggerIndex;
    long long _runNumber;
    XRTrace *_trace;
    DTTap *_tap;
    DTKPerfTapConfig *_runningConfig;
}

@property(retain, nonatomic) DTKPerfTapConfig *runningConfig; // @synthesize runningConfig=_runningConfig;
@property(retain, nonatomic) DTTap *tap; // @synthesize tap=_tap;
@property(nonatomic) __weak XRTrace *trace; // @synthesize trace=_trace;
@property(nonatomic) long long runNumber; // @synthesize runNumber=_runNumber;
@property(readonly, nonatomic) unsigned long long kdebugTriggerIndex; // @synthesize kdebugTriggerIndex=_kdebugTriggerIndex;
@property(readonly, nonatomic) BOOL configError; // @synthesize configError=_configError;
- (void).cxx_destruct;
- (BOOL)processRecord:(struct _CPRecord *)arg1 triggerIndex:(unsigned long long)arg2 timeInfo:(const struct _XRDeviceTimeInfo *)arg3;
- (void)resetCursors;
- (void)setupCursorsWithBindings:(const struct XRAnalysisCoreTableBindings *)arg1;
- (id)createDTCoreProfileTapConfig;
- (void)configureWithTableIDs:(id)arg1 runNumber:(long long)arg2 trace:(id)arg3 populateColumns:(BOOL)arg4;
- (id)_mergeKDebugTriggers:(id)arg1 timeTriggers:(id)arg2 pmiTriggers:(id)arg3;
- (void)_mergeTriggers:(id)arg1 intoResult:(id)arg2;
@property(readonly, nonatomic) unsigned long long triggerCount;

@end