//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XRKEventsInstrumentDecorator : DTTimelineDecorator
{
    XRSystemTraceRun *_run;
    unsigned long long _graphIndex;
    unsigned long long _drawingIntervalWidth;
}

+ (id)newFilteredThreadSetForRun:(id)arg1;
- (void).cxx_destruct;
- (id)decorateInspectionRanges:(id)arg1;
- (id)decorateContainer:(struct DTTimelineDecorationContainer *)arg1;
- (void)setDefaultsForPlane:(id)arg1;
- (id)initWithRun:(id)arg1 graphIndex:(unsigned long long)arg2 intervalWidth:(unsigned long long)arg3;
- (id)init;

@end