//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface AXBackBoardServerInstance : NSObject
{
    AXIPCServer *_server;
    id <AXBackBoardServerInstanceDelegate> _delegate;
    NSMutableArray *_eventListeners;
    NSMutableArray *_zoomListeners;
    struct CGRect _initialZoomFocusRect;
    NSMutableArray *_eventTapClients;
}

+ (id)backBoardServerInstanceIfExists;
+ (id)backBoardServerInstance;
@property(nonatomic) id <AXBackBoardServerInstanceDelegate> delegate; // @synthesize delegate=_delegate;
- (id)_setAXPreferenceAsMobile:(id)arg1;
- (id)_handleGuidedAccessIgnoredRegions:(id)arg1;
- (id)_handleIsGuidedAccessSelfLockedToRequestingApp:(id)arg1;
- (void)_handleSetGuidedAccessEnabledByRequestingApp:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_handleIsGuidedAccessActive:(id)arg1;
- (void)_handleGuidedAccessAutomationCommand:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_handleIsGuidedAccessInWorkspace:(id)arg1;
- (id)_handleGetGuidedAccessAvailability:(id)arg1;
- (id)_handleSetInPreBoardMode:(id)arg1;
- (id)_handleInPreBoardMode:(id)arg1;
- (_Bool)_inPreBoardMode;
- (id)_gaxBackboard;
- (id)_handleGetZoomInitialFocusRect:(id)arg1;
- (id)_handleSetZoomInitialFocusRect:(id)arg1;
- (id)_handleSetSwitchControlRendersDeviceUnusable:(id)arg1;
- (id)_handleLockScreenDimTimerEnabled:(id)arg1;
- (id)_handleInvertColorsChange:(id)arg1;
- (id)_handleRegisterSiriViewServicePID:(id)arg1;
- (id)_handleRegisterAccessibilityUIPID:(id)arg1;
- (id)_handleAXUIServerPID:(id)arg1;
- (id)_handleRegisterAssistiveTouchPID:(id)arg1;
- (id)_handleWakeUpIfNecessary:(id)arg1;
- (id)_handleZoomAttributesListenerRegistration:(id)arg1;
- (void)zoomAttributesChanged:(id)arg1;
- (id)_handleZoomAttributesChanged:(id)arg1;
- (id)_handleEventListenerRegistration:(id)arg1;
- (id)_handleEnableEventTap:(id)arg1;
- (id)_handleItemChooserVisible:(id)arg1;
- (id)_handleUserEventOccurred:(id)arg1;
- (id)_handlePostEvent:(id)arg1;
- (id)_handleConvertFrameFromContextIdToContextId:(id)arg1;
- (id)_handleConvertFrameFromContextId:(id)arg1;
- (id)_handleConvertFrameToContextId:(id)arg1;
- (id)_handleContextHostingIdForContextId:(id)arg1;
- (id)_handleContextIdForPosition:(id)arg1;
- (id)_handleZoomAdjustment:(id)arg1;
- (id)_handleRegisterZoomConflict:(id)arg1;
- (void)eventListener:(id)arg1;
- (void)dealloc;
- (id)_initServer;
- (void)_initializeHandlers;

@end