//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKActionDocumentViewController : SKDocumentViewController <DVTReplacementViewDelegate, NSSplitViewDelegate, SKActionPreviewViewControllerDelegate, SKActionAssignControllerDelegate, GTFActionEditorDelegate>
{
    DVTObservingToken *_actionEditorSelectedActionsKVOToken;
    DVTObservingToken *_actionEditorFilterStringKVOToken;
    DVTObservingToken *_previewSceneTargetKVOToken;
    DVTObservingToken *_previewSceneNavigableObjectKVOToken;
    DVTObservingToken *_previewSceneSelectedObjectsKVOToken;
    DVTReplacementView *_actionEditorReplacementView;
    GTFActionEditor *_actionEditorViewController;
    DVTReplacementView *_previewSceneReplacementView;
    SKActionPreviewViewController *_previewSceneViewController;
    SKEditView *_spriteKitEditView;
    SKActionDocumentSplitView *_splitView;
    SKActionDocumentBorderedView *_sceneEditorGroupView;
    SKActionDocumentScopeBarView *_toolbarView;
    NSPopUpButton *_sceneSelector;
    NSView *_sceneSelectorView;
    DVTGradientImageButton *_actionEditorToggleButton;
    NSView *_playbackSpeedView;
    DVTStepperTextField *_playbackSpeedField;
    DVTGradientImageButton *_previewPauseResumeButton;
    DVTGradientImageButton *_previewPlayStopButton;
    NSMutableDictionary *_actionFilter;
    SKDocument *_previewDocument;
    NSArrayController *_sceneURLs;
    BOOL _isInitialLayout;
    BOOL _ignoreSelectionChanges;
    long long _previewState;
}

+ (id)toolTipForHideActionEditorViewButton;
+ (id)toolTipForShowActionEditorButton;
- (void).cxx_destruct;
- (void)replacementView:(id)arg1 willCloseViewController:(id)arg2;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)previewPauseResumeButtonPressed:(id)arg1;
- (void)previewPlayStopButtonPressed:(id)arg1;
- (void)updateActionPreview;
- (BOOL)actionEditor:(id)arg1 shouldSupportPastedActions:(id)arg2;
- (id)undoManagerForActionEditor:(id)arg1;
- (void)refreshObjectLibrary;
@property(readonly, nonatomic) GTFActionLibrary *actionLibrary;
- (id)allTargets;
- (id)nodesFilteredByString:(id)arg1;
- (void)updateActionEditorAllTargetsFilter:(id)arg1;
- (void)updateActionEditorFilterString:(id)arg1;
- (void)updateActionEditorFilteredActions:(id)arg1 toTargets:(id)arg2 sync:(BOOL)arg3;
- (void)selectDocumentLocations:(id)arg1;
- (void)splitViewItemDidExpandOrCollapseBecauseUserDraggedDivider:(id)arg1;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (double)splitView:(id)arg1 constrainSplitPosition:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (id)actionDocumentURLForPreviewController:(id)arg1;
- (void)takeFocus;
- (void)playbackSpeedUpdated:(id)arg1;
- (id)loadAndRetainSKDocumentAtURL:(id)arg1;
- (void)setPreviewDocumentOnPreviewSceneViewController;
- (void)loadPreviewFromURL:(id)arg1;
- (void)previewSceneSelected:(id)arg1;
- (void)updateSceneSelectorToURL:(id)arg1;
- (void)refreshPreviewButtonsForState;
- (void)updateToolTipsForShowEditorViewButtons;
- (void)resizeActionEditorToInitialHeight;
- (void)updateLayoutPropertiesAfterUserDraggedDivider;
- (void)updateLayoutAfterButtonPress:(id)arg1;
- (void)populateSceneSelectorIgnoringURL:(id)arg1;
- (void)populateSceneSelector;
- (void)setupToolbarViewLayout;
- (void)updateLastActionEditorState;
- (void)primitiveInvalidate;
- (void)viewWillUninstall;
- (void)registerForActionLibraryNotifications;
- (void)viewDidInstall;
- (void)viewDidLoad;
- (void)viewDidLayout;
@property(readonly, nonatomic) SKEditingActionTarget *actionEditingTarget;
- (id)skView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end