//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKActionAssignTableView : DVTTableView
{
    NSArrayController *_contentController;
}

@property(retain, nonatomic) NSArrayController *contentController; // @synthesize contentController=_contentController;
- (void).cxx_destruct;
- (struct CGSize)_adjustFrameSizeToFitSuperview:(struct CGSize)arg1;

@end