//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKActionAssignAsset : NSObject
{
    id <NSCopying> _targetID;
    NSString *_targetName;
    NSImage *_targetThumbnail;
}

@property(retain, nonatomic) NSImage *targetThumbnail; // @synthesize targetThumbnail=_targetThumbnail;
@property(copy, nonatomic) NSString *targetName; // @synthesize targetName=_targetName;
@property(retain, nonatomic) id <NSCopying> targetID; // @synthesize targetID=_targetID;
- (void).cxx_destruct;

@end