//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKActionEmptyPreviewViewController : SKActionPreviewViewController
{
    DVTBorderedView *_backgroundView;
    NSTextField *_messageLabel;
}

@property(retain) NSTextField *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain) DVTBorderedView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end