//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKNode (InspectorAdditions) <IDEKeyDrivenNavigableItemRepresentedObject, GTFActionLibraryTarget>
+ (id)keyPathsForValuesAffectingNav_children;
+ (id)keyPathsForValuesAffectingNavigableItem_name;
+ (id)keyPathsForValuesAffectingGtf_name;
+ (id)keyPathsForValuesAffectingGtf_thumbnailImage;
+ (id)keyPathsForValuesAffectingInspectorName;
@property(readonly, nonatomic) GTFActionTimelineModel *nav_action;
@property(readonly, nonatomic) NSArray *nav_children;
@property(retain, nonatomic) NSString *skCustomModuleName;
@property(retain, nonatomic) NSString *skCustomClassName;
- (id)ideModelObjectTypeIdentifier;
@property(readonly) NSString *navigableItem_name;
@property(readonly, nonatomic) NSIndexPath *indexPath;
@property(readonly, nonatomic) NSString *gtf_name;
@property(readonly, nonatomic) GTFActionLibraryTargetThumbnail *gtf_thumbnailImage;
- (void)setGtf_uid:(id)arg1;
@property(readonly, nonatomic) id <NSCopying> gtf_uid;
- (void)removeUID;
@property(retain, nonatomic) NSValue *uid;
@property(readonly, nonatomic) SKNode *greatestReferenceNodeAncestor;
@property(readonly, nonatomic) BOOL isReferenced;
@property(nonatomic) BOOL isLocked;
@property(nonatomic) double zRotationDeg;
@property(retain, nonatomic) SKNode *parentRef;
@property(readonly, nonatomic) __weak SKNode *selfRef;
@property(retain, nonatomic) NSString *inspectorName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;
@end