//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NPHCallConfigurationChangeSource : NSObject
{
    int _type;
    id _payload;
}

@property(retain, nonatomic) id payload; // @synthesize payload=_payload;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)description;
- (id)initWithUTF8String:(const char *)arg1;
- (id)initWithString:(id)arg1;
- (id)initWithNotification:(id)arg1;
- (id)initWithType:(int)arg1 payload:(id)arg2;
- (id)init;

@end