//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NPHInCallSoundController : NSObject
{
    NPHCallConfiguration *_callConfiguration;
    TUCallSoundPlayer *_player;
}

@property(retain, nonatomic) TUCallSoundPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) NPHCallConfiguration *callConfiguration; // @synthesize callConfiguration=_callConfiguration;
- (void).cxx_destruct;
- (_Bool)_shouldIgnoreCall:(id)arg1;
- (void)_stopSoundsWithReason:(id)arg1;
- (void)_attemptToPlaySoundType:(int)arg1 forCall:(id)arg2 withReason:(id)arg3;
- (void)_processStatusForCall:(id)arg1;
- (void)_shouldIgnoreCallDidChange:(id)arg1;
- (void)_callStatusDidChange:(id)arg1;
- (void)_callConnected:(id)arg1;
- (void)_callNeedsManualInCallSoundsDidChange:(id)arg1;
- (void)dealloc;
- (id)init;

@end