//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NPHInCallView : UIView
{
    NSMutableArray *_noDynamicButtonsConstraints;
    NSMutableArray *_showRevealDynamicButtonConstraints;
    UILabel *_headerNameLabel;
    _Bool _showingFullAudioRouteButton;
    _Bool _callMuted;
    id <NPHInCallViewDelegate> _delegate;
    UIView *_headerView;
    NPHInCallInfoSingleView *_infoSingleView;
    NPHInCallInfoDoubleView *_infoDoubleView;
    NPHCallConfiguration *_callConfiguration;
    unsigned int _alertDisplay;
    UIView *_infoContainerView;
    NPHRoundButton *_leftButton;
    NPHRoundButton *_rightButton;
    UIButton *_dynamicRevealButton;
    UIButton *_dynamicButton;
    NPHInCallInfoView *_currentInfoView;
}

@property(retain, nonatomic) NPHInCallInfoView *currentInfoView; // @synthesize currentInfoView=_currentInfoView;
@property(retain, nonatomic) UIButton *dynamicButton; // @synthesize dynamicButton=_dynamicButton;
@property(retain, nonatomic) UIButton *dynamicRevealButton; // @synthesize dynamicRevealButton=_dynamicRevealButton;
@property(retain, nonatomic) NPHRoundButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) NPHRoundButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) UIView *infoContainerView; // @synthesize infoContainerView=_infoContainerView;
@property(readonly, nonatomic) unsigned int alertDisplay; // @synthesize alertDisplay=_alertDisplay;
@property(readonly, nonatomic) NPHCallConfiguration *callConfiguration; // @synthesize callConfiguration=_callConfiguration;
@property(nonatomic, getter=isCallMuted) _Bool callMuted; // @synthesize callMuted=_callMuted;
@property(retain, nonatomic) NPHInCallInfoDoubleView *infoDoubleView; // @synthesize infoDoubleView=_infoDoubleView;
@property(retain, nonatomic) NPHInCallInfoSingleView *infoSingleView; // @synthesize infoSingleView=_infoSingleView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak id <NPHInCallViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)_isAnyCallEnding;
- (void)_inCallTouchUp:(id)arg1;
- (void)_dynamicRevealTouchUp:(id)arg1;
- (id)_createDynamicRevealButton;
- (void)_dynamicTouchUp:(id)arg1;
- (id)_createDynamicButton;
- (id)_createInCallButton;
- (id)_createHeaderView;
- (void)_updateRightButton;
- (void)_updateLeftButton;
- (void)_updateInfoViewAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showFullAudioRouteButton:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_updateAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setCallConfiguration:(id)arg1 andDisplay:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)handleCrownButton;
- (void)layoutSubviews;
- (_Bool)canShowDynamicButton;
- (void)updateConstraints;
- (void)_createConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end