//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NPHNanoRespondWithTextStore : NSObject
{
    NPSDomainAccessor *_domainAccessor;
}

- (void).cxx_destruct;
- (id)cannedRepliesForLanguage:(id)arg1;
- (id)customReplies;
- (id)defaultRepliesForLanguage:(id)arg1;
- (unsigned int)count;
- (id)init;

@end