//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NEKDeletionWrapper : NSObject <SYObject>
{
    int _type;
    NSString *_identifier;
    NSString *_calendarIdentifier;
}

+ (_Bool)supportsSecureCoding;
+ (id)deletionWrapperForRecordID:(struct CalRecordID *)arg1 eventStore:(id)arg2;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)syncId;
@property(readonly, copy) NSString *description;
- (int)type;
- (id)calendarIdentifier;
- (id)identifier;
- (id)initWithIdentifier:(id)arg1 calendarIdentifier:(id)arg2 type:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end