//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NEKPBCalendarWrapper : PBCodable <NSCopying>
{
    NEKPBCalendarAttributes *_attributes;
    NSString *_calendarIdentifier;
    NSString *_oldCalendarIdentifier;
    NEKPBStoreID *_storeIdentifier;
    _Bool _isDefaultEventCalendar;
    _Bool _isDefaultTaskCalendar;
    struct {
        unsigned int isDefaultEventCalendar:1;
        unsigned int isDefaultTaskCalendar:1;
    } _has;
}

@property(retain, nonatomic) NSString *oldCalendarIdentifier; // @synthesize oldCalendarIdentifier=_oldCalendarIdentifier;
@property(nonatomic) _Bool isDefaultEventCalendar; // @synthesize isDefaultEventCalendar=_isDefaultEventCalendar;
@property(nonatomic) _Bool isDefaultTaskCalendar; // @synthesize isDefaultTaskCalendar=_isDefaultTaskCalendar;
@property(retain, nonatomic) NEKPBCalendarAttributes *attributes; // @synthesize attributes=_attributes;
@property(retain, nonatomic) NSString *calendarIdentifier; // @synthesize calendarIdentifier=_calendarIdentifier;
@property(retain, nonatomic) NEKPBStoreID *storeIdentifier; // @synthesize storeIdentifier=_storeIdentifier;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasOldCalendarIdentifier;
@property(nonatomic) _Bool hasIsDefaultEventCalendar;
@property(nonatomic) _Bool hasIsDefaultTaskCalendar;
@property(readonly, nonatomic) _Bool hasAttributes;
@property(readonly, nonatomic) _Bool hasCalendarIdentifier;
@property(readonly, nonatomic) _Bool hasStoreIdentifier;

@end