//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NEKStoreAttributes : NSObject <NSSecureCoding>
{
    _Bool _isEnabled;
    _Bool _isFacebook;
    _Bool _usesSelfAttendee;
    _Bool _supportsSharedCalendars;
    _Bool _allowsTasks;
    _Bool _allowsEvents;
    _Bool _allowsCalendarAddDeleteModify;
    _Bool _onlyCreatorCanModify;
    _Bool _snoozeAlarmRequiresDetach;
    _Bool _supportsAlarmAcknowledgedDate;
    int _type;
    NSString *_name;
    NSNumber *_defaultAlarmOffset;
    NSString *_constraintsDescriptionPath;
    NSString *_externalID;
    NSString *_externalModificationTag;
    NSString *_creatorBundleID;
    NSString *_creatorCodeSigningIdentity;
    NSString *_accountPersistentID;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) _Bool supportsAlarmAcknowledgedDate; // @synthesize supportsAlarmAcknowledgedDate=_supportsAlarmAcknowledgedDate;
@property(nonatomic) _Bool snoozeAlarmRequiresDetach; // @synthesize snoozeAlarmRequiresDetach=_snoozeAlarmRequiresDetach;
@property(nonatomic) _Bool onlyCreatorCanModify; // @synthesize onlyCreatorCanModify=_onlyCreatorCanModify;
@property(nonatomic) _Bool allowsCalendarAddDeleteModify; // @synthesize allowsCalendarAddDeleteModify=_allowsCalendarAddDeleteModify;
@property(nonatomic) _Bool allowsEvents; // @synthesize allowsEvents=_allowsEvents;
@property(nonatomic) _Bool allowsTasks; // @synthesize allowsTasks=_allowsTasks;
@property(nonatomic) _Bool supportsSharedCalendars; // @synthesize supportsSharedCalendars=_supportsSharedCalendars;
@property(copy, nonatomic) NSString *accountPersistentID; // @synthesize accountPersistentID=_accountPersistentID;
@property(copy, nonatomic) NSString *creatorCodeSigningIdentity; // @synthesize creatorCodeSigningIdentity=_creatorCodeSigningIdentity;
@property(copy, nonatomic) NSString *creatorBundleID; // @synthesize creatorBundleID=_creatorBundleID;
@property(copy, nonatomic) NSString *externalModificationTag; // @synthesize externalModificationTag=_externalModificationTag;
@property(copy, nonatomic) NSString *externalID; // @synthesize externalID=_externalID;
@property(copy, nonatomic) NSString *constraintsDescriptionPath; // @synthesize constraintsDescriptionPath=_constraintsDescriptionPath;
@property(nonatomic) _Bool usesSelfAttendee; // @synthesize usesSelfAttendee=_usesSelfAttendee;
@property(nonatomic) _Bool isFacebook; // @synthesize isFacebook=_isFacebook;
@property(nonatomic) _Bool isEnabled; // @synthesize isEnabled=_isEnabled;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSNumber *defaultAlarmOffset; // @synthesize defaultAlarmOffset=_defaultAlarmOffset;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithStore:(void *)arg1;

@end