//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface TPSTipCollectionViewCellAccessibility : __TPSTipCollectionViewCellAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_axRelatedAppName;
- (void)setLike:(_Bool)arg1 animate:(_Bool)arg2;
- (void)userUnlike:(id)arg1;
- (void)userLiked:(id)arg1;
- (void)setTip:(id)arg1 withCellAppearance:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)avplayer;
- (void)_accessibilityLoadAccessibilityInformation;
- (id)_accessibilityScannerGroupElements;
- (_Bool)_accessibilityProvidesScannerGroupElements;

@end