//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol NLNanoHealthServerDelegate <NSObject>
- (void)unregisterServerForAlerts:(NLNanoHealthServer *)arg1;
- (void)registerServerForAlerts:(NLNanoHealthServer *)arg1;
@end