//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NLSedentaryTimer : NSObject <HDHealthDaemonReadyObserver, HDDatabaseProtectedDataObserver, NLSedentaryTimerStateEngineDelegate, NLBridgeSettingsObserver>
{
    NSObject<OS_dispatch_queue> *_queue;
    id <HDHealthDaemon> _healthDaemon;
    CMSedentaryTimer *_sedentaryTimer;
    id <HDHealthDatabase> _healthDatabase;
    NLGizmoWristEventsManager *_wristManager;
    NLSedentaryTimerStateEngine *_sedentaryTimerStateEngine;
    NLBridgeSettings *_bridgeSettings;
    int _retryInCaseOfErrorCounter;
    id <NLSedentaryTimerAlertDelegate> _delegate;
}

@property(nonatomic) __weak id <NLSedentaryTimerAlertDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_showSedentaryAlertOfType:(int)arg1 withTimeoutDate:(id)arg2;
- (_Bool)_isSedentaryTimerNotificationEnabled;
- (void)dealloc;
- (id)_startDateForSedentaryTimer;
- (int)_numberOfActiveHoursToday;
- (int)_numberOfAwakeHoursToday;
- (id)_dateFromKey:(id)arg1;
- (id)_keyFromDate:(id)arg1;
- (void)_saveSedentaryHourDataIfRequired:(id)arg1;
- (_Bool)_dataExistsForHourStart:(id)arg1;
- (void)_queue_processCachedSedentaryHourSamples;
- (void)_cacheSedentaryHourStartDate:(id)arg1 state:(int)arg2;
- (void)_saveActiveHourDetailsIntoDBWithStartDate:(id)arg1;
- (void)_saveMissedHourDetailsIntoDBWithStartDate:(id)arg1;
- (void)_fireCongratulatoryNotificationIfRequiredForHourWithStartDate:(id)arg1;
- (id)_timeoutDateForSedentaryTimerAlertOfType:(int)arg1 withHourStartDate:(id)arg2;
- (void)_queue_fireReminderNotificationIfRequiredOfType:(int)arg1 forHourWithStartDate:(id)arg2;
- (_Bool)_shouldFireCongratulatoryAlertForHourWithStartDate:(id)arg1;
- (_Bool)_shouldFireReminderForHourWithStartDate:(id)arg1;
- (id)_roundedDateForDate:(id)arg1;
- (void)_queue_processDataObjectsInArray:(id)arg1;
- (void)_queue_registerTimerHandler;
- (void)_timerStarted;
- (void)_queue_startTimerHandlerWithError:(id)arg1;
- (void)_queue_startTimer;
- (void)_queue_startSedentaryTimerIfRequired;
- (void)_timerStopped;
- (void)_queue_stopTimerHandlerWithError:(id)arg1;
- (void)_queue_stopSedentaryTimer;
- (void)_queue_stopSedentaryTimerIfRequired;
- (id)_timer;
- (void)_registerDaemonLaunchForSedentaryTimerFiredNotification;
- (void)_checkIfSedentaryTimerNeedsStop;
- (void)_checkIfSedentaryTimerNeedsStart;
- (_Bool)_canStartSedentaryTimer;
- (_Bool)daemonDidReceiveNotification:(const char *)arg1;
- (void)stopSedentaryTimer;
- (void)startSedentaryTimerIfPossible;
- (int)_sedentaryTimerState;
- (int)timerState;
- (void)daemonReady:(id)arg1;
- (void)database:(id)arg1 protectedDataDidBecomeAvailable:(_Bool)arg2;
- (void)privacySettingsDidChange:(id)arg1;
- (id)initWithHealthDaemon:(id)arg1 bridgeSettings:(id)arg2 wristManager:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end