//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NLWorkoutStateManager : NSObject
{
    NSObject<OS_dispatch_queue> *_observerQueue;
    NSHashTable *_observers;
}

- (void).cxx_destruct;
- (void)_notifyWorkoutStateObservers:(_Bool)arg1;
- (void)removeWorkoutStateObserver:(id)arg1;
- (void)addWorkoutStateObserver:(id)arg1;
- (id)initWithHealthDaemon:(id)arg1;

@end