//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface ABSABSyncManager : ABSSyncManager
{
    ABSABShadow *_shadow;
    ABSABReality *_reality;
}

- (void).cxx_destruct;
- (void)deleteShadow;
- (void)deleteReality;
- (void)remove:(id)arg1;
- (void)modify:(id)arg1;
- (void)add:(id)arg1;
- (void)_bindLinks:(id)arg1 person:(void *)arg2;
- (id)reality;
- (id)shadow;
- (Class)currentObjectClass;
- (Class)oldObjectClass;
- (id)currentDb;
- (id)oldDb;

@end