//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface ABSSyncManager : NSObject
{
    id <ABSSyncStateMutable> _oldDb;
    id <ABSSyncStateDiffable> _currentDb;
    Class _oldObjectClass;
    Class _currentObjectClass;
}

@property(readonly, nonatomic) Class currentObjectClass; // @synthesize currentObjectClass=_currentObjectClass;
@property(readonly, nonatomic) Class oldObjectClass; // @synthesize oldObjectClass=_oldObjectClass;
@property(readonly, nonatomic) id <ABSSyncStateDiffable> currentDb; // @synthesize currentDb=_currentDb;
@property(readonly, nonatomic) id <ABSSyncStateMutable> oldDb; // @synthesize oldDb=_oldDb;
- (void).cxx_destruct;
- (void)deleteReality;
- (void)deleteShadow;
- (void)_processChangeset:(id)arg1 into:(id)arg2;
- (id)generateDiffs;

@end