//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface ABSyncInterface : NSObject <PSYSyncCoordinatorDelegate, SYStoreDelegate>
{
    _Bool _running;
    _Bool _runningMode;
    _Bool _inFullSync;
    _Bool _externalChangesGoingOn;
    _Bool _needsDeltaSync;
    SYStore *_syncStore;
    ABSSyncController *_syncController;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_source> *_syncTimer;
    NSObject<OS_dispatch_source> *_unlockTimer;
    long long _objectCount;
    PSYSyncCoordinator *_syncCoordinator;
    double _fullSyncStartTime;
}

+ (_Bool)checkIfSyncWasAbandonedFromAnotherProcess;
+ (void)clearSyncInProgressMarker;
+ (void)saveSyncInProgressMarker;
+ (id)uniqueProcessIdentifierForSync;
+ (id)syncInProgressFilePath;
+ (id)sharedInstance;
@property(nonatomic) double fullSyncStartTime; // @synthesize fullSyncStartTime=_fullSyncStartTime;
@property(retain, nonatomic) PSYSyncCoordinator *syncCoordinator; // @synthesize syncCoordinator=_syncCoordinator;
@property(nonatomic) _Bool needsDeltaSync; // @synthesize needsDeltaSync=_needsDeltaSync;
@property(nonatomic) _Bool externalChangesGoingOn; // @synthesize externalChangesGoingOn=_externalChangesGoingOn;
@property(nonatomic) _Bool inFullSync; // @synthesize inFullSync=_inFullSync;
@property(nonatomic) long long objectCount; // @synthesize objectCount=_objectCount;
@property(nonatomic) _Bool runningMode; // @synthesize runningMode=_runningMode;
@property(nonatomic) _Bool running; // @synthesize running=_running;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *unlockTimer; // @synthesize unlockTimer=_unlockTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *syncTimer; // @synthesize syncTimer=_syncTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) ABSSyncController *syncController; // @synthesize syncController=_syncController;
@property(retain, nonatomic) SYStore *syncStore; // @synthesize syncStore=_syncStore;
- (void).cxx_destruct;
- (void)requestFullSync:(id)arg1;
- (void)_requestFullSync:(id)arg1;
- (_Bool)oldDatabaseDelete;
- (_Bool)oldDatabaseExists;
- (void)updateSyncState;
- (CDUnknownBlockType)beginSyncingAllObjectsForStore:(id)arg1;
- (void)syncStore:(id)arg1 encounteredError:(id)arg2 context:(id)arg3;
- (void)syncStoreDidCompleteFullSync:(id)arg1;
- (void)syncStoreEnqueuedAllFullSyncMessages:(id)arg1 context:(id)arg2;
- (void)syncStoreAllObjectsDeleted:(id)arg1;
- (void)syncStore:(id)arg1 objectDeleted:(id)arg2;
- (void)syncStore:(id)arg1 objectUpdated:(id)arg2;
- (void)syncStore:(id)arg1 objectAdded:(id)arg2;
- (void)syncStoreDidUpdate:(id)arg1;
- (void)syncStoreWillUpdate:(id)arg1;
- (void)syncStoreWillUpdate:(id)arg1 objectCount:(unsigned long long)arg2;
- (void)_checkForPairingChange;
- (void)syncChanges;
- (void)startUnlockTimer:(double)arg1;
- (void)cancelUnlockTimer;
- (void)startSyncTimer;
- (void)cancelSyncTimer;
- (void)registerForAddressBookDarwinNotifications;
- (void)shutdown;
- (void)runInMode:(_Bool)arg1;
- (void)syncCoordinatorDidReceiveStartSyncCommand:(id)arg1;
- (void)_setupStatsLogging;
- (void)_initSyncStore;
- (void)_blockUntilUnlock;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end