//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NLBulletinClientSubFactory : CUISBulletinClientFactory <NLBulletinClientFactoryViewControllerDelegate>
{
    id <NLBulletinClientFactoryDelegate> _clientFactorydelegate;
}

@property(nonatomic) __weak id <NLBulletinClientFactoryDelegate> clientFactorydelegate; // @synthesize clientFactorydelegate=_clientFactorydelegate;
- (void).cxx_destruct;
- (void)clientViewControllerDidSelectMuteCoachingForToday:(id)arg1;
- (void)clientViewControllerDidSelectDismiss:(id)arg1 shouldAnimateActionMenu:(_Bool)arg2;
- (void)clientViewControllerDidDisappear:(id)arg1;
- (void)clientViewControllerDidAppear:(id)arg1;
- (id)coachingEventSampleForPresentationDate:(id)arg1 dismissDate:(id)arg2 dismissReason:(int)arg3;
@property(readonly, copy, nonatomic) NSString *aggdKeyName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end