//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NLWeeklyGoalBulletinView : UIView
{
    NLWeeklyGoalDigestView *_digestView;
    NLWeeklyGoalStatsView *_statsView;
    NLWeeklyGoalSettingView *_settingView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) HKQuantity *weeklyGoal;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)_populateSubviewsWithWeeklySummaryInfo:(id)arg1 recommendedGoal:(double)arg2 style:(unsigned int)arg3;
- (void)layoutSubviews;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 weeklySummaryInfo:(id)arg2 recommendedGoal:(double)arg3 style:(unsigned int)arg4;

@end