//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface ETCanvasViewControllerAccessibility : __ETCanvasViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_accessibilitySetCanvasAccessibilityInfo;
- (void)_startMissedMessagePlaybackLoop;
- (void)setPlayingMissedMessages:(_Bool)arg1;
- (void)colorPickerViewDidDismiss:(id)arg1;
- (void)colorPickerViewDidPresent:(id)arg1;
- (void)_playMessage:(id)arg1 identifier:(id)arg2;
- (void)viewDidLoad;
- (void)_accessibilityLoadAccessibilityInformation;

@end