//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDEAssetTagChangeListener <NSObject>
- (void)taggedAssetItem:(id <IDETaggedAssetItem>)arg1 didUpdateProperty:(NSString *)arg2 inAssetInfoProvider:(id <IDEAssetTagInfoProvider>)arg3;
@end