//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface Xcode3TagAssetRow : Xcode3AssetRow
{
    NSString *_tag;
    NSArray *_children;
    NSMutableSet *_allChildren;
    unsigned long long _size;
    BOOL _childrenNeedSorting;
    BOOL _editable;
    NSPredicate *_displayFilterPredicate;
}

- (id)displayFilterPredicate;
- (id)tag;
- (void).cxx_destruct;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)writableTypesForPasteboard:(id)arg1;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (unsigned long long)size;
- (id)displayName;
- (void)addChild:(id)arg1;
- (id)childrenAtIndexes:(id)arg1;
- (id)childAtIndex:(unsigned long long)arg1;
- (BOOL)canEdit;
- (BOOL)canHaveChildren;
- (id)children;
- (void)_sortIfNeeded;
- (void)setDisplayFilterPredicate:(id)arg1;
- (id)initWithTag:(id)arg1 editable:(BOOL)arg2;

@end