//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PBAAppDelegate : UIResponder <UIApplicationDelegate>
{
    UIWindow *_window;
    PBARootViewController *_rootViewController;
    PBAOrientationController *_orientationController;
}

@property(retain, nonatomic) PBAOrientationController *orientationController; // @synthesize orientationController=_orientationController;
@property(retain, nonatomic) PBARootViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end