//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSRColumnDataTemplateCellLayoutValues : NSObject <NSRCachedLayoutValues>
{
    float _height;
    NSArray *_subtitleLabelFitSizes;
    float _titleFirstLineBaseline;
    float _subtitleFirstLineBaseline;
    int _indexOfSubtitleEllipsis;
    struct CGSize _titleLabelFitSize;
    struct CGSize _scaledImageSize;
}

@property(nonatomic) int indexOfSubtitleEllipsis; // @synthesize indexOfSubtitleEllipsis=_indexOfSubtitleEllipsis;
@property(nonatomic) float subtitleFirstLineBaseline; // @synthesize subtitleFirstLineBaseline=_subtitleFirstLineBaseline;
@property(nonatomic) float titleFirstLineBaseline; // @synthesize titleFirstLineBaseline=_titleFirstLineBaseline;
@property(nonatomic) struct CGSize scaledImageSize; // @synthesize scaledImageSize=_scaledImageSize;
@property(retain, nonatomic) NSArray *subtitleLabelFitSizes; // @synthesize subtitleLabelFitSizes=_subtitleLabelFitSizes;
@property(nonatomic) struct CGSize titleLabelFitSize; // @synthesize titleLabelFitSize=_titleLabelFitSize;
@property(nonatomic) float height; // @synthesize height=_height;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end