//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSRImageGridTemplate : NSRTemplate
{
    NSRImageResource *_firstImage;
    NSRImageResource *_secondImage;
}

@property(retain, nonatomic) NSRImageResource *secondImage; // @synthesize secondImage=_secondImage;
@property(retain, nonatomic) NSRImageResource *firstImage; // @synthesize firstImage=_firstImage;
- (void).cxx_destruct;

@end