//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSRSideBySideButtonTemplateCell : NSRTemplateCell <NSRActionableCell>
{
    PUICSideBySideButtonsView *_buttonView;
    id <NSRTemplateCellActionDelegate> actionDelegate;
}

+ (id)calculateLayoutValuesForSuggestedSize:(struct CGSize)arg1;
@property(retain, nonatomic) id <NSRTemplateCellActionDelegate> actionDelegate; // @synthesize actionDelegate;
- (void).cxx_destruct;
- (id)_layoutValues;
- (void)setTemplateObject:(id)arg1;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end