//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSRSubheaderTemplate : NSRTemplate
{
    NSRDecoratedString *_leftDecoratedText;
    NSRDecoratedString *_rightDecoratedText;
    NSRRating *_rating;
}

@property(retain, nonatomic) NSRRating *rating; // @synthesize rating=_rating;
@property(retain, nonatomic) NSRDecoratedString *rightDecoratedText; // @synthesize rightDecoratedText=_rightDecoratedText;
@property(retain, nonatomic) NSRDecoratedString *leftDecoratedText; // @synthesize leftDecoratedText=_leftDecoratedText;
- (void).cxx_destruct;

@end