//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSRTableDataTemplateCellLayoutValues : NSRTableRowTemplateCellLayoutValues
{
    float _height;
    NSArray *_scoreLabelFrames;
    float _titleBaselineOriginY;
    float _scoreBaselineOriginY;
    struct CGRect _imageFrame;
    struct CGRect _titleFrame;
}

@property(nonatomic) float scoreBaselineOriginY; // @synthesize scoreBaselineOriginY=_scoreBaselineOriginY;
@property(nonatomic) float titleBaselineOriginY; // @synthesize titleBaselineOriginY=_titleBaselineOriginY;
@property(retain, nonatomic) NSArray *scoreLabelFrames; // @synthesize scoreLabelFrames=_scoreLabelFrames;
@property(nonatomic) struct CGRect titleFrame; // @synthesize titleFrame=_titleFrame;
@property(nonatomic) struct CGRect imageFrame; // @synthesize imageFrame=_imageFrame;
- (void)setHeight:(float)arg1;
- (float)height;
- (void).cxx_destruct;

@end