//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSVSViewControllerCell : PUICTableViewCell <NSRDynamicType, NSRTranscriptCell>
{
    NSUUID *_identifier;
    UIViewController *_viewController;
    float _topPadding;
}

+ (float)desiredBaselineForInteractiveCellBelowLayoutType:(int)arg1;
+ (float)desiredBaselineForCellBelowLayoutType:(int)arg1;
+ (int)defaultLayoutType;
+ (int)defaultContentAlignmentType;
@property(nonatomic) float topPadding; // @synthesize topPadding=_topPadding;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) NSUUID *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)updateLayoutAttributesForPreferredContentSizeCategory;
- (void)layoutSubviews;
- (void)_parentViewInCell;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end