//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSVSDialogView : UITextView <NSRDynamicType>
{
    _Bool _hasFinalizedRecognition;
    double _lastPartialTimestamp;
    NSArray *_pendingPartialResult;
    _Bool _needsEnsureSelectionVisible;
    int _dialogType;
}

+ (id)_textColorForDialogType:(int)arg1;
+ (id)attributedStringAttributesForDialogType:(int)arg1;
+ (int)dialogFontTextStyle;
+ (float)heightWithDialog:(id)arg1 suggestedSize:(struct CGSize)arg2;
@property(nonatomic) _Bool needsEnsureSelectionVisible; // @synthesize needsEnsureSelectionVisible=_needsEnsureSelectionVisible;
@property(nonatomic) int dialogType; // @synthesize dialogType=_dialogType;
- (void).cxx_destruct;
- (void)updateLayoutAttributesForPreferredContentSizeCategory;
- (void)_ensureSelectionVisibleIfNeeded;
- (void)layoutSubviews;
- (void)_resetDataDetectorsResults;
- (void)_startDataDetectors;
- (void)_tryComittingPendingResult;
- (void)_didRecognizeSpeechStrings:(id)arg1;
- (void)_didRecognizeSpeechTokens:(id)arg1;
- (void)_didFinishSpeechRecognition;
- (void)reset;
- (_Bool)hasFinalizedRecognition;
- (void)setText:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end