//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSVSDialog : NSObject
{
    _Bool _listenAfterPresenting;
    NSString *_displayString;
    int _dialogType;
}

+ (id)_parsedServerUtteranceForUtterance:(id)arg1;
+ (id)_firstInterpretationForRecognition:(id)arg1;
+ (id)errorDialogWithDisplayString:(id)arg1;
+ (id)_serverDialogWithAceObject:(id)arg1 dialogType:(int)arg2;
+ (id)interstitialDialogWithAceObject:(id)arg1;
+ (id)serverDialogWithAceObject:(id)arg1;
+ (id)userDialogWithAceObject:(id)arg1;
@property(readonly, nonatomic) _Bool listenAfterPresenting; // @synthesize listenAfterPresenting=_listenAfterPresenting;
@property(readonly, nonatomic) int dialogType; // @synthesize dialogType=_dialogType;
@property(readonly, nonatomic) NSString *displayString; // @synthesize displayString=_displayString;
- (void).cxx_destruct;
- (id)description;
- (id)initWithDisplayString:(id)arg1 dialogType:(int)arg2 listenAfterPresenting:(_Bool)arg3;

@end