//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol NSVSSiriViewDelegate <NSObject>
- (_Bool)backlightIsOn:(NSVSSiriView *)arg1;
- (void)flamesViewTapped:(NSVSSiriView *)arg1;
- (void)dimOverlayTapped:(NSVSSiriView *)arg1;
@end