//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NanoStopwatchHybridViewControllerAccessibility : __NanoStopwatchHybridViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_accessibilityUpdateLabelsOnUITimeLabelForKey:(id)arg1 withFormatString:(id)arg2 duration:(double)arg3;
- (void)_accessibilityUpateAxisLabels;
- (void)_accessibilityUpdateElapsedLabels;
- (void)updateAverageTimeLabel;
- (void)viewDidLoad;
- (void)setElapsedTime:(double)arg1;
- (void)_accessibilityLoadAccessibilityInformation;

@end