//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBICWatchComplicationSet : IBICSlottedAssetCollection
{
}

+ (id)contentReferenceTypeName;
+ (id)defaultInstanceForIdioms:(id)arg1;
+ (id)classNameComponents;
+ (id)catalogItemFileExtension;
+ (Class)requiredChildrenClass;
- (Class)expectedClassForSlot:(id)arg1;
- (void)populateIssues:(id)arg1 forUnconflictedChild:(id)arg2 inSlot:(id)arg3 context:(id)arg4;
- (id)overridingUnqualifiedRuntimeNameForChild:(id)arg1;
- (id)conflictFreeSlotForChild:(id)arg1;
- (id)defaultUnqualifiedRuntimeName;
- (id)runtimeNamespaceQualifier;
- (Class)manifestArchivistSlotClassForChildren:(id)arg1;
- (id)slotForChild:(id)arg1;
- (id)overridingNameEditingModeForChild:(id)arg1;
- (id)typeIcon;

@end