//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBPepperPlatform : IBCocoaTouchPlatform
{
}

+ (BOOL)supportsSceneUpdates;
- (id)systemNamesToGenericColorsMapResourceNameForTargetRuntime:(id)arg1;
- (id)systemDocumentDependency;
- (id)defaultTargetRuntimeForArchiving;
- (id)defaultTargetRuntime;
- (id)buildSystemPlatformIdentifier;
- (void)populateGlobalEntryPointIndicators:(id)arg1 withTargetRuntime:(id)arg2;
- (BOOL)shouldPreflightDuringUnarchiving;
- (BOOL)wantsDesignatedEntryPointInRefactoredStoryboard;
- (Class)externalPrimarySceneObjectClass;
- (id)instantiateDocumentLinker;
- (id)buildSystemPlatformName;
- (id)operatingSystemName;
- (id)identifier;

@end