//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBSPInterfaceDate : IBSPInterfaceLabel <IBDocumentArchiving, NSCoding>
{
    unsigned long long _dateStyle;
    unsigned long long _timeStyle;
    NSDate *_previewedDate;
    BOOL _usesCustomFormat;
    NSString *_format;
}

+ (id)defaultPreviewedDate;
+ (id)keyPathsForValuesAffectingIbInspectedUsesCustomFormat;
+ (void)ibPopulateConfigurableAttributeKeyPaths:(id)arg1;
+ (void)ibPopulatePropertyListAttributeKeyPaths:(id)arg1;
+ (id)ibInstantiateViewForDraggingFromLibraryWithRole:(long long)arg1 targetRuntime:(id)arg2 documentClass:(Class)arg3 assetIdentifier:(id)arg4;
+ (id)ibInstantiateForRole:(long long)arg1 withTargetRuntime:(id)arg2 documentClass:(Class)arg3 assetIdentifier:(id)arg4;
@property(copy, nonatomic) NSDate *previewedDate; // @synthesize previewedDate=_previewedDate;
@property(nonatomic) unsigned long long timeStyle; // @synthesize timeStyle=_timeStyle;
@property(nonatomic) unsigned long long dateStyle; // @synthesize dateStyle=_dateStyle;
@property(copy, nonatomic) NSString *format; // @synthesize format=_format;
@property(nonatomic) BOOL usesCustomFormat; // @synthesize usesCustomFormat=_usesCustomFormat;
- (void).cxx_destruct;
- (id)initWithTargetRuntime:(id)arg1;
- (id)ibUnarchiveValueForAttribute:(id)arg1 inConfiguration:(id)arg2 withDocumentUnarchiver:(id)arg3;
- (void)ibArchiveEvaluatedValue:(id)arg1 forAttribute:(id)arg2 inConfiguration:(id)arg3 withDocumentArchiver:(id)arg4;
- (void)unarchiveWithDocumentUnarchiver:(id)arg1;
- (void)archiveWithDocumentArchiver:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) BOOL ibInspectedUsesCustomFormat;
- (void)awakeAfterUsingDocumentUnarchiver:(id)arg1;
- (id)ibEditableTitleKeyPath;
- (id)ibDefaultPlistValueForKeyPath:(id)arg1 plistKey:(id)arg2;
- (id)ibTransformPlistValue:(id)arg1 forKeyPath:(id)arg2 plistKey:(id)arg3 document:(id)arg4 configuration:(id)arg5 reason:(long long)arg6;
- (void)ibEnumeratePlistKeysForKeyPath:(id)arg1 document:(id)arg2 reason:(long long)arg3 withBlock:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end