//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBSPInterfaceImageView : IBSPInterfaceView <NSCoding, IBDocumentArchiving, IBSPAnimatableInterfaceObject>
{
    int _contentMode;
    NSColor *_tintColor;
    NSString *_image;
    BOOL _hasAnimation;
    BOOL _initiallyAnimated;
    double _animationDuration;
    BOOL _duration;
}

+ (BOOL)ibWantsRenderedDraggedLibraryView;
+ (id)ibViewPropertyListType;
@property(nonatomic) BOOL duration; // @synthesize duration=_duration;
@property(nonatomic) int contentMode; // @synthesize contentMode=_contentMode;
@property(copy, nonatomic) NSColor *tintColor; // @synthesize tintColor=_tintColor;
@property(copy, nonatomic) NSString *image; // @synthesize image=_image;
@property double animationDuration; // @synthesize animationDuration=_animationDuration;
@property BOOL initiallyAnimated; // @synthesize initiallyAnimated=_initiallyAnimated;
@property BOOL hasAnimation; // @synthesize hasAnimation=_hasAnimation;
- (void).cxx_destruct;
- (unsigned long long)archivingDefaultAccessibilityTraits;
- (id)initWithTargetRuntime:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)ibUnarchiveValueForAttribute:(id)arg1 inConfiguration:(id)arg2 withDocumentUnarchiver:(id)arg3;
- (void)ibArchiveEvaluatedValue:(id)arg1 forAttribute:(id)arg2 inConfiguration:(id)arg3 withDocumentArchiver:(id)arg4;
- (void)unarchiveWithDocumentUnarchiver:(id)arg1;
- (void)archiveWithDocumentArchiver:(id)arg1;
- (void)awakeAfterUsingDocumentUnarchiver:(id)arg1;
- (id)ibDefaultPlistValueForKeyPath:(id)arg1 plistKey:(id)arg2;
- (id)ibTransformPlistValue:(id)arg1 forKeyPath:(id)arg2 plistKey:(id)arg3 document:(id)arg4 configuration:(id)arg5 reason:(long long)arg6;
- (BOOL)ibWantsPlaceholderImageInCanvas;
- (id)ibQualifyingInfoForDefaultLabel;
- (id)ibTypeNameForDefaultLabel;
- (id)ibRuntimeClassName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end