//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SCNBox (SKEUndoRedoSupport)
+ (id)keyPathsForValuesAffectingchamferSegmentCount_edit;
+ (id)keyPathsForValuesAffectinglengthSegmentCount_edit;
+ (id)keyPathsForValuesAffectingheightSegmentCount_edit;
+ (id)keyPathsForValuesAffectingwidthSegmentCount_edit;
+ (id)keyPathsForValuesAffectingchamferRadius_edit;
- (void)setchamferSegmentCount_edit:(long long)arg1;
- (long long)chamferSegmentCount_edit;
- (void)setlengthSegmentCount_edit:(long long)arg1;
- (long long)lengthSegmentCount_edit;
- (void)setheightSegmentCount_edit:(long long)arg1;
- (long long)heightSegmentCount_edit;
- (void)setwidthSegmentCount_edit:(long long)arg1;
- (long long)widthSegmentCount_edit;
- (void)setchamferRadius_edit:(double)arg1;
- (double)chamferRadius_edit;
@end