//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SCNGeometry (SKEUndoRedoSupport)
+ (id)keyPathsForValuesAffectingshaderModifiers_edit;
+ (id)keyPathsForValuesAffectingske_primitiveSegmentCount3_edit;
+ (id)keyPathsForValuesAffectingske_primitiveSegmentCount2_edit;
+ (id)keyPathsForValuesAffectingske_primitiveSize3_edit;
+ (id)keyPathsForValuesAffectingske_primitiveSize2_edit;
+ (id)keyPathsForValuesAffectingsubdivisionLevel_edit;
+ (id)keyPathsForValuesAffectingname_edit;
- (void)setshaderModifiers_edit:(id)arg1;
- (id)shaderModifiers_edit;
- (void)setske_primitiveSegmentCount3_edit:(struct SCNVector3)arg1;
- (struct SCNVector3)ske_primitiveSegmentCount3_edit;
- (void)setske_primitiveSegmentCount2_edit:(struct CGSize)arg1;
- (struct CGSize)ske_primitiveSegmentCount2_edit;
- (void)setske_primitiveSize3_edit:(struct SCNVector3)arg1;
- (struct SCNVector3)ske_primitiveSize3_edit;
- (void)setske_primitiveSize2_edit:(struct CGSize)arg1;
- (struct CGSize)ske_primitiveSize2_edit;
- (void)setsubdivisionLevel_edit:(unsigned long long)arg1;
- (unsigned long long)subdivisionLevel_edit;
- (void)setname_edit:(id)arg1;
- (id)name_edit;
@end