//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SCNTorus (SKEUndoRedoSupport)
+ (id)keyPathsForValuesAffectingpipeSegmentCount_edit;
+ (id)keyPathsForValuesAffectingringSegmentCount_edit;
+ (id)keyPathsForValuesAffectingpipeRadius_edit;
+ (id)keyPathsForValuesAffectingringRadius_edit;
- (void)setpipeSegmentCount_edit:(long long)arg1;
- (long long)pipeSegmentCount_edit;
- (void)setringSegmentCount_edit:(long long)arg1;
- (long long)ringSegmentCount_edit;
- (void)setpipeRadius_edit:(double)arg1;
- (double)pipeRadius_edit;
- (void)setringRadius_edit:(double)arg1;
- (double)ringRadius_edit;
@end