//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKEGradientImagePopUpButton : DVTGradientImagePopUpButton <SKEUIFactoryAppearanceControl>
{
    NSImage *_skeImage;
    NSImage *_skeInvertedImage;
    unsigned long long _skeAppearance;
}

- (void).cxx_destruct;
- (void)updateAccordingToAppearance;
@property(nonatomic) unsigned long long ske_appearance;
- (void)setTitle:(id)arg1;
- (void)setImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end