//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKEParticleSystemEditor : IDEEditor <DVTReplacementViewDelegate, SKEContentsPickerPopUpButtonDataSource, SCNSceneRendererDelegate>
{
    SCNView *_sceneView;
    DVTScopeBarView *_scopeBarView;
    DVTBorderedView *_bottomBarView;
    DVTGradientImageButton *_restartButton;
    DVTGradientImageButton *_playStopButton;
    DVTGradientImageButton *_cameraButton;
    DVTGradientImageButton *_backgroundColorButton;
    NSArray *_currentSelectedItems;
    SCNScene *_scene;
    SCNNode *_cameraNode;
    SCNNode *_particleSystemNode;
    DVTDelayedInvocation *_restartInvocation;
    double _watchDogTime;
}

- (void).cxx_destruct;
- (id)suggestedImagesForContentsPicker:(id)arg1;
- (void)selectDocumentLocations:(id)arg1;
- (void)updateBottomBarColorScheme;
- (void)configureScopeBarView;
- (void)backgroundColorDidChange:(id)arg1;
- (void)changeBackgroundColorAction:(id)arg1;
- (void)resetCameraAction:(id)arg1;
- (void)particleSystemIsPlayingDidChange:(id)arg1;
- (void)restartParticleSystemAction:(id)arg1;
- (void)setCurrentSelectedItems:(id)arg1;
- (id)currentSelectedItems;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)scheduleRestartInvocationIfNeeded;
- (void)restartParticleSystem;
- (void)setParticleSystemIsPlaying:(BOOL)arg1;
- (BOOL)particleSystemIsPlaying;
- (void)renderer:(id)arg1 didRenderScene:(id)arg2 atTime:(double)arg3;
- (void)renderer:(id)arg1 willRenderScene:(id)arg2 atTime:(double)arg3;
- (void)resetPOVUsingSystemParticleProperties;
- (void)buildScene;
- (id)particleSystem;
- (BOOL)canBecomeMainViewController;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)primitiveInvalidate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) SKEParticleSystemDocument *document; // @dynamic document;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end