//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKESceneEditorArea : IDEEditor <DVTReplacementViewDelegate, DVTSplitViewDelegate>
{
    DVTSplitView *_splitView;
    DVTReplacementView *_primaryReplacementView;
    DVTReplacementView *_secondaryReplacementView;
    SKESceneEditor *_sceneEditor;
    SKESceneSubEditor *_subEditor;
    DVTGradientImageButton *_showSecondaryEditorButton;
    NSArray *_currentSelectedItems;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
- (void).cxx_destruct;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)setStateToken:(id)arg1;
- (id)actionableMembersAndState:(unsigned long long *)arg1;
- (id)shadableMembersAndState:(unsigned long long *)arg1;
- (id)shadableMembersIncludingSubShadableMembersAndState:(unsigned long long *)arg1;
- (id)currentSelectedItemsWithFilter:(CDUnknownBlockType)arg1 state:(unsigned long long *)arg2;
- (id)subEditor;
- (void)setSubEditor:(id)arg1;
- (id)sceneEditor;
- (void)setSceneEditor:(id)arg1;
- (void)toggleShowsSubEditor;
- (void)setShowsSubEditor:(BOOL)arg1;
- (void)setShowsSubEditor:(BOOL)arg1 isRestoringState:(BOOL)arg2;
- (BOOL)showsSubEditor;
- (void)refreshViewSwitchingControlsStates;
- (void)userDidPressSecondaryEditorViewSwitchingControl:(id)arg1;
- (id)toolTipForHideSecondaryEditorButton;
- (id)toolTipForShowSecondaryEditorButton;
- (id)splitView:(id)arg1 additionalEffectiveRectsOfDividerAtIndex:(long long)arg2;
- (void)splitViewItemDidExpandOrCollapseBecauseUserDraggedDivider:(id)arg1;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (void)replacementView:(id)arg1 willCloseViewController:(id)arg2;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)replacementView:(id)arg1 willInstallViewController:(id)arg2;
@property(readonly) NSArray *selectedNodes;
- (id)currentSelectedDocumentLocations;
@property(copy) NSArray *currentSelectedItems;
- (void)selectDocumentLocations:(id)arg1;
- (void)primitiveInvalidate;
- (void)takeFocus;
- (BOOL)canBecomeMainViewController;
- (void)viewDidInstall;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) SKESceneDocument *document; // @dynamic document;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end