//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CKTranscriptBalloonCellAccessibility : __CKTranscriptBalloonCellAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)updateCheckmarkImage;
- (id)_accessibilityHitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)_accessibilityUserTestingChildren;
- (struct CGPoint)accessibilityActivationPoint;
- (_Bool)accessibilityActivate;
- (id)accessibilityCustomRotorItemsAtIndex:(long long)arg1;
- (id)accessibilityCustomRotorTitles;
- (_Bool)_accessibilitySupportsActivateAction;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (id)_accessibilityTextViewTextOperationResponder;

@end