//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CRVehicleBluetoothDiscoverer : NSObject
{
    _Bool _isPairing;
    id <CRVehicleBluetoothDiscovery> _bluetoothDiscoveryDelegate;
    NSMutableDictionary *_deviceForAddress;
    CRBluetoothPairingPrompt *_outstandingPairingPrompt;
    CRBluetoothSyncContactsPrompt *_outstandingContactsPrompt;
}

@property(nonatomic) _Bool isPairing; // @synthesize isPairing=_isPairing;
@property(retain, nonatomic) CRBluetoothSyncContactsPrompt *outstandingContactsPrompt; // @synthesize outstandingContactsPrompt=_outstandingContactsPrompt;
@property(retain, nonatomic) CRBluetoothPairingPrompt *outstandingPairingPrompt; // @synthesize outstandingPairingPrompt=_outstandingPairingPrompt;
@property(retain, nonatomic) NSMutableDictionary *deviceForAddress; // @synthesize deviceForAddress=_deviceForAddress;
@property(nonatomic) __weak id <CRVehicleBluetoothDiscovery> bluetoothDiscoveryDelegate; // @synthesize bluetoothDiscoveryDelegate=_bluetoothDiscoveryDelegate;
- (void).cxx_destruct;
- (id)_presentingViewController;
- (void)_saveVehicleForDevice:(id)arg1;
- (void)_presentPairingFailedForDevice:(id)arg1;
- (void)deviceAuthenticationRequestHandler:(id)arg1;
- (void)deviceDisconnectedHandler:(id)arg1;
- (void)deviceConnectedHandler:(id)arg1;
- (void)deviceUnpairedHandler:(id)arg1;
- (void)deviceRemovedHandler:(id)arg1;
- (void)devicePairingSuccessHandler:(id)arg1;
- (void)devicePairingFailureHandler:(id)arg1;
- (void)deviceUpdatedHandler:(id)arg1;
- (void)_handleRemovedDevice:(id)arg1;
- (void)_handleUpdatedDevice:(id)arg1;
- (void)deviceDiscoveredHandler:(id)arg1;
- (_Bool)pairBluetoothDevice:(id)arg1;
- (id)_vehicleDeviceFromBluetoothDevice:(id)arg1;
- (_Bool)_supportsCarPlay:(id)arg1;
@property(readonly, copy, nonatomic) NSSet *discoveredBluetoothDevices;
- (void)handleRemovedVehicle:(id)arg1;
- (void)handleUpdatedVehicle:(id)arg1;
- (void)handleDiscoveredVehicle:(id)arg1;
- (void)stopDiscovery;
- (void)startDiscovery;
- (void)_allowBluetoothConnections:(_Bool)arg1;
- (void)dealloc;
- (id)init;

@end