//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XRDispatchInstrumentDecoratorBars : DTTimelineDecorator
{
    XRDispatchRun *_run;
    unsigned long long _graphIndex;
    int _type;
    unsigned long long _barWidth;
}

- (void).cxx_destruct;
- (id)decorateInspectionRanges:(id)arg1;
- (long long)_blockStatisticToGraph:(id)arg1;
- (long long)_queueStatisticToGraph:(id)arg1;
- (void)setDefaultsForPlane:(id)arg1;
- (id)initWithRun:(id)arg1 graphIndex:(unsigned long long)arg2 type:(int)arg3 barWidth:(unsigned long long)arg4;
- (id)init;

@end