//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface BlockTransferLinkView : UIView
{
    NSLayoutConstraint *_fromLinkHeightConstraint;
    NSLayoutConstraint *_separatorHeightConstraint;
    UIView *_fromLink;
    UIView *_separator;
}

@property(retain, nonatomic) UIView *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) UIView *fromLink; // @synthesize fromLink=_fromLink;
- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *destinationColor;
@property(retain, nonatomic) UIColor *separatorColor;
@property(retain, nonatomic) UIColor *originColor;
- (void)layoutSubviews;
- (double)_separatorViewHeight;
- (double)_fromLinkViewHeight;
- (double)_linkWidth;
- (void)_setupInitialConstraints;
- (id)_mkView;
- (void)_createSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end