//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol GEONavigationObserver <NSObject>

@optional
- (void)navigation:(GEONavigation *)arg1 didChangeShouldSuppressCellularDataAlerts:(_Bool)arg2;
- (void)navigationDidChangeNavigationState:(GEONavigation *)arg1;
- (void)navigation:(GEONavigation *)arg1 didUpdateDisplayETA:(NSDate *)arg2 displayRemainingTime:(double)arg3;
@end