//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol GEORouteHypothesizerDelegate <NSObject>
- (void)routeHypothesizerArrived:(GEORouteHypothesizerOld *)arg1;
- (void)routeHypothesizer:(GEORouteHypothesizerOld *)arg1 receivedETAError:(NSError *)arg2;
- (void)routeHypothesizer:(GEORouteHypothesizerOld *)arg1 receivedETAResponse:(GEOETATrafficUpdateResponse *)arg2;
- (void)routeHypothesizer:(GEORouteHypothesizerOld *)arg1 willSendETARequest:(GEOETATrafficUpdateRequest *)arg2;
- (void)routeHypothesizerUpdatedETA:(GEORouteHypothesizerOld *)arg1 etaRoute:(GEOETARoute *)arg2;
- (void)routeHypothesizer:(GEORouteHypothesizerOld *)arg1 matchedToRoute:(GEORouteMatch *)arg2;
- (void)routeHypothesizerRerouted:(GEORouteHypothesizerOld *)arg1 request:(GEODirectionsRequest *)arg2 response:(GEODirectionsResponse *)arg3;
- (void)routeHypothesizer:(GEORouteHypothesizerOld *)arg1 willRequestNewRoute:(GEODirectionsRequest *)arg2;
@end