//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol MNDirectionsSessionUIDelegate <NSObject>
- (void)directionsSessionUpdatedTrafficIncidents:(MNDirectionsSession *)arg1;
- (void)directionsSessionUpdatedETA:(MNDirectionsSession *)arg1;
- (void)directionsSession:(MNDirectionsSession *)arg1 failedWithError:(NSError *)arg2;
- (void)directionsSession:(MNDirectionsSession *)arg1 didChangeRoutePreloadSession:(id <GEORoutePreloadSession>)arg2;
- (void)directionsSession:(MNDirectionsSession *)arg1 didSwitchToNewRoute:(MNRoute *)arg2;
- (void)directionsSessionDidCancelRoute:(MNDirectionsSession *)arg1;
- (void)directionsSession:(MNDirectionsSession *)arg1 didRecalculateNewRoute:(MNRoute *)arg2;
- (void)directionsSessionDidCancelRecalculate:(MNDirectionsSession *)arg1;
- (void)directionsSessionWillRecalculateRoute:(MNDirectionsSession *)arg1;
- (void)directionsSessionDidFailToReceiveRoute:(MNDirectionsSession *)arg1 error:(NSError *)arg2;
- (void)directionsSession:(MNDirectionsSession *)arg1 didReceiveRouteSet:(RouteSet *)arg2;
- (void)directionsSessionWillRequestRoute:(MNDirectionsSession *)arg1;
- (void)directionsSession:(MNDirectionsSession *)arg1 didAppendRoutesInRouteSet:(RouteSet *)arg2;
- (void)directionsSessionDidFailToRecordTrace:(MNDirectionsSession *)arg1;
@end