//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface MNNavigationOverviewBar : MNNavigationBar
{
    id <MNNavigationOverviewBarDelegate> _delegate;
}

+ (id)overviewTitle;
+ (id)endTitle;
@property(nonatomic) __weak id <MNNavigationOverviewBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setOverviewButtonHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_endTapped;
- (void)_overviewTapped;
- (id)init;

@end