//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol MNNavigationDebugViewsControllerDelegate <NSObject>
- (ChromeViewController *)chromeViewController;
- (void)navigationDebugViewsTracePlaybackDidSeekToGuideMePortionOfTransitLeg:(MNNavigationDebugViewsController *)arg1;
- (void)navigationDebugViewsTracePlaybackDidSeek:(MNNavigationDebugViewsController *)arg1;
- (void)navigationDebugViewsTracePlaybackSpeedDidChange:(MNNavigationDebugViewsController *)arg1 speedMultiplier:(double)arg2;
@end