//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol NMMapsXPCInterface
- (void)_debug_fetchDiagnosticsString:(void (^)(NSString *, NSError *))arg1;
- (void)_debug_fetchServerConfiguration:(void (^)(NSDictionary *, NSError *))arg1;
- (void)setDroppedPin:(MSPDroppedPin *)arg1;
- (void)syncHistoryWithReply:(void (^)(void))arg1;
- (void)syncBookmarksWithReply:(void (^)(void))arg1;
- (void)requestSyncUpdateWithReply:(void (^)(void))arg1;
- (void)showPreviewRoute:(NSData *)arg1 forContext:(NSData *)arg2;
- (void)checkinForNavigationControl;
@end