//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NoGoodRouteTableViewCell : UITableViewCell
{
    UIImageView *_checkmarkImageView;
    UILabel *_titleLabel;
    _Bool _checked;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(nonatomic) _Bool checked; // @synthesize checked=_checked;
- (void).cxx_destruct;
- (id)_autolayoutMetrics;
- (id)_autolayoutViews;
- (void)_addAutolayoutConstraints;
- (void)_createSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end