//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NoResultBrowseCell : UITableViewCell
{
    UILabel *_titleLabel;
    NSLayoutConstraint *_preferredHeightConstraint;
    double _preferredHeight;
}

@property(nonatomic) double preferredHeight; // @synthesize preferredHeight=_preferredHeight;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end