//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSDate (TransitAdditions)
+ (id)_maps_maximumDateForTransitPlanning;
+ (id)_maps_minimumDateForTransitPlanningWithTimeZone:(id)arg1;
- (id)_maps_nextDayAtHour:(long long)arg1;
- (id)_maps_nextWeekday:(long long)arg1 atHour:(long long)arg2;
@end