//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface RAPNavigationItemValues : NSObject
{
    NSString *_title;
    UIBarButtonItem *_backBarButtonItem;
    UIView *_titleView;
    NSString *_prompt;
    _Bool _leftItemsSupplementBackButton;
    _Bool _hidesBackButton;
    NSArray *_leftBarButtonItems;
    NSArray *_rightBarButtonItems;
}

- (void).cxx_destruct;
- (void)setValuesOnNavigationItem:(id)arg1 animated:(_Bool)arg2;
- (void)takeValuesFromNavigationItem:(id)arg1;

@end