//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface RAPPlaceIssueQuestion : RAPQuestion <RAPTransitSubcategoryQuestionHost, RAPQuestionAcceptingAlternatePlace>
{
    id <RAPPlace> _reportedPlace;
    NSArray *_selectableIssues;
    id <RAPPlaceIssue> _selectedIssue;
    id <RAPPlaceIssue> _notListedIssue;
}

+ (_Bool)_canDisplayIssuesOtherThanProblemNotListed;
@property(retain, nonatomic) id <RAPPlaceIssue> selectedIssue; // @synthesize selectedIssue=_selectedIssue;
@property(retain, nonatomic, getter=_reportedPlace) id <RAPPlace> reportedPlace; // @synthesize reportedPlace=_reportedPlace;
- (void).cxx_destruct;
- (_Bool)_isRecursivelyComplete;
- (void)_fillSubmittableProblem:(id)arg1;
- (_Bool)isComplete;
- (_Bool)childTransitSubcategoryQuestionsShouldHideStationInfoIncorrect;
@property(readonly, nonatomic) id <RAPPlaceIssue> notListedIssue; // @synthesize notListedIssue=_notListedIssue;
@property(readonly, nonatomic) NSArray *selectableIssues; // @synthesize selectableIssues=_selectableIssues;
- (id)_locationClosedTitleForMapItem:(id)arg1;
@property(readonly, nonatomic) MKMapItem *snippetMapItem;
- (id)_initWithReport:(id)arg1 parentQuestion:(id)arg2 place:(id)arg3;
- (id)initWithReport:(id)arg1 parentQuestion:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end