//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface RAPReport : NSObject
{
    _Bool _willUpdate;
    RAPReportContext *_reportContext;
    RAPSubmitter *_submitter;
    NSMapTable *_observers;
    NSString *_submissionID;
    id <MKMapServiceProblemReportTicket> _ticket;
    _Bool _canCreateSubmittableProblem;
    _Bool _submitting;
    RAPCategoryQuestion *_categoryQuestion;
    RAPReportContext *_context;
    RAPSubmissionOutcome *_latestSubmissionOutcome;
}

@property(readonly, nonatomic) RAPSubmissionOutcome *latestSubmissionOutcome; // @synthesize latestSubmissionOutcome=_latestSubmissionOutcome;
@property(readonly, nonatomic, getter=isSubmitting) _Bool submitting; // @synthesize submitting=_submitting;
@property(readonly, nonatomic, getter=_context) RAPReportContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)cancelSubmission;
- (id)devicePushToken;
- (void)recordRAPSubmissionID:(id)arg1;
- (void)submitWithPrivacyRequestHandler:(CDUnknownBlockType)arg1 willStartSubmitting:(CDUnknownBlockType)arg2;
- (id)_auxiliaryControlsRecording;
- (_Bool)_getDirectionsMapItemsForStart:(out id *)arg1 end:(out id *)arg2;
- (id)_placeContext;
- (id)_mapContext;
- (void)_invokeChangeHandlers;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1 changeHandler:(CDUnknownBlockType)arg2;
- (id)newSubmittableProblem;
- (void)_update;
- (void)updateIfNeeded;
- (void)_setNeedsUpdate;
- (void)_questionDidChange:(id)arg1;
@property(readonly, nonatomic) _Bool canCreateSubmittableProblem; // @synthesize canCreateSubmittableProblem=_canCreateSubmittableProblem;
@property(readonly, nonatomic) RAPCategoryQuestion *categoryQuestion; // @synthesize categoryQuestion=_categoryQuestion;
- (id)initWithContext:(id)arg1 submitter:(id)arg2;
- (id)init;

@end