//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface RecentsViewController : CollectionsTableViewController <SearchManagerObserver, MKLocationManagerObserver, BrowseManagerObserver, SearchResultQuickActionMenuPresenterDelegate, BrowseViewDelegate, BrowseViewMapsDelegate>
{
    UIAlertController *_clearRecentsActionSheet;
    CurrentLocationHistoryItem *_currentLocationHistoryItem;
    CustomSearchResultHistoryItem *_customSearchResultHistoryItem;
    DirectionsHomeHistoryItem *_directionsHomeHistoryItem;
    id <RecentsViewControllerDelegate> _recentsViewControllerDelegate;
    _Bool _opaque;
    _Bool _showBrowse;
    _Bool _shouldIgnoreBrowseUpdate;
    _Bool _updatingRecents;
    _Bool _isScrolling;
    NSObject<OS_dispatch_queue> *_coreRecentsQueue;
    BrowseCellView *_browseCell;
    MKLocationManager *_locationManager;
    LoadingBrowseCell *_loadingCell;
    NoResultBrowseCell *_noResultCell;
    SearchResultQuickActionMenuPresenter *_quickActionMenuPresenter;
    _Bool _showsCollectionsButton;
    _Bool _showsShortcutView;
    _Bool _disableBrowse;
    NSArray *_systemRecents;
    NSArray *_orderedHistory;
    GEOLocation *_currentLocation;
    double _lastContentOffset;
}

+ (id)_searchRequestFromString:(id)arg1;
+ (id)title;
+ (id)dataSourceChangedNotification;
@property(nonatomic) double lastContentOffset; // @synthesize lastContentOffset=_lastContentOffset;
@property(retain, nonatomic) GEOLocation *currentLocation; // @synthesize currentLocation=_currentLocation;
@property(nonatomic) _Bool disableBrowse; // @synthesize disableBrowse=_disableBrowse;
@property(nonatomic) _Bool showsShortcutView; // @synthesize showsShortcutView=_showsShortcutView;
@property(nonatomic) _Bool showsCollectionsButton; // @synthesize showsCollectionsButton=_showsCollectionsButton;
@property _Bool updatingRecents; // @synthesize updatingRecents=_updatingRecents;
@property(copy, nonatomic) NSArray *orderedHistory; // @synthesize orderedHistory=_orderedHistory;
@property(copy) NSArray *systemRecents; // @synthesize systemRecents=_systemRecents;
@property(nonatomic) __weak id <RecentsViewControllerDelegate> recentsViewControllerDelegate; // @synthesize recentsViewControllerDelegate=_recentsViewControllerDelegate;
@property(retain, nonatomic) DirectionsHomeHistoryItem *directionsHomeHistoryItem; // @synthesize directionsHomeHistoryItem=_directionsHomeHistoryItem;
@property(retain, nonatomic) CustomSearchResultHistoryItem *customSearchResultHistoryItem; // @synthesize customSearchResultHistoryItem=_customSearchResultHistoryItem;
@property(retain, nonatomic) CurrentLocationHistoryItem *currentLocationHistoryItem; // @synthesize currentLocationHistoryItem=_currentLocationHistoryItem;
- (void).cxx_destruct;
- (void)locationManager:(id)arg1 didUpdateVehicleHeading:(double)arg2 timestamp:(id)arg3;
- (void)locationManager:(id)arg1 didUpdateVehicleSpeed:(double)arg2 timestamp:(id)arg3;
- (void)locationManagerDidResumeLocationUpdates:(id)arg1;
- (void)locationManagerDidPauseLocationUpdates:(id)arg1;
- (_Bool)locationManagerShouldPauseLocationUpdates:(id)arg1;
- (void)locationManagerFailedToUpdateLocation:(id)arg1 withError:(id)arg2;
- (void)locationManagerDidReset:(id)arg1;
- (void)locationManagerUpdatedLocation:(id)arg1;
- (void)updateSavedLocation:(id)arg1;
- (id)mapServiceTraitsForQuickActionPresenter:(id)arg1;
- (_Bool)quickActionMenuPresenter:(id)arg1 isPopularNearbyAtIndexPath:(id)arg2;
- (_Bool)shouldQuickActionMenuPresenter:(id)arg1 presentAtLocation:(struct CGPoint)arg2 inView:(id)arg3;
- (void)quickActionMenuPresenter:(id)arg1 selectedShowPlaceCard:(id)arg2;
- (void)quickActionMenuPresenter:(id)arg1 selectedShareLocationOf:(id)arg2;
- (void)quickActionMenuPresenter:(id)arg1 selectedViewWebsiteFor:(id)arg2;
- (void)quickActionMenuPresenter:(id)arg1 selectedCall:(id)arg2;
- (void)quickActionMenuPresenter:(id)arg1 selectedDirectionsTo:(id)arg2;
- (double)_tableMarginWidth;
- (void)viewDidLoad;
- (void)cancelActionSheetAnimated:(_Bool)arg1;
- (void)_presentClearRecentsAlert;
- (void)searchWithType:(int)arg1;
- (void)updateClearButton;
- (void)dataSourceChanged:(id)arg1;
- (double)browseViewParentWidth:(id)arg1;
- (void)browseViewUpdateHeight:(id)arg1;
- (void)browseViewCloseSelected:(id)arg1;
- (void)browseView:(id)arg1 categorySelected:(id)arg2;
- (void)browseView:(id)arg1 categoryShown:(id)arg2;
- (void)browseView:(id)arg1 actionSelected:(unsigned long long)arg2;
- (id)browseCell;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)_historyItemCellForIndexPath:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)noResultCell;
- (id)loadingCell;
- (_Bool)_updateDirectionsHome;
- (void)_updateCustomSearchResult;
- (_Bool)_updateCurrentLocation;
- (void)_updateSystemRecents;
- (unsigned long long)numberOfRows;
- (void)didMoveToParentViewController:(id)arg1;
- (void)_maps_backgroundCompositionStyleOverrideDidChange;
- (void)viewWillAppear:(_Bool)arg1;
- (void)updateBrowseViewState;
- (void)browseManagerStateUpdated;
- (void)queryCategory:(id)arg1;
- (void)dealloc;
- (id)initWithOpaqueBackground:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end