//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface RoutePickingTransitDirectionsController : NSObject <DirectionsStepsTableViewControllerDelegate, TransitDirectionsListViewControllerDelegate>
{
    RoutePickingSessionTransit *_sessionTransit;
    id <MainChromeTopBarContentProvider> _previousTopBarContentProvider;
    UIView *_previousScrollableBarContentControllerTopView;
    DirectionsStepsTableViewController *_walkingDirectionsListViewController;
    TransitDirectionsListViewController *_transitDirectionsListViewController;
    _Bool _previousRoutePickingModeBottomLineHidden;
    NSString *_previousMainButtonTitle;
    UIButton *_startRouteButton;
    long long _presentationStyle;
    UITransitionView *_transitionView;
    UIView *_routeCellSnapshotView;
    long long _transitionState;
    _Bool _isPresented;
    MNRoute *_route;
    id <RoutePickingTransitDirectionsControllerDelegate> _delegate;
    id <MainChromeTopBarContentProvider> _topBarContentProvider;
    id <PresenterPresentationSource> _shareSheetPresentationSource;
    PlacePresentationSelectionManagerContext *_placePresentationSelectionManagerContext;
}

@property(readonly, nonatomic) id <PresenterPresentationSource> shareSheetPresentationSource; // @synthesize shareSheetPresentationSource=_shareSheetPresentationSource;
@property(readonly, nonatomic) _Bool isPresented; // @synthesize isPresented=_isPresented;
@property(nonatomic) __weak id <RoutePickingTransitDirectionsControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MNRoute *route; // @synthesize route=_route;
- (void).cxx_destruct;
- (_Bool)placePresentationSelectionManager:(id)arg1 requiresMapsSelectionForPresentingPlacecardInContext:(id)arg2;
- (_Bool)placePresentationSelectionManager:(id)arg1 shouldUseDefaultPlaceCardPresentationForViewController:(id)arg2;
@property(readonly, nonatomic) PlacePresentationSelectionManagerContext *placePresentationSelectionManagerContext; // @synthesize placePresentationSelectionManagerContext=_placePresentationSelectionManagerContext;
- (id)placePresentationSelectionManager;
- (void)_configurePlacePresentation;
- (void)transitDirectionsListViewController:(id)arg1 didTapClusteredVehiclesCell:(id)arg2;
- (void)_zoomMapViewToItem:(id)arg1;
- (void)transitDirectionsListViewController:(id)arg1 didTapRowForItem:(id)arg2;
- (void)transitDirectionsListViewControllerDidInteractWithRouteOverviewCell:(id)arg1;
- (_Bool)transitDirectionsListViewControllerShouldAllowInfoCardsForEndpoints:(id)arg1;
- (_Bool)directionsStepsTableViewControllerShouldAllowInfoCardsForEndpoints:(id)arg1;
- (void)directionsStepsTableViewController:(id)arg1 didTapDisclosureForSearchResult:(id)arg2;
- (void)directionsStepsTableViewController:(id)arg1 didTapRowForRouteStep:(id)arg2;
- (void)doneButtonTapped:(id)arg1;
- (void)_share:(id)arg1;
@property(readonly, nonatomic) id <MainChromeTopBarContentProvider> topBarContentProvider; // @synthesize topBarContentProvider=_topBarContentProvider;
- (void)_updateTopBarAnimated:(_Bool)arg1;
- (struct CGPoint)_previewControllerRouteCellOriginWithFallback:(struct CGPoint)arg1;
- (struct CGPoint)transitionView:(id)arg1 beginOriginForToView:(id)arg2 forTransition:(int)arg3 defaultOrigin:(struct CGPoint)arg4;
- (struct CGPoint)transitionView:(id)arg1 endOriginForFromView:(id)arg2 forTransition:(int)arg3 defaultOrigin:(struct CGPoint)arg4;
- (void)_animateTransitionFromRoutePreviewCellToRouteOverviewCell;
- (void)transitionViewDidStart:(id)arg1;
- (void)transitionViewDidComplete:(id)arg1 finished:(_Bool)arg2;
- (void)_dismissTransitDirectionsListAnimated:(_Bool)arg1;
- (void)_presentTransitDirectionsListAnimated:(_Bool)arg1;
- (void)_updateDirectionsListViewControllerForOrientation;
- (void)layout;
- (void)layoutForUnobscuredBoundsChange;
- (void)dismissAnimated:(_Bool)arg1;
- (void)presentFromRoutePickingSessionTransit:(id)arg1 animated:(_Bool)arg2;
- (id)_mainChromeViewController;
@property(readonly, nonatomic) UIViewController<RouteDirectionsListController> *directionsListViewController;
- (id)_walkingDirectionsListViewController;
- (id)_transitDirectionsListViewController;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end