//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SearchBarSearchManager : NSObject <SearchBookmarksAndHistoryOperationDelegate, SearchMeCardLabelsOperationDelegate, SearchAddressBookOperationDelegate, SearchRecentsOperationDelegate>
{
    id <SearchBarSearchManagerDelegate> _delegate;
    NSOperationQueue *_searchQueue;
    NSString *_query;
    SearchBarSearchResults *_searchResults;
    MSPOngoingFetchRequest *_cachedFavorites;
}

@property(copy, nonatomic) NSString *query; // @synthesize query=_query;
- (void).cxx_destruct;
- (void)_searchUsingSearchRequest:(id)arg1;
- (long long)_integerValueForDefaultsKey:(id)arg1 networkDefaultsKey:(id)arg2 defaultValue:(long long)arg3;
- (void)cancelCurrentSearch;
- (void)searchName:(id)arg1 forSearchMode:(int)arg2 withTypes:(long long)arg3;
- (void)searchAddressBookOperation:(id)arg1 didMatchResults:(id)arg2;
- (void)searchRecentsOperation:(id)arg1 didMatchResults:(id)arg2;
- (void)meCardLabelsOperation:(id)arg1 didMatchResults:(id)arg2;
- (void)bookmarksAndHistoryOperation:(id)arg1 didFindMatches:(id)arg2;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end