//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SteppingContainingViewThatPretendsToBeAScrollView : UIView
{
    UIScrollView *scrollView;
}

@property __weak UIScrollView *scrollView; // @synthesize scrollView;
- (void).cxx_destruct;
- (_Bool)_canScrollY;
- (_Bool)_canScrollX;
- (double)_scrollHysteresis;
- (double)_touchDelayForScrollDetection;
- (double)_verticalVelocity;
- (double)_horizontalVelocity;
- (_Bool)_pagingRight;
- (_Bool)_pagingLeft;
- (_Bool)touchesShouldBegin:(id)arg1 withEvent:(id)arg2 inContentView:(id)arg3;
- (_Bool)delaysContentTouches;

@end