//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol SteppingModePlugin <NSObject>
@property(nonatomic) __weak id <CellVendor> cellVendor;
@property(readonly) long long numberOfSigns;
- (void)reloadSignAtIndex:(long long)arg1;
- (void)rectForSignAtIndex:(long long)arg1 currentStepIndex:(unsigned long long)arg2 handler:(void (^)(struct))arg3;
- (struct CGSize)sizeForSignAtIndex:(long long)arg1 fittingSize:(struct CGSize)arg2;
- (struct _NSRange)stepRangeForSignIndex:(long long)arg1;
- (long long)signIndexForStepIndex:(long long)arg1;
- (long long)signIndexForStep:(GEOComposedRouteStep *)arg1;
- (GEOComposedRouteStep *)stepAtSignIndex:(long long)arg1;
- (UIView *)auxViewAtIndex:(long long)arg1;
- (UICollectionViewCell *)signAtIndex:(long long)arg1;
@end