//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface TokenView : UIView
{
    UIView *_content;
    UIImageView *_image;
    UILabel *_label;
    UIColor *_currentColor;
    GEOSearchCategory *_currentCategory;
    _Bool _selected;
}

@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
- (void).cxx_destruct;
- (void)setText:(id)arg1;
- (void)updateToken;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setCategory:(id)arg1;
- (void)setImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end