//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface TransitRoutePickingTimingCell : TransitRoutePickingCell
{
    UILabel *_timeLabel;
    UIButton *_editButton;
    UILabel *_avoidedModesLabel;
    NSLayoutConstraint *_topToTimingLabelConstraint;
    NSLayoutConstraint *_avoidedLabelToTimeLabelConstraint;
    NSLayoutConstraint *_editButtonCenterYConstraint;
    NSLayoutConstraint *_editButtonBaselineConstraint;
    _Bool _centerEditButton;
    id <TransitRoutePickingTimingCellDelegate> _delegate;
    RoutePickingTiming *_routePickingTiming;
    long long _disabledTransitModes;
    TransitCustomTimingBannerFormatter *_textFormatter;
}

+ (id)reuseIdentifier;
@property(nonatomic) _Bool centerEditButton; // @synthesize centerEditButton=_centerEditButton;
@property(retain, nonatomic) TransitCustomTimingBannerFormatter *textFormatter; // @synthesize textFormatter=_textFormatter;
@property(nonatomic) long long disabledTransitModes; // @synthesize disabledTransitModes=_disabledTransitModes;
@property(retain, nonatomic) RoutePickingTiming *routePickingTiming; // @synthesize routePickingTiming=_routePickingTiming;
@property(nonatomic) __weak id <TransitRoutePickingTimingCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)_interLabelSpacing;
- (double)_topToLabelBaselineDistance;
- (void)_updateConstraintValues;
- (double)_availableWidthForTimingLabel;
- (void)_updateFonts;
- (void)_contentSizeCategoryDidChange;
- (void)_selectEdit;
- (id)_autolayoutConstraints;
- (void)layoutSubviews;
- (void)updateConstraints;
- (void)didMoveToWindow;
- (void)_createSubviews;
- (void)setSeparatorStyle:(long long)arg1;
- (id)init;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end