//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface TransitLegSteppingModeSign : NSObject
{
    GEOComposedRouteStep *_step;
    GEOComposedRouteLeg *_leg;
    struct _NSRange _stepIndexRange;
    TransitInstruction *_instruction;
    _Bool _isMatchedSign;
    MergedTransitRoutingIncidentMessage *_incidentMessage;
    NSArray *_alternateRouteLabelItems;
}

@property(readonly, nonatomic) NSArray *alternateRouteLabelItems; // @synthesize alternateRouteLabelItems=_alternateRouteLabelItems;
@property(nonatomic) _Bool isMatchedSign; // @synthesize isMatchedSign=_isMatchedSign;
@property(readonly, nonatomic) TransitInstruction *instruction; // @synthesize instruction=_instruction;
@property(nonatomic) struct _NSRange stepIndexRange; // @synthesize stepIndexRange=_stepIndexRange;
@property(readonly, nonatomic) GEOComposedRouteLeg *leg; // @synthesize leg=_leg;
@property(readonly, nonatomic) GEOComposedRouteStep *step; // @synthesize step=_step;
- (void).cxx_destruct;
@property(readonly, nonatomic) id <GEOTransitRoutingIncidentMessage> transitRoutingIncidentMessage;
@property(readonly, nonatomic) NSTimeZone *timeZoneForFormattedString;
@property(readonly, nonatomic) id <GEOServerFormattedString> tertiaryFormattedInstruction;
@property(readonly, nonatomic) id <GEOServerFormattedString> minorFormattedInstruction;
@property(readonly, nonatomic) id <GEOServerFormattedString> majorFormattedInstruction;
- (_Bool)hasValidInstructions;
- (_Bool)isWalking;
- (id)initWithWalkingLeg:(id)arg1 stepIndexRange:(struct _NSRange)arg2;
- (id)initWithStep:(id)arg1 stepIndexRange:(struct _NSRange)arg2 extraIncident:(id)arg3;
- (id)initWithStep:(id)arg1 stepIndexRange:(struct _NSRange)arg2;

@end