//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface TransitDirectionsListItemTransitTrip : TransitDirectionsListArtworkItem <TransitDirectionsListExpandableItem>
{
    NSString *_locallyGeneratedSubstepsFooter;
    _Bool _expanded;
    TransitDirectionsListBlockTransfer *_blockTransfer;
    GEOComposedTransitTripRouteStep *_boardStep;
    NSArray *_expandedItems;
    double _collaspedCellHeight;
}

+ (id)listItemWithBoardStep:(id)arg1;
@property(nonatomic) double collaspedCellHeight; // @synthesize collaspedCellHeight=_collaspedCellHeight;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
@property(copy, nonatomic) NSArray *expandedItems; // @synthesize expandedItems=_expandedItems;
@property(readonly, nonatomic) GEOComposedTransitTripRouteStep *boardStep; // @synthesize boardStep=_boardStep;
@property(retain, nonatomic) TransitDirectionsListBlockTransfer *blockTransfer; // @synthesize blockTransfer=_blockTransfer;
- (void).cxx_destruct;
- (void)updateForBoardStepSelectedIndexChange;
- (void)setTransitInstruction:(id)arg1;
- (id)initWithBoardStep:(id)arg1;
- (id)_operatingHoursForTrip;
@property(readonly, nonatomic) NSString *expandedItemsFooter;
- (_Bool)shouldEnableExpandedButton;
- (id)_countStopsStringClientFallback;
- (id)_countStopsStringFromServer;
- (id)expandingButtonTitleForExpandedState:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end