//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NLActivityDataProvider : NSObject <BBDataProvider, NLNanoExtendedHealthStoreAlertDelegate, NLActivitySubsectionDataProviderDelegate>
{
    NLNanoExtendedHealthStore *_nanoHealthStore;
    NSDictionary *_subsectionProviders;
    NSDictionary *_subsectionProvidersByCoachingSubmanagerIdentifier;
}

+ (id)_subsectionProviderClasses;
- (void).cxx_destruct;
- (void)showCoachingAlertRequests:(id)arg1;
- (void)hideSedentaryActivityAlert;
- (void)showSedentaryAlertOfType:(long long)arg1 withTimeoutDate:(id)arg2 withActiveHourCount:(long long)arg3 withTotalCount:(long long)arg4;
- (void)subsectionDataProviderInvalidateBulletins:(id)arg1;
- (void)subsectionDataProvider:(id)arg1 removeBulletin:(id)arg2;
- (void)subsectionDataProvider:(id)arg1 modifyBulletin:(id)arg2;
- (void)subsectionDataProvider:(id)arg1 addBulletin:(id)arg2;
- (id)preConfiguredBulletinForSubsectionDataProvider:(id)arg1;
- (void)handleBulletinActionResponse:(id)arg1;
- (id)clearedInfoForBulletins:(id)arg1 lastClearedInfo:(id)arg2;
- (id)bulletinsFilteredBy:(unsigned long long)arg1 enabledSectionIDs:(id)arg2 count:(unsigned long long)arg3 lastCleared:(id)arg4;
- (id)defaultSubsectionInfos;
- (id)sectionParameters;
- (id)sortDescriptors;
- (id)sectionDisplayName;
- (id)sectionIdentifier;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end