//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface MessageHeaderHeaderAccessibility : __MessageHeaderHeaderAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (_Bool)shouldGroupAccessibilityChildren;
- (id)accessibilityElements;
- (unsigned long long)accessibilityTraits;
- (void)_accessibilityLoadAccessibilityInformation;
- (id)initWithFrame:(struct CGRect)arg1 displayStyle:(int)arg2;

@end