//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface TimerViewControllerAccessibility : __TimerViewControllerAccessibility_super
{
}

+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)stopUpdatingTimerUI;
- (void)startUpdatingTimerUI;
- (id)init;

@end