//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FUBarSeriesAccessibility : __FUBarSeriesAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_accessibilityFormatStringForUnit:(id)arg1 value:(long long)arg2;
- (void)_axUpdateAccessibilityElements;
- (void)layoutSubviews;
- (_Bool)_accessibilityHitTestShouldFallbackToNearestChild;
- (void)_accessibilityLoadAccessibilityInformation;
- (id)_accessibilityLabelForBarYPoint:(double)arg1 withValue:(id)arg2;

@end