//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol AccountCreationProtocol

@optional
+ (id <AccountFullAccountProtocol>)accountWithBasicAccount:(ASSBasicAccount *)arg1;
+ (Class)classForAccountType:(NSString *)arg1;
@end