//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PSListControllerAccessibility : __PSListControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)reloadSpecifierAtIndex:(int)arg1 animated:(_Bool)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)_accessibilityHandleNavigationControllerDidStartTransition;
- (void)highlightSpecifierWithID:(id)arg1;
- (id)loadSpecifiersFromPlistName:(id)arg1 target:(id)arg2;

@end