//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NMGMapKitServer : NSObject <NSXPCListenerDelegate, MKCompanionXPCInterface, NMDeviceConnectionObserver>
{
    NSXPCListener *_listener;
    NSMutableArray *_peerConnections;
    NSMutableDictionary *_locationObserversForBundleIdentifier;
    NSLock *_lock;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocation:(id)arg1;
- (void)_sendStartUpdatingLocationMessage:(id)arg1;
- (void)_sendStopUpdatingLocationMessage:(id)arg1;
- (void)_stopLocationUpdatesForConnection:(id)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)connectionNeedsStateSynchronization:(id)arg1;
- (void)connection:(id)arg1 didChangeDeviceConnectivity:(_Bool)arg2;
- (id)_locationObserversForBundleIdentifier:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end