//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NPRFBluetoothManagerFacade : NSObject <RadiosPreferencesDelegate>
{
    double _lastBacklightAssertionUpdate;
    _Bool _isDisscovering;
    _Bool _airplaneModeOff;
    RadiosPreferences *_radioPrefs;
    id <NPRFBluetoothManagerDelegate> _delegate;
    unsigned int _mode;
    HKHealthStore *_healthStore;
    HKHealthServiceDiscovery *_healthDiscovery;
    CSLSBacklightAssertion *_backlightAssertion;
}

+ (_Bool)appActive;
+ (_Bool)isSupportedDevice:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) CSLSBacklightAssertion *backlightAssertion; // @synthesize backlightAssertion=_backlightAssertion;
@property(retain, nonatomic) HKHealthServiceDiscovery *healthDiscovery; // @synthesize healthDiscovery=_healthDiscovery;
@property(retain, nonatomic) HKHealthStore *healthStore; // @synthesize healthStore=_healthStore;
@property(nonatomic) unsigned int mode; // @synthesize mode=_mode;
@property(retain, nonatomic) id <NPRFBluetoothManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)airplaneModeChanged;
- (void)backlightDidChange:(id)arg1 from:(int)arg2 to:(int)arg3;
- (void)cancelBacklightAssertion;
- (void)renewBacklightAssertion;
- (void)numericComparisionHandler:(id)arg1;
- (void)pinRequestHandler:(id)arg1;
- (void)authenticationRequestHandler:(id)arg1;
- (void)healthDeviceUnpairedHandler:(id)arg1;
- (void)deviceUnpairedHandler:(id)arg1;
- (void)deviceRemovedHandler:(id)arg1;
- (void)healthDeviceDisconnectedHandler:(id)arg1;
- (void)deviceDisconnectedHandler:(id)arg1;
- (void)healthDeviceConnectedHandler:(id)arg1;
- (void)deviceConnectedHandler:(id)arg1;
- (void)deviceUpdatedHandler:(id)arg1;
- (void)checkDiscoveryModeAfterUpdatingDevice:(id)arg1;
- (void)healthDevicePairedHandler:(id)arg1;
- (void)devicePairedHandler:(id)arg1;
- (void)deviceDiscoveredHandler:(id)arg1;
- (void)powerChangedHandler:(id)arg1;
- (void)loadKnownDevices;
- (void)acceptSSPForDevice:(id)arg1 error:(int)arg2;
- (void)stopHealthDiscovery;
- (void)startHealthDiscovery;
- (void)removeObservers;
- (void)addObservers;
- (void)allowBluetoothConnections:(_Bool)arg1;
- (void)setConnectingMode:(_Bool)arg1;
- (void)stopDiscovery;
- (void)startDiscovery;
@property(readonly, nonatomic) _Bool isDiscovering;
- (void)turnOnBT;
@property(readonly, nonatomic) _Bool powerAndActive;
@property(readonly, nonatomic) _Bool power;
- (void)dealloc;
- (id)init;

@end