//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBAbstractDocumentEditor (IBiOSDocumentEditor)
- (BOOL)validateiOSUserInterfaceItem:(id)arg1;
- (void)debugConvertToIOS7WithScreenMetrics:(id)arg1;
- (void)debugConvertToIOS7IPad:(id)arg1;
- (void)debugConvertToIOS7IPhone:(id)arg1;
@end