//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBiOSDocumentInspectorViewController : IBCocoaTouchDocumentInspectorViewController
{
}

+ (id)documentPlatform;
- (id)alertAccessoryViewForDisablingConfigurations;
- (void)finishDisablingConfigurationsAndAutolayout:(BOOL)arg1 forDocuments:(id)arg2 withAlert:(id)arg3;

@end