//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _WDGraphSeriesZoomLevelConfigurationManager : NSObject
{
    NSMutableDictionary *_dataUnitGroupIDToConfiguration;
    NSMutableDictionary *_graphSeriesUUIDToConfiguration;
}

@property(retain, nonatomic) NSMutableDictionary *graphSeriesUUIDToConfiguration; // @synthesize graphSeriesUUIDToConfiguration=_graphSeriesUUIDToConfiguration;
@property(retain, nonatomic) NSMutableDictionary *dataUnitGroupIDToConfiguration; // @synthesize dataUnitGroupIDToConfiguration=_dataUnitGroupIDToConfiguration;
- (void).cxx_destruct;
- (id)_groupIDForDataUnitGroup:(id)arg1;
- (id)allGraphSeries;
- (id)allDataUnitGroups;
- (id)configurationForGraphSeries:(id)arg1;
- (id)configurationForDataUnitGroup:(id)arg1;
- (void)reset;
- (void)removeConfigurationForDataUnitGroup:(id)arg1;
- (void)addConfiguration:(id)arg1;
- (id)init;

@end