//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WDBasalBodyTemperatureDataProvider : WDDiscreteMinMaxDataProvider
{
}

- (id)chartPointForStatistics:(id)arg1 dataUnit:(id)arg2 timeScope:(long long)arg3;
- (unsigned long long)statisticsOptionsForTimeScope:(long long)arg1;

@end