//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WDCenteredHorizontalLineSeries : WDChartSeries
{
    UIColor *_fillColor;
    UIColor *_accentColor;
    double _lineWidth;
}

@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
@property(retain, nonatomic) UIColor *accentColor; // @synthesize accentColor=_accentColor;
@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
- (void).cxx_destruct;
- (void)_enumeratePointsWithValue:(long long)arg1 handler:(CDUnknownBlockType)arg2;
- (void)renderFillInContext:(struct CGContext *)arg1;
- (id)_clipImageFromBezierPath:(id)arg1;
- (void)renderChartInContext:(struct CGContext *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end