//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WDDataCategoryDetailViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UIViewControllerRestoration>
{
    NSArray *_dataUnitGroups;
    WDControllerManager *_controllerManager;
    UITableView *_tableView;
    NSUserActivity *_userActivity;
    _Bool _showListIcon;
    NSDate *_initialStartDate;
}

+ (id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2;
@property(retain, nonatomic) NSDate *initialStartDate; // @synthesize initialStartDate=_initialStartDate;
@property(nonatomic) _Bool showListIcon; // @synthesize showListIcon=_showListIcon;
- (void).cxx_destruct;
- (void)restoreUserActivityState:(id)arg1;
- (void)_tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 animated:(_Bool)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithDataUnitGroups:(id)arg1 controllerManager:(id)arg2 title:(id)arg3 userActivityCategoryID:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end