//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WDManualDataEntryTableViewCell : UITableViewCell <UITextFieldDelegate>
{
    unsigned long long _dataEntryType;
    UITextField *_valueField;
    UIView *_inputView;
    NSString *_decimalSeparator;
    UILabel *_displayNameLabel;
    UILabel *_unitLabel;
    NSArray *_displayNameLabelConstraints;
    HKDataUnit *_dataUnit;
    id <WDManualDataEntryTableViewCellDelegate> _delegate;
}

@property(nonatomic) __weak id <WDManualDataEntryTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) HKDataUnit *dataUnit; // @synthesize dataUnit=_dataUnit;
- (void).cxx_destruct;
- (void)_updateDecimalSeparator;
- (id)_sanitizedTextFieldText:(id)arg1;
- (id)_removeDecimalSeparatorsFromText:(id)arg1 numAllowed:(long long)arg2;
- (void)_localeDidChange:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)_valueFieldDidChange:(id)arg1;
- (id)inputView;
- (void)setInputView:(id)arg1;
- (void)endEditing;
- (void)beginEditing;
- (void)_setupUIWithDisplayName:(id)arg1 unitName:(id)arg2;
- (void)_updateDisplayNameLabelConstraints;
- (void)_setupConstraints;
@property(retain, nonatomic) NSString *value;
@property(retain, nonatomic) NSString *displayName;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)initWithDisplayName:(id)arg1 unitName:(id)arg2 dataEntryType:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end