//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WDWorkoutAddDataViewController : WDAddDataViewController <UIPickerViewDataSource, UIPickerViewDelegate>
{
    NSDateFormatter *_dateFormatter;
    NSDate *_startDate;
    NSDate *_endDate;
    UITableViewCell *_selectedCell;
    WDManualDataEntryTableViewCell *_startDateCell;
    UIDatePicker *_startDatePicker;
    WDManualDataEntryTableViewCell *_endDateCell;
    UIDatePicker *_endDatePicker;
    WDManualDataEntryTableViewCell *_totalDistanceCell;
    WDManualDataEntryTableViewCell *_totalEnergyBurnedCell;
    NSArray *_workoutActivityTypePairs;
    WDManualDataEntryTableViewCell *_workoutActivityTypeCell;
    UIPickerView *_workoutActivityTypePicker;
    _Bool _hasSelectedDefaultPickerLocation;
    HKQuantityType *_distanceType;
    NSArray *_sectionsWithDistance;
    NSArray *_sectionsWithoutDistance;
}

- (void).cxx_destruct;
- (void)_startDatePickerChanged:(id)arg1;
- (void)_endDatePickerChanged:(id)arg1;
- (id)_roundDateToNearestMinute:(id)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)_updateCurrentDistanceTypeWithActivityType:(unsigned long long)arg1;
- (id)_sections;
- (void)_setDefaultActivityTypePickerIfNecessary;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)_rowsForSection:(long long)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (unsigned long long)_selectedActivityType;
- (unsigned long long)_activityTypeForIndex:(long long)arg1;
- (id)_activityTypeDescriptionForIndex:(long long)arg1;
- (long long)_indexOfActivityType:(unsigned long long)arg1;
- (id)_generateSortedActivityTypes;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)_distanceDisplayName;
- (id)_dataUnitForDistanceType:(id)arg1;
- (id)_dataUnitForGroupIdentifier:(long long)arg1;
- (id)_quantityFromCell:(id)arg1 unit:(id)arg2;
- (id)_totalEnergyBurned;
- (id)_totalDistance;
- (void)saveHKObjectWithCompletion:(CDUnknownBlockType)arg1;
- (void)unitPreferencesDidChange:(id)arg1;
- (void)localeDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithDataUnitGroup:(id)arg1 controllerManager:(id)arg2 unitController:(id)arg3 initialStartDate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end