//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NTKMoonPhaseTimelineEntryModelAccessibility : __NTKMoonPhaseTimelineEntryModelAccessibility_super
{
}

+ (id)colorCircular:(id)arg1;
+ (id)smallUtility:(id)arg1;
+ (id)smallModular:(id)arg1;
+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;

@end