//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol DYLayerManager <NSObject>
- (void)setAnchorPoint:(const struct Argument *)arg1 forLayerID:(unsigned long long)arg2;
- (void)setPosition:(const struct Argument *)arg1 forLayerID:(unsigned long long)arg2;
- (void)setTransform:(const struct Argument *)arg1 forLayerID:(unsigned long long)arg2 withScreenToLayerScale:(const struct pair<double, double> *)arg3;
- (void)deleteLayer:(unsigned long long)arg1;
- (CALayer *)currentTopLayer;
- (CALayer *)layerForID:(unsigned long long)arg1;
- (void)prepareLayerForPresent:(CALayer *)arg1;
- (void)updateLayer:(CALayer *)arg1 contentRect:(struct CGRect)arg2 contentsScale:(double)arg3 properties:(NSDictionary *)arg4;
- (CALayer *)createLayerWithID:(unsigned long long)arg1 contentRect:(struct CGRect)arg2 contentsScale:(double)arg3 properties:(NSDictionary *)arg4 isCoreAnimationSurface:(_Bool)arg5;
@end