//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLAlertItem : NSObject
{
    CUISAlertViewController *_alertViewController;
    NSString *_identifier;
    unsigned int _priority;
}

+ (id)alertItemWithViewController:(id)arg1;
@property(nonatomic) unsigned int priority; // @synthesize priority=_priority;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) CUISAlertViewController *alertViewController; // @synthesize alertViewController=_alertViewController;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)hash;
- (_Bool)isEqual:(id)arg1;

@end