//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLAlertQuickLongLookView : UIView <UIScrollViewDelegate>
{
    UIScrollView *_scrollView;
    UIView *_contentView;
    UIView *_clientContentView;
    NTKDigitalTimeLabel *_timeLabel;
    NSMutableArray *_buttons;
    UILabel *_quickLookLabel;
    UILabel *_longLookLabel;
    UILabel *_quickLookSubtitleLabel;
    CUISAlertChevronView *_topChevron;
    CUISAlertChevronView *_bottomChevron;
    NSTimer *_slowScrollTimeoutTimer;
    struct CGRect _cachedQuickLookLabelRect;
    struct CGPoint _cachedQuicklookIconCenter;
    float _scaleAmountForQuicklookLabel;
    float _scaleAmountForQuicklookIcon;
    _Bool _scrolling;
    _Bool _needsReloadAfterScrollEnd;
    _Bool _needsLayoutUpdateForLonglook;
    _Bool _hasDraggedPastBottomThreshold;
    _Bool _invokedSwipeUpAction;
    _Bool _swipeDownToDismissEnabled;
    _Bool _swipeUpToActionEnabled;
    _Bool _hasQuickLookBeenPresented;
    _Bool _hasLongLookBeenPresented;
    _Bool _isAnimatingToLongLook;
    _Bool _isScrollingBeyondVisible;
    _Bool _isScrollingFromBeyondVisible;
    id <CSLAlertQuickLongLookViewDelegate> _delegate;
    id <CSLAlertQuickLongLookViewDataSource> _dataSource;
    float _percentLongLookPresented;
    UIView *_quickLookIconView;
    UIView *_longLookIconView;
}

@property(retain, nonatomic) UIView *longLookIconView; // @synthesize longLookIconView=_longLookIconView;
@property(retain, nonatomic) UIView *quickLookIconView; // @synthesize quickLookIconView=_quickLookIconView;
@property(nonatomic) float percentLongLookPresented; // @synthesize percentLongLookPresented=_percentLongLookPresented;
@property(nonatomic) _Bool isScrollingFromBeyondVisible; // @synthesize isScrollingFromBeyondVisible=_isScrollingFromBeyondVisible;
@property(nonatomic) _Bool isScrollingBeyondVisible; // @synthesize isScrollingBeyondVisible=_isScrollingBeyondVisible;
@property(nonatomic) _Bool isAnimatingToLongLook; // @synthesize isAnimatingToLongLook=_isAnimatingToLongLook;
@property(nonatomic) _Bool hasLongLookBeenPresented; // @synthesize hasLongLookBeenPresented=_hasLongLookBeenPresented;
@property(nonatomic) _Bool hasQuickLookBeenPresented; // @synthesize hasQuickLookBeenPresented=_hasQuickLookBeenPresented;
@property(nonatomic) _Bool swipeUpToActionEnabled; // @synthesize swipeUpToActionEnabled=_swipeUpToActionEnabled;
@property(nonatomic) _Bool swipeDownToDismissEnabled; // @synthesize swipeDownToDismissEnabled=_swipeDownToDismissEnabled;
@property(nonatomic) __weak id <CSLAlertQuickLongLookViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <CSLAlertQuickLongLookViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_didTapButton:(id)arg1;
- (id)_buttonWithTitle:(id)arg1;
- (void)reloadData;
- (void)_reloadIcon;
- (void)_updateInterfaceAtScrollEnd;
- (void)_scrollToLongLook;
- (void)_fadeTimeLabelByPercent:(float)arg1;
- (void)_fadeSubtitleByPercent:(float)arg1;
- (void)_updateLabelColorByPercent:(float)arg1;
- (void)_scaleLabelByPercent:(float)arg1;
- (void)_translateLabelByPercent:(float)arg1;
- (void)_translateIconByPercent:(float)arg1;
- (void)_scaleIconByPercent:(float)arg1;
- (void)_crossFadeIconsByPercent:(float)arg1;
- (void)_updateQuicklookViewsForOffset:(float)arg1;
- (void)_handleScrollDidEnd:(id)arg1;
- (void)_doSwipeUpAction;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (_Bool)_draggedPastBottomActionThreshold;
- (_Bool)_draggedPastTopActionThreshold;
- (_Bool)_scrollViewPastBottomThreshold:(float)arg1;
- (_Bool)_scrollViewPastTopThreshold:(float)arg1;
- (void)prepareToShowQuickLook;
- (void)_prepareQuickLookAnimation;
- (void)_animateInQuickLookWithDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_prepareLongLookAnimation;
- (void)_animateInLongLookWithDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animateInWithDuration:(double)arg1 animationStyle:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentQuickLook:(_Bool)arg1;
- (void)presentQuickLook;
- (void)_slowScrollTimeoutExpired;
- (void)_didTapIcon:(id)arg1;
- (void)_didTapScrollView:(id)arg1;
- (void)_updateLayoutForLongLook;
- (void)scrollToContentOffset:(float)arg1 animated:(_Bool)arg2;
- (void)scrollToBottom:(_Bool)arg1;
- (void)scrollToTop:(_Bool)arg1;
- (void)presentLongLook;
- (void)_updateBottomChevron;
- (id)_labelForBottomChevron;
- (id)_createBottomChevron;
- (id)_createTopChevron;
- (void)_initSubviews;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end