//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLBulletinDefaultFactory : CUISBulletinClientFactory
{
    CSLBulletinAlertItem *_bulletin;
    NSUserActivity *_userActivity;
    _Bool _shouldPresentActionMenu;
    _Bool _shouldClearBulletinsAfterDismissal;
}

+ (id)_userActivityWithBulletin:(id)arg1;
@property(nonatomic) _Bool shouldClearBulletinsAfterDismissal; // @synthesize shouldClearBulletinsAfterDismissal=_shouldClearBulletinsAfterDismissal;
@property(nonatomic) _Bool shouldPresentActionMenu; // @synthesize shouldPresentActionMenu=_shouldPresentActionMenu;
- (void).cxx_destruct;
- (id)userActivity;
- (_Bool)shouldClearBulletinsAfterDismissalForReason:(unsigned int)arg1;
- (void)textReplySuggestionsForLanguage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_handleAction:(id)arg1;
- (id)bbActions;
- (id)actionMenuPresentation;
- (id)primaryPagePresentation;
- (id)initWithBulletin:(id)arg1;

@end