//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLGlancePowerPreheatScheduleProvider : NSObject <CSLPrelaunchScheduleProvider>
{
    int _remoteChargerStateNotifyToken;
    unsigned int _remoteDevicePowerState;
    NSDate *_lastPreheatDate;
    NSDate *_offPowerPreheatBudgetResetDate;
    unsigned int _offPowerPreheatCount;
    unsigned int _onPowerStaggeredBatchSize;
    unsigned int _localDevicePowerState;
    NSMutableArray *_duetIdentifiersToPreheatOnPower;
    id <CSLPrelaunchScheduleProviderDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_queue;
    CSLGlanceSwitcherViewController *_glanceSwitcherViewController;
}

@property(retain, nonatomic) CSLGlanceSwitcherViewController *glanceSwitcherViewController; // @synthesize glanceSwitcherViewController=_glanceSwitcherViewController;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <CSLPrelaunchScheduleProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_forceUnpoweredPreheat;
- (void)_reset;
- (void)_localDevicePowerStateChanged:(id)arg1;
- (void)_unregisterForDuetEvents;
- (void)_fetchRemoteState;
- (void)_registerForDuetEvents;
- (id)_duetIdentifiersForUnpoweredPreheat;
- (_Bool)_preheatGlanceRange;
- (void)_resetOffPowerPreheatBudget;
- (void)_reduceAvailableOffPowerPreheatBudget;
- (_Bool)_isOffPowerPreheatAllowed;
- (_Bool)_isOnPower;
- (_Bool)_preheatBatch;
- (_Bool)_executeUnpowered;
- (_Bool)_executePowered;
- (id)_nextScheduledDateWhenUnpowered;
- (id)_nextScheduledDateWhenPowered;
- (_Bool)execute;
- (id)nextScheduledDate;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end