//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLGlanceAlertViewController : CUISAlertViewController
{
    CSLGlance *_glance;
    id <CUISGlanceController> _glanceController;
    id <CSLGlanceAlertViewControllerDelegate> _delegate;
    UIViewController<CUISGlanceViewController> *_glanceViewController;
    UIView *_container;
    id _policyAssertion;
}

@property(retain, nonatomic) id policyAssertion; // @synthesize policyAssertion=_policyAssertion;
@property(retain, nonatomic) UIView *container; // @synthesize container=_container;
@property(retain, nonatomic) UIViewController<CUISGlanceViewController> *glanceViewController; // @synthesize glanceViewController=_glanceViewController;
@property(nonatomic) __weak id <CSLGlanceAlertViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <CUISGlanceController> glanceController; // @synthesize glanceController=_glanceController;
@property(readonly, nonatomic) CSLGlance *glance; // @synthesize glance=_glance;
- (void).cxx_destruct;
- (id)animationControllerForPresentation;
- (void)deactivate;
- (void)viewDidLoad;
- (id)initWithGlanceController:(id)arg1;

@end