//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLGlanceSwitcherViewController : UIViewController <CSLSupplementalAnimationProvider, PUICPageScrollViewControllerDataSource, PUICPageScrollViewControllerDelegate, CUISGlanceServiceViewControllerDelegate, CSLGlanceManagerObserver, CSLUITileNavigationControllerChildViewController>
{
    _Bool _scrollEnabled;
    id <CSLGlanceSwitcherViewControllerDelegate> _delegate;
    id <CSLGlanceBackgroundAnimationProvider> _backgroundAnimationProvider;
    PUICPageScrollViewController *_viewController;
    unsigned int _currentGlanceIndex;
    NSMutableArray *_glances;
    NSString *_currentGlanceID;
    CSLGlanceCorePredictionController *_corePredictionController;
    NSTimer *_dwellTimer;
    CSLGlanceUserActivityController *_userActivityController;
    CSLGlanceUserActivityAssertion *_appearanceAssertion;
    CSLGlanceUserActivityAssertion *_dwellTimerAssertion;
    CSLGlanceUserActivityAssertion *_alertWindowAssertion;
    CSLGlanceCoreDuetDwellRecorder *_dwellRecorder;
    int _scrollDirection;
    CDUnknownBlockType _pendingCompletion;
    unsigned int _pendingCompletionIndex;
    id <CSLGlanceSwitcherPPTDelegate> _pptDelegate;
    CSLGlanceAggDPresentationRecorder *_presentationRecorder;
}

@property(retain, nonatomic) CSLGlanceAggDPresentationRecorder *presentationRecorder; // @synthesize presentationRecorder=_presentationRecorder;
@property(nonatomic) __weak id <CSLGlanceSwitcherPPTDelegate> pptDelegate; // @synthesize pptDelegate=_pptDelegate;
@property(nonatomic) unsigned int pendingCompletionIndex; // @synthesize pendingCompletionIndex=_pendingCompletionIndex;
@property(copy, nonatomic) CDUnknownBlockType pendingCompletion; // @synthesize pendingCompletion=_pendingCompletion;
@property(nonatomic) int scrollDirection; // @synthesize scrollDirection=_scrollDirection;
@property(retain, nonatomic) CSLGlanceCoreDuetDwellRecorder *dwellRecorder; // @synthesize dwellRecorder=_dwellRecorder;
@property(retain, nonatomic) CSLGlanceUserActivityAssertion *alertWindowAssertion; // @synthesize alertWindowAssertion=_alertWindowAssertion;
@property(retain, nonatomic) CSLGlanceUserActivityAssertion *dwellTimerAssertion; // @synthesize dwellTimerAssertion=_dwellTimerAssertion;
@property(retain, nonatomic) CSLGlanceUserActivityAssertion *appearanceAssertion; // @synthesize appearanceAssertion=_appearanceAssertion;
@property(retain, nonatomic) CSLGlanceUserActivityController *userActivityController; // @synthesize userActivityController=_userActivityController;
@property(retain, nonatomic) NSTimer *dwellTimer; // @synthesize dwellTimer=_dwellTimer;
@property(retain, nonatomic) CSLGlanceCorePredictionController *corePredictionController; // @synthesize corePredictionController=_corePredictionController;
@property(retain, nonatomic) NSString *currentGlanceID; // @synthesize currentGlanceID=_currentGlanceID;
@property(retain, nonatomic) NSMutableArray *glances; // @synthesize glances=_glances;
@property(nonatomic, getter=isScrollEnabled) _Bool scrollEnabled; // @synthesize scrollEnabled=_scrollEnabled;
@property(nonatomic) unsigned int currentGlanceIndex; // @synthesize currentGlanceIndex=_currentGlanceIndex;
@property(retain, nonatomic) PUICPageScrollViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) __weak id <CSLGlanceBackgroundAnimationProvider> backgroundAnimationProvider; // @synthesize backgroundAnimationProvider=_backgroundAnimationProvider;
@property(nonatomic) __weak id <CSLGlanceSwitcherViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_logCurrentGlanceDidDisappear;
- (void)_logCurrentGlanceDidAppear;
- (void)setPPTDelegate:(id)arg1;
- (void)containerScrollViewDidStop:(id)arg1;
- (void)containerScrollViewDidScroll:(id)arg1 withDirection:(unsigned int)arg2;
- (void)_handleGlanceViewControllerDidChange:(id)arg1;
- (void)_reloadGlance:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reloadGlance:(id)arg1;
- (void)glance:(id)arg1 didUpdateUserActivity:(id)arg2;
- (void)glance:(id)arg1 didUpdatePrelaunchBundleID:(id)arg2;
- (void)glance:(id)arg1 didRaiseCorePredictionEvent:(id)arg2 expertType:(id)arg3;
- (void)glance:(id)arg1 didRequestAppLaunchWithBundleID:(id)arg2 launchURL:(id)arg3;
- (void)glanceManager:(id)arg1 didUpdateGlances:(id)arg2 addedGlanceIDs:(id)arg3 removedGlanceIDs:(id)arg4 includesSelectionCandidates:(_Bool)arg5 reset:(_Bool)arg6;
- (void)pageScrollViewController:(id)arg1 pageDidDisappearAtIndex:(unsigned int)arg2;
- (void)pageScrollViewController:(id)arg1 pageWillDisappearAtIndex:(unsigned int)arg2;
- (void)pageScrollViewControllerDidStopScrolling:(id)arg1;
- (void)pageScrollViewController:(id)arg1 pageWillAppearAtIndex:(unsigned int)arg2;
- (unsigned int)pageScrollViewControllerNumberOfPages:(id)arg1;
- (id)pageScrollViewController:(id)arg1 viewControllerForPageAtIndex:(unsigned int)arg2;
- (void)pageScrollViewController:(id)arg1 didScrollToPageAtIndex:(unsigned int)arg2;
- (struct CGPoint)_offsetBetweenPoint:(struct CGPoint)arg1 point2:(struct CGPoint)arg2;
- (void)configureAnimation:(id)arg1;
- (void)configureDosidoAnimation:(id)arg1;
- (void)_notifyDuetOfGlanceDidSettle;
- (void)_notifyDuetOfDeactivation;
- (void)_notifyDuetOfActivation;
- (id)_currentDuetIdentifiers;
- (void)_updateAnimationDatesForGlance:(id)arg1;
- (void)_playSettleAnimationForGlance:(id)arg1;
- (void)_playSwipeInAnimationForGlance:(id)arg1;
- (void)_updateGlancesWithGlances:(id)arg1 addedGlanceIDs:(id)arg2 removedGlanceIDs:(id)arg3 includesSelectionCandidates:(_Bool)arg4 reset:(_Bool)arg5;
- (id)_glanceWithViewController:(id)arg1;
- (unsigned int)_indexOfGlanceWithID:(id)arg1;
- (void)_firePendingCompletion:(_Bool)arg1;
- (_Bool)_isActivelyScrolling;
- (void)_handleAlertDidHide:(id)arg1;
- (void)_handleAlertWillShow:(id)arg1;
- (void)_activateUserActivityForGlance:(id)arg1;
- (void)_resignCurrentUserActivity;
- (void)_setCurrentUserActivity:(id)arg1 forceRefresh:(_Bool)arg2;
- (void)_saveCurrentGlanceID;
- (void)_stopDwelling;
- (void)_startDwelling;
- (void)_handleDwellTimer:(id)arg1;
- (void)_stopDwellTimer;
- (void)_startDwellTimer;
- (void)_postChangeNotificationIfNeeded;
- (id)duetIdentifiersForGlancesRequiringPreheat;
- (id)duetIdentifiersForGlancesSupportingPreheat;
- (void)resetPreheatForGlanceWithDuetIdentifier:(id)arg1;
- (_Bool)prelaunchNextGlance;
- (void)enumerateGlancesFromSelectedGlanceUsingBlock:(CDUnknownBlockType)arg1;
- (void)preheatAllPossibleGlancesWithCompletion:(CDUnknownBlockType)arg1;
- (void)preheatGlancesWithDuetIdentifiers:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)preheatAllNecessaryGlancesWithCompletion:(CDUnknownBlockType)arg1;
- (void)_forcePreheatOfGlancesAdjacentToGlance:(id)arg1;
- (id)_duetIdentifiersOfGlancesNeedingPreheat;
- (unsigned int)_indexOfFirstGlanceNeedingPrelaunch;
@property(nonatomic, getter=isPagingEnabled) _Bool pagingEnabled;
- (unsigned int)indexOfGlanceWithBundleIdentifier:(id)arg1;
- (unsigned int)indexOfGlanceWithGlanceID:(id)arg1;
- (void)scrollToGlanceAtIndex:(unsigned int)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)scrollToGlanceAtIndex:(unsigned int)arg1 animated:(_Bool)arg2;
- (_Bool)scrollEnabled;
@property(readonly, nonatomic) UIViewController<CUISGlanceServiceViewController> *currentGlanceViewController;
- (id)glanceViewControllerForGlance:(id)arg1;
- (id)glanceAtIndex:(unsigned int)arg1;
@property(readonly, nonatomic) CSLGlance *currentGlance;
- (void)_endDwellRecordingSession;
- (void)_beginDwellRecordingSession;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)_configurePrelauncher;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end