//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLGlanceSwitcherPPTHelper : NSObject <CSLGlanceSwitcherPPTDelegate>
{
    _Bool _testActive;
    NSString *_testName;
    unsigned int _fromGlanceIndex;
    unsigned int _toGlanceIndex;
    NSString *_prefix;
    NSString *_currentSubtestName;
    unsigned int _state;
}

@property(nonatomic) _Bool testActive; // @synthesize testActive=_testActive;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
@property(retain, nonatomic) NSString *currentSubtestName; // @synthesize currentSubtestName=_currentSubtestName;
@property(retain, nonatomic) NSString *prefix; // @synthesize prefix=_prefix;
@property(nonatomic) unsigned int toGlanceIndex; // @synthesize toGlanceIndex=_toGlanceIndex;
@property(nonatomic) unsigned int fromGlanceIndex; // @synthesize fromGlanceIndex=_fromGlanceIndex;
@property(retain, nonatomic) NSString *testName; // @synthesize testName=_testName;
- (void).cxx_destruct;
- (void)glanceSwitcher:(id)arg1 reachedState:(unsigned int)arg2 forGlanceAtIndex:(unsigned int)arg3;
- (void)finishSubtest;
- (void)_startSubtestWithState:(unsigned int)arg1;
- (void)_startSubtestFromState:(unsigned int)arg1 toState:(unsigned int)arg2;
- (void)finishSubtests;
- (void)startDetailedSubtestsWithGlanceViewController:(id)arg1 fromGlanceAtIndex:(unsigned int)arg2 toGlanceAtIndex:(unsigned int)arg3;
- (id)initWithTestName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end