//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLStoreDemoSupport : NSObject
{
    _Bool _isRunningInDemoMode;
    _Bool _hasDemoLoop;
    _Bool _shouldRunNanoDemo;
    CSLIconPositionsStore *_iconPositionsStore;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool shouldRunNanoDemo; // @synthesize shouldRunNanoDemo=_shouldRunNanoDemo;
@property(nonatomic) _Bool hasDemoLoop; // @synthesize hasDemoLoop=_hasDemoLoop;
@property(nonatomic) _Bool isRunningInDemoMode; // @synthesize isRunningInDemoMode=_isRunningInDemoMode;
@property(nonatomic) __weak CSLIconPositionsStore *iconPositionsStore; // @synthesize iconPositionsStore=_iconPositionsStore;
- (void).cxx_destruct;
- (id)init;
- (void)resetIconLayout;

@end