//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CSLUIApplicationIconView : CSLUIIconView
{
    UIImageView *_deleteAppButton;
    CSLUIJiggleView *_jiggleView;
    CSLUIApplicationIconDownloadProgressView *_progressView;
    UIImageView *_maskImageView;
    UIView *_iconProxyView;
    struct CGSize _screenSize;
    _Bool _isDeletable;
}

@property(nonatomic) _Bool isDeletable; // @synthesize isDeletable=_isDeletable;
- (void).cxx_destruct;
- (void)setAlpha:(float)arg1;
- (void)cleanupForAnimationZoom;
- (void)prepareForAnimationZoom;
- (void)applyLayoutAttributes:(CDStruct_727cf631)arg1;
- (void)resumeJiggling;
- (void)pauseJiggling;
- (void)cleanupDownloadProgressView;
- (void)updateDownloadProgress:(double)arg1;
- (void)setupProgressView;
- (void)cleanupJiggling;
- (void)_shrinkDeleteAppButtonAnimationWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)updateDeletionIcon;
- (void)setupJiggling;
- (void)setIcon:(id)arg1;
- (id)initWithIcon:(id)arg1 isDeletable:(_Bool)arg2;

@end