//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol CUISGlanceServiceViewControllerDelegate
- (void)glance:(UIViewController<CUISGlanceServiceViewController> *)arg1 didUpdatePrelaunchBundleID:(NSString *)arg2;
- (void)reloadGlance:(UIViewController<CUISGlanceServiceViewController> *)arg1;
- (void)glance:(UIViewController<CUISGlanceServiceViewController> *)arg1 didUpdateUserActivity:(NSUserActivity *)arg2;
- (void)glance:(UIViewController<CUISGlanceServiceViewController> *)arg1 didRaiseCorePredictionEvent:(NSDictionary *)arg2 expertType:(NSString *)arg3;
- (void)glance:(UIViewController<CUISGlanceServiceViewController> *)arg1 didRequestAppLaunchWithBundleID:(NSString *)arg2 launchURL:(NSURL *)arg3;
@end