//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IOSSHLBasicActivateAppTransaction : IOSSHLContextSwitchTransaction <FBApplicationUpdateScenesTransactionObserver>
{
    _Bool _activatingSuspended;
    IOSSHLApplication *_activatingApplication;
}

@property(nonatomic) _Bool activatingSuspended; // @synthesize activatingSuspended=_activatingSuspended;
@property(retain, nonatomic) IOSSHLApplication *activatingApplication; // @synthesize activatingApplication=_activatingApplication;
- (void).cxx_destruct;
- (id)_sceneSettingsForApp:(id)arg1 orientation:(int *)arg2;
- (void)_activateApplication;
- (void)_sceneWillCommit:(id)arg1;
- (void)_departingContextDidNotChange;
- (void)transaction:(id)arg1 willCommitSceneUpdate:(id)arg2;
- (_Bool)shouldWatchdog:(id *)arg1;
- (void)_childTransactionDidComplete:(id)arg1;
- (void)_cleanupEnteringScenes;
- (void)_activateEnteringScenes;
- (_Bool)_isDepartingContext:(id)arg1;
- (void)_didComplete;
- (void)_willBegin;
@property(readonly, copy) NSString *debugDescription;
- (id)initWithResultBlock:(CDUnknownBlockType)arg1;
- (id)initWithApplication:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end