//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol NCClockIconViewZoomController <NSObject>
- (void)clockIconViewCleanupZoom:(NCClockIconView *)arg1;
- (void)clockIconView:(NCClockIconView *)arg1 setZoomDiameter:(float)arg2;
- (void)clockIconViewPrepareZoom:(NCClockIconView *)arg1;
@end