//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PassbookUIServiceApplication : UIApplication
{
    NSNumber *_statusBarHeightOverride;
}

+ (_Bool)shouldBackgroundMainThreadOnSuspendedLaunch;
@property(retain, nonatomic) NSNumber *statusBarHeightOverride; // @synthesize statusBarHeightOverride=_statusBarHeightOverride;
- (double)statusBarHeight;
- (void)dealloc;

@end