//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface AppDelegate : UIResponder <UIApplicationTestingDelegate, CNContactViewControllerDelegate, CNMultipleUnknownContactsViewControllerDelegate, UIApplicationDelegate>
{
    UIWindow *_window;
    UIViewController *_rootViewController;
    ContactsSplitViewController *_splitViewController;
    CNContact *_restoredContact;
    CNContact *_restoredUnsavedContact;
    NSMutableArray *_receivedContactsQueue;
    NSDate *_userActivityStartDate;
}

@property(retain, nonatomic) NSDate *userActivityStartDate; // @synthesize userActivityStartDate=_userActivityStartDate;
@property(retain, nonatomic) NSMutableArray *receivedContactsQueue; // @synthesize receivedContactsQueue=_receivedContactsQueue;
@property(retain, nonatomic) CNContact *restoredUnsavedContact; // @synthesize restoredUnsavedContact=_restoredUnsavedContact;
@property(retain, nonatomic) CNContact *restoredContact; // @synthesize restoredContact=_restoredContact;
@property(retain, nonatomic) ContactsSplitViewController *splitViewController; // @synthesize splitViewController=_splitViewController;
@property(retain, nonatomic) UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)multipleUnknownContactsViewControllerDidComplete:(id)arg1;
- (void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2;
- (void)cancelModalUnknownPersons:(id)arg1;
- (void)saveUnknownPersons:(id)arg1;
- (void)_dismissContactsAndPresentNext;
- (void)_presentNextContacts;
- (id)_dequeueContacts;
- (void)_enqueueContacts:(id)arg1;
- (id)_contactsFromURL:(id)arg1;
- (_Bool)_showCardForContactWithIdentifier:(id)arg1;
- (_Bool)_showCardForContact:(id)arg1;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)application:(id)arg1 didDecodeRestorableStateWithCoder:(id)arg2;
- (void)application:(id)arg1 willEncodeRestorableStateWithCoder:(id)arg2;
- (_Bool)application:(id)arg1 shouldRestoreApplicationState:(id)arg2;
- (_Bool)application:(id)arg1 shouldSaveApplicationState:(id)arg2;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)_handleURL:(id)arg1;
- (id)dataSource;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end