//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NPHVoicemailPlaybackJumpView : UIView
{
    UIButton *_jumpBackButton;
    UIButton *_jumpForwardButton;
    id <NPHVoicemailPlaybackJumpViewDelegate> _delegate;
}

@property(nonatomic) __weak id <NPHVoicemailPlaybackJumpViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_updatePlaybackJumpButtons;
- (void)_voicemailPlaybackTap:(id)arg1;
- (id)_createVoicemailPlaybackJumpButton;
- (void)layoutSubviews;
- (void)_createConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end