//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WorldClockGlanceModel : NSObject
{
    id _citiesChangedObserver;
    _Bool _isPaused;
    NSString *_cityName;
    NSTimeZone *_cityTimezone;
    id <WorldClockGlanceModelDelegateProtocol> _delegate;
    double _cityLongitude;
    double _cityLatitude;
}

@property __weak id <WorldClockGlanceModelDelegateProtocol> delegate; // @synthesize delegate=_delegate;
@property(readonly) NSTimeZone *cityTimezone; // @synthesize cityTimezone=_cityTimezone;
@property(readonly) double cityLatitude; // @synthesize cityLatitude=_cityLatitude;
@property(readonly) double cityLongitude; // @synthesize cityLongitude=_cityLongitude;
@property(readonly) NSString *cityName; // @synthesize cityName=_cityName;
- (void).cxx_destruct;
- (void)localeChange:(id)arg1;
- (void)significantTimeChange:(id)arg1;
- (void)_loadCityData;
- (void)dealloc;
- (id)init;

@end