//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface RemindersCardContentController : UIViewController <UITextFieldDelegate, RemindersListHeaderViewDelegate>
{
    RemindersCardController *_containingCardController;
    RemindersListHeaderView *_headerView;
}

@property(readonly) RemindersListHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) RemindersCardController *containingCardController; // @synthesize containingCardController=_containingCardController;
- (void).cxx_destruct;
- (void)fontSizeChanged;
- (void)alarmsFired;
- (void)cardDidPresent;
- (void)setCardState:(unsigned long long)arg1 reloadModelIfNeeded:(_Bool)arg2;
- (void)configureHeaderView:(id)arg1;
- (int)headerViewStyle;
- (_Bool)isScheduled;
- (id)displayedCalendar;
- (void)setupConstraints;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end