//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface MILaunchServicesDatabaseGatherer : NSObject <MIFilesystemScannerDelegate>
{
    NSMutableDictionary *_coreServices;
    NSMutableDictionary *_systemApps;
    NSMutableDictionary *_userApps;
    NSMutableDictionary *_internalApps;
    NSMutableDictionary *_pluginKitPlugins;
    NSMutableDictionary *_vpnPlugins;
    NSMutableDictionary *_frameworks;
    _Bool _shouldUpdatePluginContainersWithParentID;
}

+ (id)entryForBundle:(id)arg1 inContainer:(id)arg2 withError:(id *)arg3;
+ (id)dictOfPluginKitPluginsInBundle:(id)arg1 updatingPluginParentID:(_Bool)arg2 withError:(id *)arg3;
+ (id)dictOfPluginKitPluginsInBundle:(id)arg1 withError:(id *)arg2;
- (void).cxx_destruct;
- (_Bool)performGatherWithError:(id *)arg1;
@property(readonly) NSDictionary *receipt;
- (_Bool)scanExecutableBundle:(id)arg1 inContainer:(id)arg2 withError:(id *)arg3;
- (id)_dictForEntry:(id)arg1;
- (_Bool)_scanBundle:(id)arg1 withError:(id *)arg2;
- (id)init;

@end