//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NCGGlanceLayoutAttributes : CUISGlanceLayoutAttributes
{
}

+ (void)initialize;
+ (void)load;
@property(readonly, nonatomic) float bodyFontLineHeightRounded;
@property(readonly, nonatomic) UIColor *contentBackgroundColor;
@property(readonly, nonatomic) UIColor *headerBackgroundColor;
@property(readonly, nonatomic) UIFont *bodyDesignatorFont;
@property(readonly, nonatomic) UIFont *bodyFont;
@property(readonly, nonatomic) float platterHeaderLabelOriginYToFirstBaseline;
@property(readonly, nonatomic) float contentFooterBaselineToBottom;
@property(readonly, nonatomic) float contentLastLineToBottom;
@property(readonly, nonatomic) float contentHeaderHeight;
@property(readonly, nonatomic) float cueDateBaselineOffset;
@property(readonly, nonatomic) float cueDayBaselineOffset;
@property(readonly, nonatomic) struct UIEdgeInsets calendarContentEdgeInsets;
@property(readonly, nonatomic) struct UIEdgeInsets calendarPlatterEdgeInsets;

@end