//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface RUStationTrackInfoViewAccessibility : __RUStationTrackInfoViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_axAnnotateStoreButton;
- (void)_accessibilityLoadAccessibilityInformation;
- (double)_accessibilityAllowedGeometryOverlap;
- (_Bool)shouldGroupAccessibilityChildren;
- (id)accessibilityContainerElements;
- (void)dealloc;
- (struct CGRect)accessibilityFrame:(id)arg1;
- (id)accessibilityLabel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end