//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SPBulletinClientFactory : CUISBulletinClientFactory <SPInterfaceViewControllerDelegate, SPCompanionConnectionDelegate, CUISBulletinClientFactoryExtension>
{
    _Bool _presentedAlert;
    _Bool _staticAlertPresented;
    NSString *_bulletinSectionID;
    NSDictionary *_appInfoDict;
    NSDictionary *_longLookInterfaceInfo;
    NSDictionary *_dynamicInterface;
    NSDictionary *_staticInterface;
    NSDictionary *_bulletinPresentationCustomInfo;
    NSBundle *_gizmoAppBundle;
    SPCompanionConnection *_companionConnection;
    SPInterfaceViewController *_spClientViewController;
    SPBulletinClientViewController *_bulletinClientViewController;
    NSDictionary *_actionsByTag;
    NSUserActivity *_wkUserActivity;
    CDUnknownBlockType _primaryPagePresentationCompletion;
    BBAction *_pendingTextSuggestionAction;
    CDUnknownBlockType _textReplySuggestionsCompletion;
    NSDate *_aggdLoggingStartTimestamp;
}

+ (void)initialize;
@property(retain, nonatomic) NSDate *aggdLoggingStartTimestamp; // @synthesize aggdLoggingStartTimestamp=_aggdLoggingStartTimestamp;
@property(copy, nonatomic) CDUnknownBlockType textReplySuggestionsCompletion; // @synthesize textReplySuggestionsCompletion=_textReplySuggestionsCompletion;
@property(nonatomic) __weak BBAction *pendingTextSuggestionAction; // @synthesize pendingTextSuggestionAction=_pendingTextSuggestionAction;
@property(nonatomic) _Bool staticAlertPresented; // @synthesize staticAlertPresented=_staticAlertPresented;
@property(nonatomic) _Bool presentedAlert; // @synthesize presentedAlert=_presentedAlert;
@property(copy, nonatomic) CDUnknownBlockType primaryPagePresentationCompletion; // @synthesize primaryPagePresentationCompletion=_primaryPagePresentationCompletion;
@property(retain, nonatomic) NSUserActivity *wkUserActivity; // @synthesize wkUserActivity=_wkUserActivity;
@property(copy, nonatomic) NSDictionary *actionsByTag; // @synthesize actionsByTag=_actionsByTag;
@property(retain, nonatomic) SPBulletinClientViewController *bulletinClientViewController; // @synthesize bulletinClientViewController=_bulletinClientViewController;
@property(retain, nonatomic) SPInterfaceViewController *spClientViewController; // @synthesize spClientViewController=_spClientViewController;
@property(retain, nonatomic) SPCompanionConnection *companionConnection; // @synthesize companionConnection=_companionConnection;
@property(retain, nonatomic) NSBundle *gizmoAppBundle; // @synthesize gizmoAppBundle=_gizmoAppBundle;
@property(copy, nonatomic) NSDictionary *bulletinPresentationCustomInfo; // @synthesize bulletinPresentationCustomInfo=_bulletinPresentationCustomInfo;
@property(copy, nonatomic) NSDictionary *staticInterface; // @synthesize staticInterface=_staticInterface;
@property(copy, nonatomic) NSDictionary *dynamicInterface; // @synthesize dynamicInterface=_dynamicInterface;
@property(copy, nonatomic) NSDictionary *longLookInterfaceInfo; // @synthesize longLookInterfaceInfo=_longLookInterfaceInfo;
@property(copy, nonatomic) NSDictionary *appInfoDict; // @synthesize appInfoDict=_appInfoDict;
@property(copy, nonatomic) NSString *bulletinSectionID; // @synthesize bulletinSectionID=_bulletinSectionID;
- (void).cxx_destruct;
- (void)bulletinClientViewControllerNeedsResizeViews;
- (void)invalidateBlurredHeaderForClientViewController;
- (void)launchApp;
- (id)launchAnnotationWithResponseInfo:(id)arg1;
- (void)launchAppWithActionItemID:(id)arg1 responseInfo:(id)arg2;
- (void)launchAppWithActionItemID:(id)arg1;
- (void)actionItemSelected:(id)arg1;
- (id)bulletinUniqueID;
- (id)calculateSectionIDsSupported;
- (id)defaultPrimaryPagePresentation;
- (id)primaryPagePresentationForStaticAlert;
- (void)presentStaticAlert;
- (void)presentDynamicAlert;
- (void)interfaceViewController:(id)arg1 setValue:(id)arg2 forKey:(id)arg3;
- (void)interfaceViewController:(id)arg1 sendAction:(id)arg2 withValue:(id)arg3;
- (_Bool)interfaceViewControllerHasNativeConnection:(id)arg1;
- (void)interfaceViewControllerDidUpdateInterfaceValues:(id)arg1;
- (void)interfaceViewControllerWillDisappear:(id)arg1;
- (void)interfaceViewControllerDidAppear:(id)arg1;
- (void)interfaceViewControllerDidDeactivate:(id)arg1;
- (void)interfaceViewControllerWillActivate:(id)arg1;
- (void)interfaceViewControllerRelease:(id)arg1;
- (void)interfaceViewController:(id)arg1 createCompanionControllerClass:(id)arg2 properties:(id)arg3 initializationContextID:(id)arg4;
- (void)companionConnection:(id)arg1 textSuggestions:(id)arg2 forNotificationActionWithID:(id)arg3 controllerWithID:(id)arg4;
- (void)companionConnection:(id)arg1 interfaceViewController:(id)arg2 presentNotificationWithType:(id)arg3;
- (void)companionConnection:(id)arg1 userActivity:(id)arg2;
- (void)companionConnection:(id)arg1 interfaceViewController:(id)arg2 setValue:(id)arg3 forKey:(id)arg4 property:(id)arg5;
- (void)textReplySuggestionsForLanguage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)sectionIDsSupported;
- (id)userActivity;
- (id)actionMenuPresentation;
- (void)invalidate;
- (void)primaryPagePresentationWillExpire;
- (double)extendedPrimaryPagePresentationTimeout;
- (id)primaryPagePresentation;
- (void)primaryPagePresentationWithCompletion:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithBulletins:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end